### PR TITLE
gdbserver: use numeric character references for unicode

### PR DESCRIPTION
**Pull request by liamwhite**

### CODE REVIEW

**Comment by boludoz** [comment]
Question, that is Linux unicode, right?

**Comment by liamwhite** [comment]
Unicode has nothing to do with platform. With this change, strings from the guest are delivered inside a packet containing XML with non-ASCII characters replaced by numeric references. The packets were always intended to contain only ASCII, which fixes the gdb reference client raising encoding errors.

**Comment by boludoz** [comment]
std::string_view is ASCII, true?

**Comment by liamwhite** [comment]
UTF-8 coexists with C text processing facilities. The std::string_view input to EscapeXML is a span of a UTF-8 string read from guest memory.

**Review by FearlessTobi — APPROVED** [review]

**Pull request merged**
