### PR TITLE
Update translations (2022-05-01)

### PR DESCRIPTION
**Pull request by zhaobot**
This PR is generated by [zhaowenlan1779/txbot](https://github.com/zhaowenlan1779/txbot).

### CODE REVIEW

**Comment by lioncash** [comment]
@zhaowenlan1779 this seems to have readded the soundtouch external

**Comment by Docteh** [comment]
https://github.com/zhaowenlan1779/txbot/blob/de39df4ef840a92485911889cf8ecbf541ae1252/txbot-yuzu.rb#L87
`    execute "tx pull -a --minimum-perc 47", TRANSLATIONS_PATH, true`

On transifex it shows as just below that cutoff: Finnish 46.6%

I was wondering what the requirements were for a language to make it into official builds, now I know.

**Comment by Docteh** [comment]
@zhaowenlan1779 I've done some research into the problem, I think the best move is to have the bot not have submodules checked out, as they're not necessary to do commits. The submodules are only needed to compile.

My suggestion is to delete this line (80) in [txbot-yuzu.rb](https://github.com/zhaowenlan1779/txbot/blob/main/txbot-yuzu.rb#L80)

```ruby
    execute "git submodule update"
```

Clear out the `REPO_PATH`, and run the script again.

Personally I'd delete the checked out files, but as an alternative:
```shell
git submodule deinit --all
git checkout 03d671fabc09e5d4f1032a4a0501a970598f9486
git submodule deinit --all
git checkout master
```

The first call to deinit won't clean out externals/soundtouch as `.gitmodules` not longer references it, but rewinding to a time when it was referenced will let it be removed.

**Comment by zhaowenlan1779** [comment]
Superseded by #8325.

**Pull request closed without merging**
