### PR TITLE
yuzu: fix "GPLv3.0++" in Chinese about dialog

### PR DESCRIPTION
**Pull request by Tachi107**
Introduced in 24d7a027dcaa7572108c620b86ce4ec5878bbcb1

Thanks to @mzji for spotting the issue

### CODE REVIEW

**Comment by FearlessTobi** [comment]
Thanks for your contribution.
However, the translations files should never be manually changed.
The mentioned fixes should instead be made via Transifex.

Closing.

**Comment by Tachi107** [comment]
Oh, ok, thanks

**Comment by Docteh** [comment]
@Tachi107 are you registered as a translator on transifex? I'm curious the strings over there have been updated after #8225

**Comment by Tachi107** [comment]
> @Tachi107 are you registered as a translator on transifex? I'm curious the strings over there have been updated after #8225

Unfortunately not. I tried to register but it seemed that the page had some issues, and after a few trials I gave up. Feel free to correct my errors if you already have an account :)

**Comment by Docteh** [comment]
@FearlessTobi Since the change in #8225 is just incrementing the license from `GPLv2.0` to `GPLv3.0+` would it be possible for someone registered as  say Deutsch to suggest translations for the other languages?

**Pull request closed without merging**
