### PR TITLE
yuzu: settings: Enable multicore, asynch GPU, and assembly shaders by default.

### PR DESCRIPTION
**Pull request by bunnei**
- In general, this is now the preferred settings for most games.

### CODE REVIEW

**Comment by v1993** [comment]
Looks like a good change. Only thing I'd like to note is that in my tests (OpenGL, Nvidia, Linux) assembly shaders allow slightly faster compilation but lower FPS compared to GLSL.

**Comment by ReinUsesLisp** [comment]
While assembly shaders might generate slower code than the GLSL equivalent, in my opinion the overall user experience is better in GLASM. Users that experience better results with GLSL can always change the setting manually.
As a side note, GLASM allows us to use precise on legacy drivers (Fermi) without causing internal compiler errors.

**Comment by pacproduct** [comment]
I do not know if it's because of this PR specifically, but performances on Luigi's Mansion 3 skyrocketed today. This game now runs more or less at normal speed on my environment, amazing. Was still almost unplayable yesterday as it was running at 30~60% speed yesterday! 👍

**Comment by v1993** [comment]
Does this also change settings on existing installations? Unlike luckier people, I had to "enjoy" 7-10 FPS and minor graphical glitches in games until giving configuration window a visit and turning assembly shaders off.

**Pull request merged**
