### PR TITLE
Update current compablity

### PR DESCRIPTION
**Pull request by ShalokShalom**
Pokemon Let`s Go is very playable since a couple of weeks. 
A couple of persons have shown this on Youtube in full play-throughs.
The improvements are staggering, this commits reflects this and avoids enforcing too high expectiations.

### CODE REVIEW

**Comment by legoj15** [comment]
IMO specifying a specific game isn't the best idea. No other emulator I can think of flaunts the fact it can run a specific game. Also, this is tying the name of this game to yuzu which could lead to future issues. I think the current status of the readme is fine

**Comment by ShalokShalom** [comment]
It looked to me that you optimised the emulator specifically to Pokemon Let`s Go. Simply because it got more and more playable every week. I thought you try to promote Yuzu through it :hugs: 

So, now that this is out, what do you think, how should Yuzu look like in its Readme?

I think it makes sense to link the [compability chart](https://yuzu-emu.org/game/) while it seems outdated.

**Comment by ShalokShalom** [comment]
How does this solve the current issue? 
Or answer any of my questions/suggestions?
Will you leave it as it is, which is just completely non-true?

**Comment by Hexagon12** [comment]
You can add your compatibility rating to the list by selecting Help - Report Compatibility while running the game in Yuzu. We have the compatibility rating site for a reason.

**Comment by ShalokShalom** [comment]
I am talking about the Readme page. I write this issue for a reason.

**Comment by Hexagon12** [comment]
I agree that the readme page is outdated, since some games can be perfectly played (like simple 2D titles) on master (Nightly) builds. Keep in mind that this isn't a readme for Canary, and master does not launch LGPE or any popular AAA game. If you want, you can make a new PR which suggests that, and not a specific game in mind.

**Pull request closed without merging**
