### PR TITLE
audio_renderer: Fix biquad filter

### PR DESCRIPTION
**Pull request by ogniK5377**
Originally the biquad filter was disabled due to issues with crackling before.

### CODE REVIEW

**Comment by v1993** [comment]
This is causing issues in Kirby: Star Allies. During stage three of final boss battle parts of music sound broken.

Here's how it sounds with this patch:

https://www.dropbox.com/s/yddl781mutvwmmf/kirby_bad.ogg?dl=0

Here's how it sounds normally:

https://www.dropbox.com/s/3pqfmukce8ol6qa/kirby_good.ogg?dl=0

Note that both versions include some sound effects from recorded gameplay. Curiously, issue doesn't happen while I stay in pause menu, either because of quieter music or different filtering.

**Comment by v1993** [comment]
Can this, please, be excluded from EA merge until issue I've pointed out is fixed?

**Comment by bunnei** [comment]
@ogniK5377 can you take a look at the above issue? Thanks!

**Comment by bunnei** [comment]
@ogniK5377 ping here

**Pull request closed without merging**
