### PR TITLE
Fixes Appveyor -Windows

### PR DESCRIPTION
**Pull request by bobthecooldad**
This is a my first pr... (be gentle 😄 )
I could get the msvc working but still looking for a way to get mingw working.

### CODE REVIEW

**Comment by MerryMage** [comment]
Hi. Modify the cmake command in appveyor.yml, not CMakeLists.txt directly.

**Comment by N00byKing** [comment]
While you're at it, maybe rebrand from citra to yuzu

**Comment by Jhon591** [comment]
A compiling error seems to be in arm_unicorn.cpp

Got mine locally done from downwards from this post.
https://gbatemp.net/threads/citra-unofficial-chinese-builds-discussion.431974/page-376#post-7786779

**Comment by bobthecooldad** [comment]
Close whilst changing from cmake to appyveyor.xml as i need to do lots of builds and test and dont want to spam this pr

**Comment by bobthecooldad** [comment]
@MerryMage Reverted the cmake as asked, changed from citra to yuzu in the lines of code.
Edited and added it in appveyor, Dont know how to squash as i have done this in github on website

**Comment by MerryMage** [comment]
The `else` conditional and the code you added following is not required. You can remove those lines you added. (Nothing later on depends on the variable.)

**Comment by bobthecooldad** [comment]
I only added it because it took a few minutes to work out what modules and i thought i could put it there so if it was msvc or it was mingw (if not then i will close this pr as nothing has been changed)
and i was not editing the mingw (like 15 minutes vs 8)

**Comment by jroweboy** [comment]
@bobthecooldad mingw will take some additional work as we need to compile unicorn from the yuzu-emu fork and link against that instead of the bundled unicorn binaries we provide. if you can just change appveyor to add a `-DUSE_YUZU_BUNDLED_UNICORN=Yes` to the cmake line for msvc that should be fine for a pr.

**Pull request closed without merging**
