### PR TITLE
audio: allow more latency in cubeb initialization

### LINKED ISSUE #11398: [regression] No sound with cubeb in yuzu 1539 on Linux
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1539

### Description of Issue

No sound using cubeb in Mainline 1539. Cubeb cannot see my Renoir / HDMI audio output device. SDL2 audio works as expected.

I have checked Mainline 1538 (previous) build and everyting works fine with sound in cubeb.

### Expected Behavior

Cubeb can detect correct audio device. Audio in games is ok.

### Reproduction Steps

Install yuzu 1539, run any game.

### Log File

-

### System Configuration

CPU: AMD Ryzen 4650 GE.
GPU/Driver: Intergrated Vega, Mesa 23.0.4
RAM: 32GB (4GB for graphics)
OS: Ubuntu 22.04 (5.15 kernel)

### PR DESCRIPTION
**Pull request by liamwhite**
Fixes #11398

### CODE REVIEW

**Review by FearlessTobi — APPROVED** [review]

**Review by AAAAAXfda — APPROVED** [review]
Alright, looks good to me. I'll be merging this in a moment.

**Comment by mr-sihc** [comment]
the guy said that cubeb can't even see the audio device, is this just fixing the auto selection?
that wasn't what he said

**Comment by liamwhite** [comment]
I didn't fix the issue blind, I easily reproduced it on my own machine. cubeb on pipewire incorrectly reports a minimum latency, in frames, of 1200 frames (240 samples * 5 channels) when we check what the latency is for 2 channel output. The _actual_ minimum latency available is 240 frames per channel, so the check simply does not work and should be removed.

**Comment by mr-sihc** [comment]
ok thats cool
but how does it handle a non suitable device when you select it, does it warn you or make it non-selectable?
or does it just make no sound and not warn you?

**Comment by liamwhite** [comment]
If a cubeb stream can't be opened and cubeb is selected in the audio options then a log message is printed and audio is disabled for the session. If you leave the selection on auto (the default) then it tries to open an SDL stream as well and only disables audio if both fail.

**Comment by ikamaletdinov** [comment]
@liamwhite Thanks a lot. That fixed the issue completely.

**Pull request merged**
