### PR TITLE
A novice attempt of implementing 'OpenBisFileSystem' and 'OpenBisStorage' FS service

### LINKED ISSUE #8239: unimplemented function 'OpenBisFileSystem'
used by Goldleaf
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8545785/yuzu_log.txt)

### PR DESCRIPTION
**Pull request by IamSanjid**
Before we begin I want to say I've very little experience with switch emulation so feel free to yell at me.

Yesterday saw this issue #8239 and was interested in how FS services work.

After reading [this simple explanation of OpenBisFileSystem](https://switchbrew.org/wiki/Filesystem_services#OpenBisFileSystem) and [OpenBisStorage explanation](https://switchbrew.org/wiki/Filesystem_services#OpenBisStorage) and following [this](https://switchbrew.org/wiki/Flash_Filesystem) documentation about FileSystem came up with this implementation.

Probably fixes #8239

### CODE REVIEW

**Comment by v1993** [comment]
AFAIK, @Morph1984 is working on filesystem rewrite, which likely implements these functions as well, although this should be a fine implementation in the meantime. Maybe discuss paths to newly introduced directories with Morph to ensure seamless transition with rewrite.

**Comment by IamSanjid** [comment]
> AFAIK, @Morph1984 is working on filesystem rewrite, which likely implements these functions as well, although this should be a fine implementation in the meantime. Maybe discuss paths to newly introduced directories with Morph to ensure seamless transition with rewrite.

ah then I think it's no longer needed it probably won't gonna help much since not many applications seem to use those fs services

**Comment by Morph1984** [comment]
Yes, @v1993 @IamSanjid I have already implemented this function among many others within the rewrite. While I appreciate the effort you've made to attempt to implement this, I very much prefer to have this implemented properly within the rewrite I am currently developing.

**Comment by IamSanjid** [comment]
@Morph1984 i should've contacted you beforehand but it's fine at least tried something new.

**Pull request closed without merging**
