### PR TITLE
CI: Re-enable building yuzu with Vulkan enabled on Linux and MinGW

### PR DESCRIPTION
**Pull request by lat9nq**
This is possible now with the updated Docker images and their updated packages. Before, there were build errors due to old QT5 packages on Ubuntu, but now it is feasible to build with Vulkan enabled. I tested on my machine with both the linux-mingw and linux-fresh Docker images, and the builds complete successfully on both master and master + early-access and mainline tagged PRs, as well as being able to enter games in Vulkan.

### CODE REVIEW

**Comment by callmenemo491** [comment]
@lat9nq , build failure...
https://dev.azure.com/yuzu-emu/de968a8e-869e-4f5a-a0c9-0cb1b14a9357/_apis/build/builds/4469/logs/28

**Comment by lat9nq** [comment]
@callmenemo491 @bunnei because #3860 isn't merged, everything is going to fail right now.

**Comment by lioncash** [comment]
I've merged #3860. Could this get a rebase, so that the buildbot can try building it on Windows, whenever you have the time?

**Comment by lioncash** [comment]
Looks like some other changes got added in.

If you can reset back to the initial change and then run:

```bash
git pull --rebase origin master
```
(Replace `origin` with the remote that points to the main yuzu repository if `origin` points to your fork)

on the branch. This should eliminate the extra commits being brought in.

**Comment by lat9nq** [comment]
Welp i messed this up. Sorry I'm a bit green with git

**Comment by lioncash** [comment]
> Sorry I'm a bit green with git

No worries! We've all been there.

I believe it can be recovered with the following:

Run:

```bash
# This will reset the branch back to the latest master commit.
git reset --hard ba02ff230aa8200f0657d66e3814622b619d3ee0
```

Then run:


```bash
# This will take the commit you initially made and attempt
# to apply it after the current master commit
git cherry-pick ec0ea0dfa1caf071f3de997d7556d0c7467a871b
```

and then all you should need to do is force push the commits to your branch again.

**Comment by lioncash** [comment]
Nicely done!

Will let the build run and then merge it once it succeeds.

**Comment by lat9nq** [comment]
Thanks for helping me! I pulled master changes before uploading, and that was definitely not the right move!

**Pull request merged**
