### PR TITLE
Simplify VkResult lookup

### PR DESCRIPTION
**Pull request by FireBurn**
How would you feel about using vk_enum_string_helper.h from https://github.com/KhronosGroup/Vulkan-Utility-Libraries rather than keeping vulkan_wrapper in sync yourself?

If you like the idea it would need to be added to externals I think

### CODE REVIEW

**Comment by FireBurn** [comment]
I think I've figured out the CMake bits, I'd also messed up a merge conflict

**Comment by FireBurn** [comment]
I think I know what's up with the windows builds, also might be able to simplify further

**Comment by FireBurn** [comment]
Hopefully that fixes the WIN32 stuff, using the dispatch stuff from vulkan utility libraries might be a futher improvement

**Comment by german77** [comment]
Your PR has formatting issues. Please address them first. See the CI details.

**Comment by Wunkolo** [comment]
Is there a particular reason to not just use `vk::to_string`? This is available in the Vulkan SDK through Vulkan-Hpp's `vulkan/vulkan_to_string.hpp` header.

https://github.com/KhronosGroup/Vulkan-Hpp/blob/fafe484a31265797e4716792ef1e1d529a3852cf/vulkan/vulkan_to_string.hpp#L3542-L3599

**Comment by FireBurn** [comment]
> Is there a particular reason to not just use `vk::to_string`? This is available in the Vulkan SDK through Vulkan-Hpp's `vulkan/vulkan_to_string.hpp` header.
> 
> https://github.com/KhronosGroup/Vulkan-Hpp/blob/fafe484a31265797e4716792ef1e1d529a3852cf/vulkan/vulkan_to_string.hpp#L3542-L3599

I've tried including this directly but it fails because of things not being defined, I've also tried including vulkan.hpp which works around those issues but it doesn't like vk::to_string, is there something special I need to do to include this that I'm missing?

**Comment by Wunkolo** [comment]
```diff
--- a/src/video_core/renderer_vulkan/vk_swapchain.cpp
+++ b/src/video_core/renderer_vulkan/vk_swapchain.cpp
@@ -16,6 +16,10 @@
 #include "video_core/vulkan_common/vulkan_wrapper.h"
 #include "vulkan/vulkan_core.h"
 
+#define VULKAN_HPP_ASSERT(x)
+#include "vulkan/vulkan_hpp_macros.hpp"
+#include "vulkan/vulkan_to_string.hpp"
+
 namespace Vulkan {
 
 namespace {
@@ -151,7 +155,8 @@ bool Swapchain::AcquireNextImage() {
         vk::Check(result);
         break;
     default:
-        LOG_ERROR(Render_Vulkan, "vkAcquireNextImageKHR returned {}", vk::ToString(result));
+        LOG_ERROR(Render_Vulkan, "vkAcquireNextImageKHR returned {}",
+                  ::vk::to_string(::vk::Result(result)).c_str());
         break;
     }
``` 

This ended up working for me. It's kinda ugly since this seems to be the first time Vulkan-Hpp is being touched and uses an `std::string` rather than reading from `.rodata` but it uses what's already available in https://github.com/KhronosGroup/Vulkan-Headers/tree/main/include/vulkan. So on second thought this might not be a good idea for now.

Based on https://github.com/yuzu-emu/yuzu/pull/3566 from several years ago, it looks like the avoidance of Vulkan-Hpp was done on purpose. Might be worth revisiting this rational if Vulkan-Hpp can strictly be used to simplify some patterns like structure-creation, enums, to_string, etc.

**Comment by FireBurn** [comment]
If you're still happy to switch to this, I think there are further things that could be reused in vk_dispatch_table.h, vk_format_utils.h & vk_struct_helper.hpp

**Comment by FireBurn** [comment]
Is there anything else required?

**Review by Wunkolo — APPROVED** [review]

**Review by liamwhite — APPROVED** [review]

**Comment by abouvier** [comment]
> Is there anything else required?

Yeah, why did you duplicate the content of `video_core/vulkan_common/vulkan.h` inside `video_core/vulkan_common/vk_enum_string_helper.h`?

And are you sure you want to hijack the option `YUZU_USE_EXTERNAL_VULKAN_HEADERS` for a different library?

**Comment by FireBurn** [comment]
> > Is there anything else required?
> 
> Yeah, why did you duplicate the content of `video_core/vulkan_common/vulkan.h` inside `video_core/vulkan_common/vk_enum_string_helper.h`?
> 
> And are you sure you want to hijack the option `YUZU_USE_EXTERNAL_VULKAN_HEADERS` for a different library?

Sorry for the delay in replying, I've been away on holiday

The helper was to fix the windows build issues, if all that isn't required I can cut it down if you like

YUZU_USE_EXTERNAL_VULKAN_HEADERS was because Vulkan-Utility-Libraries was mostly a bunch of headers, but I can make it a seperate switch if you prefer

**Comment by FireBurn** [comment]
@liamwhite @Wunkolo do you have preferences about the above?

**Comment by liamwhite** [comment]
Please make a separate CMake variable for the utility library

**Comment by FireBurn** [comment]
My Linux and Android builds still build, please could you kick of the workflows that test the windows builds?

**Comment by abouvier** [comment]
Your `vk_enum_string_helper.h` (like `vma.h`) should just be:
```cpp
#pragma once

#include "video_core/vulkan_common/vulkan.h"
#include <vulkan/vk_enum_string_helper.h>
```

**Comment by FireBurn** [comment]
@liamwhite @abouvier @Wunkolo are you happy to commit this now?

**Review by abouvier — APPROVED** [review]

**Comment by Calinou** [comment]
This PR should fix the build on Fedora 39 too, as I've had to add `#define VK_ENABLE_BETA_EXTENSIONS` above `#include <vulkan/vulkan.h>` in `src/video_core/vulkan_common/vulkan.h` to get yuzu to build here. This define is needed so that the `VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR` constant is set.

**Comment by liamwhite** [comment]
@FireBurn please resolve the comment from abouvier

**Comment by abouvier** [comment]
It's resolved now, it's a old failed review :p

**Pull request merged**
