### PR TITLE
Add macos moltenvk bundle, Add copy moltevk dylib script

### PR DESCRIPTION
**Pull request by vonchenplus**
The main addition in this PR  is an automated copy script for MoltenVK. It allows for the launch of some simple games on my Mac Pro. However, there are still quite a few issues that need to be resolved.

image

### CODE REVIEW

**Comment by Steveice10** [comment]
FYI upstream MoltenVK uploads prebuilt tars you could use to releases here https://github.com/KhronosGroup/MoltenVK/releases

**Comment by vonchenplus** [comment]
> FYI upstream MoltenVK uploads prebuilt tars you could use to releases here https://github.com/KhronosGroup/MoltenVK/releases

Can't use MoltenVK directly because we need the VK_KHR_portability_enumeration extension

**Comment by liamwhite** [comment]
If MoltenVK now requires you to _not_ pass the portability enumeration extension, then you can remove it. Previously they did...

**Comment by Steveice10** [comment]
It works fine regardless. In Citra we support trying to load a system libvulkan dylib (with the debug layers and everything), and fall back to the bundled libMoltenVK dylib if it's not present on the system.

**Comment by liamwhite** [comment]
Okay, then can we check if portability enumeration exists and add it if it does?

**Comment by vonchenplus** [comment]
> 

no portability extension found if use moltevk directly.

**Comment by liamwhite** [comment]
Yes, that's why I'm asking to check if it exists, and add it if it does, for compatibility with the libvulkan loader.

**Comment by vonchenplus** [comment]
> Yes, that's why I'm asking to check if it exists, and add it if it does, for compatibility with the libvulkan loader.

So, would you like to reintegrate VK_KHR_portability_enumeration? I've examined several others (such as Dolphin), and it appears that they all directly utilize MoltenVK.

**Comment by Steveice10** [comment]
> So, would you like to reintegrate VK_KHR_portability_enumeration? I've examined several others (such as Dolphin), and it appears that they all directly utilize MoltenVK.

If you don't leave compatibility with the libvulkan loader (detect if the portability extension is available and request it if so), you won't be able to use debug validation layers.

**Review by liamwhite — APPROVED** [review]

**Pull request merged**
