### PR TITLE
vma: enable options everywhere

### PR DESCRIPTION
**Pull request by abouvier**
The `VMA_*` options need to be defined before every inclusion of `vk_mem_alloc.h`, not just in the implementation. So regroup them in a header file with `vk_mem_alloc.h` and include this one everywhere instead.

### CODE REVIEW

**Comment by abouvier** [comment]
Apparently the format verifier wants `#include "video_core/vulkan_common/vma.h"` to be before `#include "video_core/vulkan_common/vulkan_wrapper.h"`, which means that `vk_mem_alloc.h` will include `vulkan/vulkan.h` first and before `vulkan_wrapper.h`, so the `#define VK_USE_PLATFORM_WIN32_KHR` etc. also need to be in `vma.h`.

**Comment by abouvier** [comment]
To avoid macros duplication, I also created a `video_core/vulkan_common/vulkan.h` header regrouping all vulkan options, to be included in place of `<vulkan/vulkan.h>`

**Comment by liamwhite** [comment]
You can make the clang-format not strictly order headers by making sections separated by double linebreaks, if that makes things easier.

**Comment by abouvier** [comment]
Never mind, it's better organized now and the headers can be included in any order ;)

**Review by liamwhite — APPROVED** [review]

**Pull request merged**
