### PR TITLE
android: Fix input overlay version check

### PR DESCRIPTION
**Pull request by t895**

### CODE REVIEW

**Review by liamwhite — APPROVED** [review]

**Comment by AbandonedCart** [comment]
https://github.com/yuzu-emu/yuzu/blob/master/src/android/app/build.gradle.kts#L58

Android R is API 30. You don't need a check at all.

**Comment by t895** [comment]
> https://github.com/yuzu-emu/yuzu/blob/master/src/android/app/build.gradle.kts#L58
> 
> Android R is API 30. You don't need a check at all.

I'm aware. This is just for when someone wants to build it themselves on a lower API level.

**Comment by AbandonedCart** [comment]
> I'm aware. This is just for when someone wants to build it themselves on a lower API level.

That doesn't really make sense, though. It sounds like instead of throwing an error that will cause someone to look into it, you're suppressing the error so they have to go digging line by line for where you set a minimum API without any handling for the lower ones.

**Comment by t895** [comment]
I'd prefer to have the input overlay load with the small drawback of not insetting the view and allow emulation instead of throwing an error and crashing on lower API levels. It's not worth creating a new codepath for Android 10 and below to inset the view since we're not supporting it. This is just to allow the bare minimum.

**Comment by AbandonedCart** [comment]
So you want it to build for a lower API without any changes and simply not work as expected?

**Comment by t895** [comment]
Yes

**Comment by AbandonedCart** [comment]
> Yes

Well that seems malicious, but whatever then.

**Review by bunnei — APPROVED** [review]

**Pull request merged**
