### PR TITLE
Added Czech

### PR DESCRIPTION
**Pull request by honzapatCZ**
as title says.
PS: not sure about control_metadata

### CODE REVIEW

**Comment by Hexagon12** [comment]
If you want to translate yuzu's user interface, please refer to our [Transifex project](https://www.transifex.com/yuzu-emulator/yuzu/).
If you want for all games to be in Czech, you're out of luck. 
That's not how you would add a language to a emulator.

**Comment by honzapatCZ** [comment]
I have done so last month still not in. The option is missing. I thought that will be it.

**Comment by ogniK5377** [comment]
The changes you have made do not reflect how the Nintendo Switches has them. You cannot add new languages, only Nintendo can add new languages to the switch and if games use them then it will work

**Comment by honzapatCZ** [comment]
@ogniK5377 I know. I only wanted to translate the emulator.

**Pull request closed without merging**
