### PR TITLE
externals: Update dynarmic to 6.2.3

### PR DESCRIPTION
**Pull request by merryhime**
Updates dynarmic from 6.2.1 to 6.2.3. Notable changes:

- fmt 9.0.0 compatible for those bleeding edge users not using 8.x.x?
- Minor IR size optimization.
- Minor flag improvements for 32-bit ARM guests.
- Bugfix for QC flag for VectorSignedSaturatedDoublingMultiply operation when output is unused (rare and unnoticeable; no known real-world example of this bug).

### CODE REVIEW

**Comment by Docteh** [comment]
To me this just looks like a bump in dynarmic, or is following HEAD an option for submodule?

**Comment by merryhime** [comment]
Automatically tracking HEAD is not an option, and you wouldn't want that behaviour anyway.

**Comment by Docteh** [comment]
Thanks

referring to a PR as "short-lived" confused me, unless its like that reversion of VS2022 :wink:

**Comment by lat9nq** [comment]
Build failure is not related to this PR.

**Review by liamwhite — APPROVED** [review]

**Pull request merged**
