### PR TITLE
general: compress png images

### PR DESCRIPTION
**Pull request by Fdawgs**
Losslessly compress PNG images using [Pngcrush](https://pmt.sourceforge.io/pngcrush/) to reduce the build size by a few bytes.

### CODE REVIEW

**Comment by Docteh** [comment]
404 files is unwieldy for review. 

I crunched the numbers and these are the top 25

14966 dist/qt_themes/colorful/icons/48x48/bad_folder.png
4962 dist/icons/overlay/controller_pro.png
3894 dist/icons/overlay/controller_single_joycon_right.png
3884 dist/icons/overlay/controller_single_joycon_left.png
3837 dist/icons/overlay/controller_dual_joycon.png
3323 dist/icons/overlay/controller_single_joycon_right_dark.png
3321 dist/icons/overlay/controller_single_joycon_left_dark.png
2957 dist/icons/overlay/controller_pro_dark.png
2782 dist/icons/overlay/controller_dual_joycon_dark.png
2748 dist/icons/overlay/button_press_stick.png
2395 dist/icons/overlay/controller_handheld.png
2326 dist/qt_themes/default/icons/256x256/yuzu.png
2220 dist/icons/overlay/button_X.png
2007 dist/qt_themes/qdarkstyle/icons/256x256/plus_folder.png
1847 dist/icons/overlay/button_A.png
1841 dist/icons/overlay/button_B.png
1833 dist/icons/overlay/button_Y.png
1765 dist/icons/controller/applet_pro_controller_dark_disabled.png
1745 dist/icons/overlay/controller_handheld_dark.png
1696 dist/icons/overlay/osk_button_backspace_dark.png
1685 dist/icons/controller/applet_pro_controller_midnight_disabled.png
1647 dist/icons/overlay/osk_button_backspace.png
1604 dist/icons/overlay/controller_single_joycon_left_y_dark.png
1573 dist/qt_themes/default/icons/256x256/plus_folder.png
1543 dist/icons/controller/applet_pro_controller_disabled.png

Somewhere along the line its not worth the hassle

The bottom 25 for reference

33 dist/qt_themes/qdarkstyle_midnight_blue/rc/toolbar_separator_horizontal_focus.png
33 dist/qt_themes/qdarkstyle_midnight_blue/rc/branch_end_disabled.png
32 dist/qt_themes/qdarkstyle_midnight_blue/rc/transparent_pressed@2x.png
32 dist/qt_themes/qdarkstyle_midnight_blue/rc/transparent_focus@2x.png
32 dist/qt_themes/qdarkstyle_midnight_blue/rc/transparent_disabled@2x.png
32 dist/qt_themes/qdarkstyle_midnight_blue/rc/transparent@2x.png
32 dist/qt_themes/qdarkstyle_midnight_blue/rc/toolbar_separator_vertical_disabled.png
32 dist/qt_themes/qdarkstyle_midnight_blue/rc/line_horizontal_disabled@2x.png
31 dist/qt_themes/qdarkstyle_midnight_blue/rc/line_vertical_pressed.png
31 dist/qt_themes/qdarkstyle_midnight_blue/rc/line_vertical_focus.png
31 dist/qt_themes/qdarkstyle_midnight_blue/rc/line_vertical_disabled.png
31 dist/qt_themes/qdarkstyle_midnight_blue/rc/line_horizontal_pressed@2x.png
31 dist/qt_themes/qdarkstyle_midnight_blue/rc/line_horizontal_focus@2x.png
31 dist/qt_themes/qdarkstyle_midnight_blue/rc/branch_line_pressed.png
31 dist/qt_themes/qdarkstyle_midnight_blue/rc/branch_line_focus.png
31 dist/qt_themes/qdarkstyle_midnight_blue/rc/branch_line_disabled.png
30 dist/qt_themes/qdarkstyle_midnight_blue/rc/line_horizontal@2x.png
30 dist/qt_themes/qdarkstyle_midnight_blue/rc/line_horizontal.png
26 dist/qt_themes/qdarkstyle_midnight_blue/rc/line_horizontal_pressed.png
26 dist/qt_themes/qdarkstyle_midnight_blue/rc/line_horizontal_focus.png
26 dist/qt_themes/qdarkstyle_midnight_blue/rc/line_horizontal_disabled.png
22 dist/qt_themes/qdarkstyle_midnight_blue/rc/transparent_pressed.png
22 dist/qt_themes/qdarkstyle_midnight_blue/rc/transparent_focus.png
22 dist/qt_themes/qdarkstyle_midnight_blue/rc/transparent_disabled.png
22 dist/qt_themes/qdarkstyle_midnight_blue/rc/transparent.png

**Comment by Fdawgs** [comment]
Thanks @Docteh, apologies for the large amount!
Is it worth be just doing the top 25 then?

**Comment by Docteh** [comment]
Yeah, just do the top 25, it'll scatter enough reminders through the tree so that in the future anyone making additions/modifications people will think about PNG sizes

**Comment by Fdawgs** [comment]
> Yeah, just do the top 25, it'll scatter enough reminders through the tree so that in the future anyone making additions/modifications people will think about PNG sizes

Cheers, updated the PR.

**Review by Docteh — APPROVED** [review]

**Review by bunnei — APPROVED** [review]

**Comment by bunnei** [comment]
LGTM, thanks!

**Pull request merged**
