### PR TITLE
Service/vi: Fix normal_params_size in GetDisplayResolution

### PR DESCRIPTION
**Pull request by Hexagon12**
The service requires normal_params_size to be 4, not 6. Fixes an issue in Minecraft Story Mode.

### CODE REVIEW

**Comment by mailwl** [comment]
It's wrong! w & h - u64 values both, so, change should be in other place (push<u64> instead of push<u32>)

**Comment by Hexagon12** [comment]
@mailwl You can open a PR yourself if you think that my PR is wrong.
~~Also pls implement NFP IUser~~

**Comment by mailwl** [comment]
i will later. but use switchbrew for reference in future: http://switchbrew.org/index.php?title=Display_services#GetDisplayResolution

**Comment by greggameplayer** [comment]
yes it might be wrong because this error stay in kirby star allies

**Pull request merged**
