### PR TITLE
video_core: Use std::jthread and std::stop_token for worker threads

### PR DESCRIPTION
**Pull request by ReinUsesLisp**
Marking this as a draft because `libc++` doesn't yet support `std::jthread` and `std::stop_token`.

Fixes shutdown issues and simplifies the code overall. Default destructors stop worker threads naturally.

### CODE REVIEW

**Comment by lat9nq** [comment]
Fixes #5195

**Comment by v1993** [comment]
Does this supersede PR #5337?

**Comment by ReinUsesLisp** [comment]
Yes, I wasn't aware that PR existed.
This notifies all the condition variables automatically when the `std::stop_token` gets signaled. We don't have to worry about notifying anything, the jthread destructors take care of it.

**Comment by ReinUsesLisp** [comment]
Unmarking this as draft, we already use features libc++ doesn't support.

**Comment by ReinUsesLisp** [comment]
Untagging because our current version of msvc doesn't support it.

**Comment by Morph1984** [comment]
Superseded by #7019

**Pull request closed without merging**
