### PR TITLE
android: add oboe audio sink

### PR DESCRIPTION
**Pull request by liamwhite**
This should fix the issues where audio gets permanently cut off when changing output devices or starting a screen capture.

### CODE REVIEW

**Comment by gidoly** [comment]
Changing not charging

**Comment by t895** [comment]
Please add Oboe to the list of audio backends in the android frontend. (I think you have to do that for qt as well?)

**Comment by liamwhite** [comment]
Oboe cannot be used on non-Android so it doesn't really make sense to add it to Qt

**Comment by coolllman** [comment]
This pr broken sound.

**Comment by liamwhite** [comment]
My audio is fine. Feel free to switch to cubeb.

**Comment by liamwhite** [comment]
@coolllman also, provide a log file so I can see how oboe configured your device.

**Comment by brujo5** [comment]
No audio problem here, tested oboe with few games and work perfectly fine on my poco F4.

**Comment by coolllman** [comment]
With cubeb all good, 
log with oboe
[Uploading yuzu_log.txt…]()

**Comment by liamwhite** [comment]
After some testing in games with very low framerate, I believe the crackling may be caused by underruns from the priority being too low. Can you retry with the [latest artifact](https://nightly.link/yuzu-emu/yuzu/actions/runs/7242685525) where I fixed the priority, to see if the issue persists?

**Comment by coolllman** [comment]
Test latest artifact, same problem
[yuzu_log2.txt](https://github.com/yuzu-emu/yuzu/files/13700618/yuzu_log2.txt)

**Comment by djdp77** [comment]
> With cubeb all good, log with oboe [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13699806/yuzu_log.txt)

Have the same issue in Undertale, audio crackles with oboe

**Comment by liamwhite** [comment]
Please get a new log with the latest artifact https://nightly.link/yuzu-emu/yuzu/actions/runs/7250152895
I have fully specified all stream parameters for the sink and added more detailed logging for things that might have gone wrong.

**Comment by djdp77** [comment]
I tried it with the attifact but no longer get crackling in Undertale, same for android-165

**Comment by coolllman** [comment]
165 fix problem👍

**Review by FernandoS27 — APPROVED** [review]

**Pull request merged**
