### PR TITLE
cmake: fix cpp-jwt build

### PR DESCRIPTION
**Pull request by abouvier**
Links `cpp-jwt` with `openssl`.

Maybe solve https://github.com/yuzu-emu/yuzu/issues/9840.

~~Not using `cpp-jwt/CMakeLists.txt` circumvents the `find_package(OpenSSL REQUIRED)` present inside.~~

### CODE REVIEW

**Comment by abouvier** [comment]
Why not fetch `openssl` via `vcpkg` on Windows? It's used by `cpp-jwt` and `cpp-httplib` and will considerably simplify the inclusion of both externals.

**Comment by liamwhite** [comment]
@abouvier I think it would be a good idea to use openssl from vcpkg and completely kill the libressl submodule - it doesn't even compile on modern Linux distros, so you have to use the system version). My only concern is the version from vcpkg not overriding the one in the Windows ADO build environment ([which broke previously](https://github.com/yuzu-emu/yuzu/pull/9302)), but hopefully it will have priority.

**Comment by liamwhite** [comment]
Azure DevOps is comical and runs out of disk space when compiling with this PR merged.

**Comment by liamwhite** [comment]
(Please ignore previously deleted comment)

**Review by liamwhite — APPROVED** [review]

**Pull request merged**
