### PR TITLE
externals: update cubeb

### LINKED ISSUE #7499: No audio after sleep mode
This issue is easily reproducible.
When emulation is running I close the notebook. 
When notebook is opened and windows go out of sleep emulation continues to run fine except for sound (no sound at all).
I have to restart the game for sound to come back.

Is it possible to fix this? On some other emulators (for example Citra or Dolphin) sound returns to normal fine after sleep.

### PR DESCRIPTION
**Pull request by danilaml**
Fixes #7499

### CODE REVIEW

**Review by bunnei — APPROVED** [review]

**Comment by amayra** [comment]
why not use git directly?

**Comment by danilaml** [comment]
@amayra what do you mean?

**Comment by amayra** [comment]
> @amayra what do you mean?

i mean why yuzu use [cubeb @ 75d9d12](https://github.com/mozilla/cubeb/tree/75d9d125ee655ef80f3bfcd97ae5a805931042b8) this 2-year-old repo and not the master repo of cubeb

is there any reason for not use the master repo directly when you compiled yuzu ?

**Comment by danilaml** [comment]
@amayra this is what this PR does?

**Comment by Squall-Leonhart** [comment]
This should also fix no audio after device change.

**Pull request merged**
