### PR TITLE
libnx: crappy fix for GfxMode_TiledSingle rendering mode

### PR DESCRIPTION
**Pull request by Cpasjuste**
This fix yuzu only rendering the first frame with libnx and GfxMode_TiledSingle mode. It can maybe have some side effect.

### CODE REVIEW

**Comment by bunnei** [comment]
We're actively working on a proper fix for this - so I'm going to hold off on merging this for now until we understand this better

**Comment by Cpasjuste** [comment]
No problem. At least this could give some hint, but also allow impatient people like me to make it work for now :)

**Comment by bunnei** [comment]
Is this still needed?

**Comment by bunnei** [comment]
I assume this is no longer useful - please open an issue if you believe that there are any bugs here.

**Pull request closed without merging**
