### PR TITLE
input_common: Add support for analog toggle

### PR DESCRIPTION
**Pull request by german77**
Allows to toggle buttons that have analog inputs.

### CODE REVIEW

**Comment by unuruu5760** [comment]
I really, really, really, really, really, really thank you. you are the best!!

**Comment by unuruu5760** [comment]
Oh no!!!!!!!!!!!! , I just tested it. But this doesn't work in games.

**Comment by unuruu5760** [comment]
> 



> It does work. But remember this is another PR. #8863 fixes the error in game while this one add support for analog toggle. Wait until both are on mainline.

YEAH ,I tested using this PR but  it didn't work. Is this wrong?

**Comment by german77** [comment]
I mean you need to compile yourself a custom build with both PR merged or just wait until both are on mainline. They are small changes it will be in less than a week

**Review by bunnei — APPROVED** [review]

**Pull request merged**
