### PR TITLE
Implement RGB565 framebuffer Pixel Format

### PR DESCRIPTION
**Pull request by greggameplayer**
tested on Lego Ninjago and seems to be good.
Need some test for RGB565 Framebuffer format.

### CODE REVIEW

**Comment by Yvar192** [comment]
Have you properly reverse engineered this implementation?

**Comment by Hexagon12** [comment]
Please check your PR over again. It causes massive regressions on a lot of titles.

**Comment by greggameplayer** [comment]
@Hexagon12 tell me more what exactly ?

**Comment by greggameplayer** [comment]
@DarkLordZach i'm nearly from the requested result for RGB565 so i work on it

**Comment by DarkLordZach** [comment]
That's great, but doesn't answer my questions...

**Comment by greggameplayer** [comment]
I will do another PR for BGRA8 framebuffer Pixel Format in order to merge it quickly

**Comment by greggameplayer** [comment]
It's not 100% correct it give me that result on vt52 demo homebrew
image

instead of : 
image

**Comment by greggameplayer** [comment]
If you know what's wrong in my implementation don't hesitate to say it to me

**Comment by DarkLordZach** [comment]
Closing as stale/unresponsive and incorrect implementation

**Pull request closed without merging**
