### PR TITLE
Fixed controller applet crashing when on FW17+

### PR DESCRIPTION
**Pull request by Macj0rdan**
Fixed this by implementing `SetTouchscreenDimensions`

### CODE REVIEW

**Comment by Kelebek1** [comment]
How often is it called? I'd prefer a Debug log rather than Info if possible.

**Comment by Macj0rdan** [comment]
> How often is it called? I'd prefer a Debug log rather than Info if possible.

@german77 Said I should make it infos.
Narr what do you say?

**Comment by german77** [comment]
Just once and only by the controller applet. This function destroys the current state on touch screen on HW. So it will never be spammed since that will break touch.

**Comment by Kelebek1** [comment]
Ok that's fine then.

**Review by liamwhite — APPROVED** [review]

**Pull request merged**
