### PR TITLE
shader-ir: Minor cleanup-related changes

### PR DESCRIPTION
**Pull request by lioncash**
Performs a few minor cleanup changes, like removing unused headers, clarity renaming, and getting rid of unnecessary atomic reference count increment and decrements.

### CODE REVIEW

**Comment by FernandoS27** [comment]
Why doing std move on shared pointers? that's kinda dangerous.

**Comment by lioncash** [comment]
How so? It's no more dangerous than using std::move on any other type.

**Comment by FernandoS27** [comment]
I don't know, I've had bad experience with them causing memory corruption and troubles when used on shared pointers. I think this should be tested just to make sure. I really don't feel like reverting a PR this big.

**Comment by FernandoS27** [comment]
You need to rebase.

**Comment by lioncash** [comment]
Done

**Pull request merged**
