### PR TITLE
Make builds optimize better, add optimization options and make asserts unlikely.

### PR DESCRIPTION
**Pull request by FernandoS27**
This Pull Request adds a few things:

- Global program linker optimizations, fastcall optimizations, windows application optimizations, base ISA up to SSE 4.2, etc to EA builds. It will come later to mainline if all good.
- Add an option to generate debug information faster while parallel compiling.
- make all ifs in ASSERTS be [[unlikely]]

### CODE REVIEW

**Comment by v1993** [comment]
If you're going for max optimization, cmake has a portable way of turning LTO on:

```
-DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON -DCMAKE_POLICY_DEFAULT_CMP0069=NEW
```

**Comment by FernandoS27** [comment]
> If you're going for max optimization, cmake has a portable way of turning LTO on:
> 
> ```
> -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON -DCMAKE_POLICY_DEFAULT_CMP0069=NEW
> ```

ty, I'll try this.

**Comment by goldenx86** [comment]
Heh, awaiting the 5 people with a Phenom, Core 2 Duo or VIA CPU that will come complaining.

**Comment by v1993** [comment]
@goldenx86 They always can switch to mainline and use saved money to buy a better CPU :stuck_out_tongue:.

**Comment by FernandoS27** [comment]
I removed SS4.2 base. I think we need to tell them in advance.

**Comment by ViNi-Arco** [comment]
SSE4.1 is a more "comfortable" requirement, if you have a processor that is older than q9450/q9650 and does not support SSE4.1 and that is not at least quad core, you will not perform satisfactorily in many scenarios.

**Comment by goldenx86** [comment]
I don't expect good performance from any CPU lacking an IMC.

**Comment by FernandoS27** [comment]
> SSE4.1 is a more "comfortable" requirement, if you have a processor that is older than q9450/q9650 and does not support SSE4.1 and that is not at least quad core, you will not perform satisfactorily in many scenarios.

you cannot set SEE4.1 in MSVC. Only SSE2, SEE4.2(this option is hidden), AVX, AVX2 and AVX512.

**Comment by ViNi-Arco** [comment]
> you cannot set SEE4.1 in MSVC. Only SSE2, SEE4.2(this option is hidden), AVX, AVX2 and AVX512.

Does MSVC have this limitation!? Mr.Fernando you could try Clang or Mingw, MSVC has Clang, right.

At first I thought you would implement SSE4.2 with assembler in your code, that's why I recommended SSE4.1 for having a wider range of CPU's with support, and if you really need MSVC it's ok to include SSE4.2 in your builds, since it is with Flag in the Compiler, _those with an older CPU will have to compile on their own to try to get better performance anyway.._

**Comment by Tachi107** [comment]
> If you're going for max optimization, cmake has a portable way of turning LTO on:
> 
> ```
> -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON -DCMAKE_POLICY_DEFAULT_CMP0069=NEW
> ```

I believe that `-DCMAKE_POLICY_DEFAULT_CMP0069=NEW` is not necessary as yuzu targets CMake >=3.15, so it should default to the `NEW` behaviour anyway

**Comment by v1993** [comment]
> I believe that `-DCMAKE_POLICY_DEFAULT_CMP0069=NEW` is not necessary as yuzu targets CMake >=3.15, so it should default to the `NEW` behaviour anyway

Can you back that up, please? Because, quoting official [CMake docs](https://cmake.org/cmake/help/v3.22/policy/CMP0069.html):

> This policy was introduced in CMake version 3.9. CMake version 3.22.1 warns when the policy is not set and uses `OLD` behavior. Use the `cmake_policy()` command to set it to `OLD` or `NEW` explicitly.

Passing in `-DCMAKE_POLICY_DEFAULT_CMP0069=NEW` from command line is an alternative to using `cmake_policy`.

**Comment by Tachi107** [comment]
> Can you back that up, please? Because, quoting official [CMake docs (for CMake 3.22)](https://cmake.org/cmake/help/v3.22/policy/CMP0069.html):
> > This policy was introduced in CMake version 3.9. CMake version 3.22.1 warns when the policy is not set and uses OLD behavior

Yep, when the policy is not set CMake uses the `OLD` behaviour, but whether a policy is set or not depends on the value of `cmake_minimum_required`; if you set the minimum required version to a certain value, all policy introduced up to that version follow the `NEW` behaviour. If you scroll down to the bottom of the page you liked, under the "Examples" section, you can see that in the last three examples the minimum required version is set to 3.9, and a comment reminds the reader that that way the policy gets automatically set to `NEW`.

The [`cmake-policy`](https://cmake.org/cmake/help/v3.22/manual/cmake-policies.7.html#introduction) manual explains it better than me:

> The cmake_minimum_required() command does more than report an error if a too-old version of CMake is used to build a project. It also sets all policies introduced in that CMake version or earlier to NEW behavior. To manage policies without increasing the minimum required CMake version, the if(POLICY) command may be used:

**Comment by v1993** [comment]
Thanks for explaining! I *think* there were some issues with subprojects (libraries from external) not using LTO without explicitly passing in command-line flag, but this requires re-testing.

**Comment by Tachi107** [comment]
> I _think_ there were some issues with subprojects (libraries from external) not using LTO without explicitly passing in command-line flag, but this requires re-testing.

It would make sense, as if subprojects declare a minimum required version lower than 9 the policy would default to the `OLD` behaviour, but I'm not sure either

**Comment by FernandoS27** [comment]
now we'll add it for mainline as well.

**Comment by Tatsh** [comment]
Can this change be made to Linux builds or is this not relevant for that?

**Comment by FernandoS27** [comment]
> Can this change be made to Linux builds or is this not relevant for that?

it's possible but most linux users compile yuzu locally, they can add -march=native & -O3 & -flto

**Comment by Tatsh** [comment]
I have no plans to add an LTO option in my package for Gentoo unless upstream supports that configuration, preferably with a CMake flag.

**Comment by v1993** [comment]
LTO can be activated in CMake by using `-DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON` (and *probably* also `-DCMAKE_POLICY_DEFAULT_CMP0069=NEW` - see discussion above) - passing `-flto` directly is not recommended (real example - this will cause linking errors if you'll try to use clang due to missing call to `ar`).

If yuzu wishes to add LTO as an option, something like this can be used:

```CMake
set(YUZU_LTO OFF CACHE BOOL "Use LTO if supported by compiler")

...

if (YUZU_LTO)
	  include(CheckIPOSupported)
	  check_ipo_supported(RESULT supported OUTPUT error)
	  
	  if (supported)
	      message(STATUS "LTO supported, enabling")
	      set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
	  else()
	      message(WARNING "LTO not supported: <${error}>")
	  endif()
endif()
```

then just pass `-DYUZU_LTO` as cmake option. In practice, however, there'll be no practical difference from passing `-DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON`, perhaps aside from being able to have LTO on by default.

> it's possible but most linux users compile yuzu locally

Because yuzu's official Linux packaging is bad enough not to use it, it does not mean it needs to get worse (just stop packaging entirely if you officially give up on it instead of leaving it to rot). On contrary, it needs to get *better*.

**Comment by Tatsh** [comment]
> ```cmake
> YUZU_LTO
> ```

I'm looking for a flag like that custom-made to the project so that I know it is supported unless otherwise noted. LTO could potentially lead to issues that wouldn't be there without it. It may cause unwanted bug reports if it's not supported officially.

**Comment by merryhime** [comment]
Is `/Gr` safe? I do not know how it changes ABI, and dynarmic assumes default x64 ABI.

**Comment by bunnei** [comment]
Untagging because this is causing most mainline and EA builds to fail. ADO changed something recently, we now are failing 4/5 times, causing mainline/EA to not actually be built for days.

Can we break up the changes here and merge the ones that will work with the build pipeline?

**Comment by Tachi107** [comment]
On Linux / GCC you might consider bumping the minimum [psABI](https://gitlab.com/x86-psABIs/x86-64-ABI/-/wikis/uploads/01de35b2c8adc7545de52604cc45d942/x86-64-psABI-2021-05-20.pdf#page=16) instead of explicitly selecting a specific instruction set, with `-march=x86-64-v2`

**Comment by liamwhite** [comment]
Superseded by #9442

**Pull request closed without merging**
