### PR TITLE
Changed UNIMPLEMENTED_MSG -> LOG_CRITICAL for missing services

### PR DESCRIPTION
**Pull request by ogniK5377**
Easier debugging for canary logs

### CODE REVIEW

**Comment by lioncash** [comment]
It would be a better option to update the ignore assertions PR to just change the unimplemented macros to log as well. Unimplemented services should undeniably assert in master, not continue onwards.

**Comment by ogniK5377** [comment]
With a previous PR, i fixed all uninitalized reads, we wouldn’t even have to prevent execution. We could still have assertion messages to show up @lioncash

**Comment by lioncash** [comment]
I don't understand what you're trying to tell me, or why that's relevant. If a service is unimplemented that should be a flat stop no matter what in master. If we're going to impact master, just so canary can hackily continue, then no, I'm totally against this.

**Comment by FernandoS27** [comment]
@lioncash I made a PR that did but you were deeply against it.

**Comment by lioncash** [comment]
As far as I can remember, I was against it being merged into master. I was fine with it being canary tagged though.

**Pull request closed without merging**
