### PR TITLE
Implement Pull #3333 from citra: citra_qt: Pause emulation on CoreError

### PR DESCRIPTION
**Pull request by N00byKing**
Not too much to see.

### CODE REVIEW

**Comment by N00byKing** [comment]
withdrawing pull i fucked something up

**Comment by N00byKing** [comment]
unfucked it

**Comment by Jhon591** [comment]
This will cause spacegameNX nso to freeze at startup and cannot get pass the title screen
https://github.com/Jhon591/yuzu/commit/317f299eb60791fbf582942fa73d770b87c8fd29

So I reverted it.

**Comment by N00byKing** [comment]
Probably means that spacegame is throwing errors causing yuzu to stop. This commit causes yuzu to stop emulation when a core reports an error

**Pull request merged**
