### PR TITLE
yuzu: Add modifiers for keyboard

### LINKED ISSUE #7759: Add the ability to invert the control stick modifier key.
This is a feature request to basically mimic the "!" (or "NOT") logic function that you can apply to keys within the Dolphin emulator. For the context of the modifier key, the idea is that you can invert the logic of the modifier key so that instead of decreasing the stick's position to a percentage, it will instead increase the stick's position to a percentage.
This would allow players who prefer walking to be the default movement when using a keyboard, and requiring the pressing down or toggle of the modifier key to start running (rather than running by default).

Here's an image below regarding how this is implemented within Dolphin. Normally to set this up within Dolphin, you have the range of each control stick direction decreased to a value under 100 (e.g. 80), and have the modifier key's value set to 200 (i.e. doubling the range from 80 to 160).
image

Thank you.

### PR DESCRIPTION
**Pull request by german77**
Somehow this wasn't added on kraken. Add the button modifiers to invert and toggle the input on keyboard

Closes #7759

### CODE REVIEW

**Review by bunnei — APPROVED** [review]

**Comment by pianoboy8** [comment]
Testing this out, It's a bit hard to figure out if this is working as it's supposed to. Mainly the best way to test if this works/can replicate what the original #7759 request is if there was an additional range feature for left/right sticks and if the modifier itself could go past a value of 100.

For reference, for the intended mechanic to work (walk when pressing arrow keys, run when pressing arrow keys + modifier key), the arrow key/control stick should have a range value of 50-75, and the modifier key should be inverted and set to a value of 200. This would then make it so when holding down the modifier key, you would have a range value of 100-150.

**Comment by pianoboy8** [comment]
@german77 by any chance are you planning to look into implementing the above?

**Comment by german77** [comment]
I did implement just that on this PR. Let me make a short demostration of what you are trying to do. Unless I'm understanding all wrong

**Comment by pianoboy8** [comment]
Sure thing. Maybe I missed a feature inside yuzu to make this change or something.

**Comment by german77** [comment]
My bad. You are correct. The button is not working correctly. Give me a few minutes to do a proper fix

**Pull request merged**
