### PR TITLE
externals: Update dynarmic.

### PR DESCRIPTION
**Pull request by degasus**
The new version supports fastmem on a64.

### CODE REVIEW

**Comment by bunnei** [comment]
Untagged until we resolve cmake issue: https://gist.github.com/bunnei/652c863c1bccaed36e85647027c2993b

**Review by bunnei — APPROVED** [review]

**Comment by bunnei** [comment]
Tested locally, seems fine. Probably just build pipeline being weird with submodules.

**Comment by v1993** [comment]
Does this PR alone make yuzu utilize fastmem? Or are further additions required to get fastmem working? Asking since you mention in few places that you have done testing and noticed 15% performance increase.

**Comment by degasus** [comment]
It is only the dynarmic part, yuzu does not support it so far.
And it is only for 64 bit games, 32 but games have been supported in dynarmic for a long time already (also no yuzu support)

**Pull request merged**
