### PR TITLE
Enable compiler optimizations and enforce x86-64-v2 on GCC/Clang

### PR DESCRIPTION
**Pull request by goldenx86**
Had to disable LTO on Linux, seems to cause issues with Qt. In its place, march=x86-64-v2 is being used, enforcing up to SSE4.2.

### CODE REVIEW

**Comment by gidoly** [comment]
description: enables link time compiler optimization

**Comment by v1993** [comment]
Somewhat overlaps with #7497?

**Comment by goldenx86** [comment]
Yeah this is a clear overlap of Blink's PR. Using it to test how the build bots behave.

**Comment by Tachi107** [comment]
I've enabled LTO and SSE4.2 optimizations in [Debian's downstream packaging](https://salsa.debian.org/debian/yuzu/-/blob/a307cf98fc589da3d81dcc43008ff7d9b279a6b8/debian/rules), and while the package isn't yet in Debian's archive (it's still waiting for a peer review) I haven't personally observed any issues.

**Comment by goldenx86** [comment]
Heh, AVX and x86-64-v2 is next.

**Comment by piplup55** [comment]
breaks ui and has longer boot times with errors in the console on linux
image
image
image

**Comment by v1993** [comment]
Are you using clang? If so, this is a known issue that neither Qt nor Clang devs are interested in fixing...

**Comment by piplup55** [comment]
> Are you using clang? If so, this is a known issue that neither Qt nor Clang devs are interested in fixing...

this was using the appimage it gave me from patron

**Comment by Tachi107** [comment]
Why was LTO disabled for GCC too?

**Comment by Tatsh** [comment]
> Why was LTO disabled for GCC too?

Actually I'm getting this error with LTO+GCC:

```
FAILED: bin/yuzu-room
: && /usr/sbin/x86_64-pc-linux-gnu-g++ -O2 -ggdb -march=native \
-mtune=native -pipe -ftree-vectorize -flto=auto -fno-fat-lto-objects -Wl,-O1 -Wl,--as-needed    \
-fuse-ld=lld src/dedicated_room/CMakeFiles/yuzu-room.dir/yuzu_room.cpp.o -o \
 bin/yuzu-room  src/common/libcommon.a  src/network/libnetwork.a  src/web_service/libweb_service.a  externals/mbedtls/library/libmbedtls.a  externals/mbedtls/library/libmbedcrypto.a  -lrt  src/network/libnetwork.a  src/web_service/libweb_service.a  /usr/lib64/libenet.so  src/common/libcommon.a  /usr/lib64/libboost_context.so.1.80.0  /usr/lib64/libfmt.so.9.1.0  /usr/lib64/liblz4.so.1.9.4  /usr/lib64/libzstd.so  \
 /usr/lib64/libssl.so  /usr/lib64/libcrypto.so  externals/mbedtls/library/libmbedx509.a  externals/mbedtls/library/libmbedcrypto.a && :
ld.lld: error: undefined symbol: main
```

**Review by bunnei — APPROVED** [review]

**Pull request merged**
