### PR TITLE
Initial ARM64 support

### PR DESCRIPTION
**Pull request by liamwhite**
Allows building and running yuzu with 32-bit titles on arm64 Linux. Tested and working on Asahi Linux with lavapipe for Vulkan support, yuzu built with the following:
```
export VCPKG_FORCE_SYSTEM_BINARIES=1
cmake .. -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DYUZU_USE_BUNDLED_VCPKG=ON -DYUZU_TESTS=OFF
```

Support for 64-bit titles (i.e., most of them) and support for performance-enhancing features like fastmem is awaiting further changes from Dynarmic at the moment.

### CODE REVIEW

**Comment by goldenx86** [comment]
If someone from Apple reads this, provide a damn Vulkan driver.

**Comment by kotori2** [comment]
> 32-bit titles on arm64 Linux

Hi, thanks for your work. I'm new to NS emulator. Is that means lots of games on NS are ARM32 only and that's the reason why we need Dynarmic on ARM64?
Also I got some compilation errors on ARM64 macOS, especially from `xbyak` ~~and some C++ 20 features that Apple Clang lack of~~. Does `xbyak` currently supports ARM system? 
> a JIT assembler for x86(IA-32)/x64(AMD64, x86-64) MMX/SSE/SSE2/SSE3/SSSE3/SSE4/FPU/AVX/AVX2/AVX-512 by C++ header

**Comment by liamwhite** [comment]
@kotori2 
> Is that means lots of games on NS are ARM32 only

Most games on the Nintendo Switch are 64-bit. Only a small selection (consisting mostly of Wii and Wii U ports) are 32-bit.

> Also I got some compilation errors on ARM64 macOS, especially from xbyak and some C++ 20 features that Apple Clang lack of.

Compilation with Apple Clang is not supported at this time due to outdated standards support. I would recommend installing a compiler from Homebrew or MacPorts.

> Does xbyak currently supports ARM system?

No. I have disabled compilation of xbyak in this pull request. If it is not being properly disabled, you should provide more information.

**Comment by kotori2** [comment]
@liamwhite 
> Compilation with Apple Clang is not supported at this time due to outdated standards support. I would recommend installing a compiler from Homebrew or MacPorts.

Yea I know. But I don't think installing gcc on macOS is a thing. The GNU suite will conflict with the Apple one, such as `GNU ar`. I was trying to use [range-v3](https://github.com/ericniebler/range-v3) and [jthread](https://github.com/josuttis/jthread) and they works. But [I don't think they might accept a PR for this before 2026](https://github.com/yuzu-emu/yuzu/pull/8113#issuecomment-1126984164).

> No. I have disabled compilation of xbyak in this pull request.

Gonna try later to see if I got any chance to get it running on ARM64 macOS. Thanks again.

**Review by bunnei — APPROVED** [review]

**Pull request merged**
