### PR TITLE
Update README.md: add information about supported Windows versions

### PR DESCRIPTION
**Pull request by SHOJI122**
Add information about supported Windows versions.

### CODE REVIEW

**Comment by piplup55** [comment]
technically only windows 10 1803 is supported for fastmem

**Comment by Norstyrm** [comment]
Also if you don't consider fastmem, Windows 7 is still _supported_ afaik, no?

**Comment by piplup55** [comment]
> Also if you don't consider fastmem, Windows 7 is still _supported_ afaik, no?

technically yes but you would have some issues
image

**Comment by SHOJI122** [comment]
Thank you for telling me about the Fastmem technology. I didn't know that, and this information would be help me much about why >Windows 10 v1803 is needed. I have added it in the PR.

**Review by piplup55 — COMMENTED** [review]
fastmem might get disabled by default if it can't assign 4gb in windows

**Comment by SHOJI122** [comment]
> fastmem might get disabled by default if it can't assign 4gb in windows, custom builds shouldn't be mentioned/discussed in the readme imo other then that it looks fine

Thanks for the suggestion! I didn't know that there are cases that Fastmem would get disabled. I have further optimised the patch.

**Comment by FearlessTobi** [comment]
Just a suggestion, but maybe we should put all of this information on the hardware requirements wiki page instead in order to keep our Readme clean?

**Comment by SHOJI122** [comment]
> Just a suggestion, but maybe we should put all of this information on the hardware requirements wiki page instead in order to keep our Readme clean?

I agree. I firstly read wiki on the website. However, when I clicked "edit this page" I came here and found that I have no permission to edit the wiki page. :(

**Pull request closed without merging**
