### PR TITLE
[DO NOT MERGE] NSP and BKTR Conflict Fix for Canary

### PR DESCRIPTION
**Pull request by DarkLordZach**
This includes all of BKTR (to cd9e...) and NSP (to a8b9...) along with fix for their conflicts.

### CODE REVIEW

**Comment by bunnei** [comment]
@DarkLordZach please rebase

**Comment by DarkLordZach** [comment]
Merge is a temp fix, will actually rebase when I can

**Comment by bunnei** [comment]
rebaseeeee

**Comment by bunnei** [comment]
@DarkLordZach needs a rebase

**Comment by DarkLordZach** [comment]
Closed as no longer necessary because NSP #1178 has merged.

**Pull request closed without merging**
