### PR TITLE
externals: use openssl from vcpkg

### PR DESCRIPTION
**Pull request by abouvier**
Supersede https://github.com/yuzu-emu/yuzu/pull/9844.

### CODE REVIEW

**Review by liamwhite — APPROVED** [review]

**Comment by liamwhite** [comment]
Azure DevOps is comical and runs out of disk space when compiling with this PR merged.

**Comment by abouvier** [comment]
Where is this Azure thing? It's not the same thing that the GitHub checks below?

**Comment by liamwhite** [comment]
Azure DevOps is the CI infrastructure used for Mainline and Patreon builds. I have asked internally if we can move off of it because of issues like this.

**Comment by abouvier** [comment]
You managed to fix the Azure bug? :p

**Comment by liamwhite** [comment]
Disabling LTO project-wide caused the VM to not need so much storage.

**Pull request merged**
