### PR TITLE
TextureCache: Eliminate format deduction as full depth conversion has been supported.

### PR DESCRIPTION
**Pull request by FernandoS27**
This fixes the remaining Pokemon Brilliant Diamond LSD effects.

### CODE REVIEW

**Comment by lat9nq** [comment]
Causes Splatoon 2 to crash when using Vulkan by trying to enter player customization (from Inkopolis Square, Press X -> Options -> Other -> Player settings).

**Comment by Oschowa** [comment]
This PR, specifically commit 779f4ac72d2ea2788c2106c8d2d1ec0e01b77b81, causes a massive performance drop for me on the title screen of `Tokyo Mirage Sessions #FE` with the OpenGL renderer on radeonsi. From solid 30 fps at 3x internal resolution to sub 1 fps. This consequently also affects all mainline builds starting with build number 820. The AMD proprietary OpenGL driver and Zink seem unaffected by this regression, but they have other issues unrelated to this PR. My GPU is a 6700XT. If you think this is a driver bug i can take this over to the Mesa gitlab, let me know if i can provide more info.

**Comment by FernandoS27** [comment]
> This PR, specifically commit [779f4ac](https://github.com/yuzu-emu/yuzu/commit/779f4ac72d2ea2788c2106c8d2d1ec0e01b77b81), causes a massive performance drop for me on the title screen of `Tokyo Mirage Sessions #FE` with the OpenGL renderer on radeonsi. From solid 30 fps at 3x internal resolution to sub 1 fps. This consequently also affects all mainline builds starting with build number 820. The AMD proprietary OpenGL driver and Zink seem unaffected by this regression, but they have other issues unrelated to this PR. My GPU is a 6700XT. If you think this is a driver bug i can take this over to the Mesa gitlab, let me know if i can provide more info.

I'm aware and looking at it.

**Comment by FernandoS27** [comment]
> This PR, specifically commit [779f4ac](https://github.com/yuzu-emu/yuzu/commit/779f4ac72d2ea2788c2106c8d2d1ec0e01b77b81), causes a massive performance drop for me on the title screen of `Tokyo Mirage Sessions #FE` with the OpenGL renderer on radeonsi. From solid 30 fps at 3x internal resolution to sub 1 fps. This consequently also affects all mainline builds starting with build number 820. The AMD proprietary OpenGL driver and Zink seem unaffected by this regression, but they have other issues unrelated to this PR. My GPU is a 6700XT. If you think this is a driver bug i can take this over to the Mesa gitlab, let me know if i can provide more info.

Should now be fixed a long some other issues.

**Comment by Oschowa** [comment]
Can confirm perf is fine again, thanks!

**Review by bunnei — APPROVED** [review]

**Pull request merged**
