### PR TITLE
video_core: rewrite presentation for layer composition

### PR DESCRIPTION
**Pull request by liamwhite**
This is all of the presentation changes extracted from #12756, except for the alpha blending changes which are a bit rough around the edges and still need further RE work to figure out. This requires extensive testing in both Vulkan and OpenGL to ensure that all upscaling and antialiasing modes are still working, and that framerate mods are not affected. 

It is unclear how the introduction of the hardware composer abstraction will interact with #12730. Games rely on am to create their layers, and am only creates one display layer, so we may need to look at the maximum value of the swap interval for all layers in this case.

### CODE REVIEW

**Comment by liamwhite** [comment]
To maintain compatibility with the changes proposed in 12730, I think what we can do is:
- When receiving a swap interval of 5 or above, treat it as a swap interval of 1
- Change the speed limit to that value

**Comment by liamwhite** [comment]
(cc @saad-script for thoughts)

**Comment by saad-script** [comment]
setting negative swap intervals seem to work as expected, but setting a swap interval of 0 does not unlock the framerate above 60 in this PR.

before:
1 => 60fps
0 => 120fps
-1 => 240 fps

after PR:
1 => 60fps
0 => 60fps
-1 => 240fps

**Comment by saad-script** [comment]
> To maintain compatibility with the changes proposed in 12730, I think what we can do is:
> 
> * When receiving a swap interval of 5 or above, treat it as a swap interval of 1
> * Change the speed limit to that value

Sounds good to me

**Comment by liamwhite** [comment]
@saad-script okay, can you recheck now?

**Comment by saad-script** [comment]
> @saad-script okay, can you recheck now?

swap intervals of <= 0 are doing the opposite:
1 => 60fps
0 => 30fps
-1 => 15fps

I think the reviews i left above should solve this issue

**Comment by saad-script** [comment]
Framerate mods all seem to work now!
Tested using both <= 0 swap intervals and also swap interval >= 5

Also, normal swap interval values of 1,2,3 all work as expected

**Review by FernandoS27 — APPROVED** [review]

**Pull request merged**
