### PR TITLE
jit: use code memory handles correctly

### PR DESCRIPTION
**Pull request by liamwhite**
This allows the N64 games to work with NCE
sm64

### CODE REVIEW

**Comment by SamSIM-pro** [comment]
Does this PR extend to other Nintendo consoles like the Wii? JIT-based games being compatible with NCE, I mean.

**Comment by FernandoS27** [comment]
> Does this PR extend to other Nintendo consoles like the Wii? JIT-based games being compatible with NCE, I mean.

Nope, Nintendo emulates Wii games differently this only affects games that use the Switch's JIT service which is mostly just N64 games.

**Comment by SamSIM-pro** [comment]
> > Does this PR extend to other Nintendo consoles like the Wii? JIT-based games being compatible with NCE, I mean.
> 
> Nope, Nintendo emulates Wii games differently this only affects games that use the Switch's JIT service which is mostly just N64 games.

Ok, thanks for clarifying.

**Comment by Venvvs** [comment]
Could this fix the issue with Super Mario All Stars?
I played it on yuzu 150 to like 162 fine and now it freezes after choosing a game.
I know people say it's a miracles it even worked but idk.

Going back to those versions however it didn't work anymore? Weird.

**Comment by brujo5** [comment]
When running an N64 game such as Paper Mario and doing a save state (by pressing the - button) the game crashes

**Comment by RaduNastase** [comment]
Could this positively affect (meaning playable via NCE) other JIT only games like Espgaluda 2, Mushihimesama and Dodonpachi Ressurection?

**Comment by liamwhite** [comment]
no

**Comment by FernandoS27** [comment]
> Could this positively affect (meaning playable via NCE) other JIT only games like Espgaluda 2, Mushihimesama and Dodonpachi Ressurection?

Guys it has nothing to do with the emulation JIT that we use.

The Nintendo Switch has a JIT service for Nintendo propietary emulators that they use. We just fixed it to work with it.

**Review by german77 — APPROVED** [review]

**Pull request merged**
