### PR TITLE
audio_core: Workaround for audio pops and clicks

### PR DESCRIPTION
**Pull request by v1993**
This is most evident on Linux, but happens everywhere. See issue #7144 for more details and original patch by @vasishath .

This hides an issue in yuzu and should NOT be merged into master. Just a temporary fix to make life less miserable.

### CODE REVIEW

**Comment by v1993** [comment]
It's confirmed to work, so please tag this mainline-merge and do-not-merge.

**Review by FernandoS27 — APPROVED** [review]

**Comment by FernandoS27** [comment]
We are avoiding mainline-merge since it causes issues. Let me see this PR well though.

**Comment by vasishath** [comment]
> This is most evident on Linux, but happens everywhere. See issue #7144 for more details and original patch by @vasishath .
> 
> This hides an issue in yuzu and should NOT be merged into master. Just a temporary fix to make life less miserable.

Thanks a lot!

**Comment by gidoly** [comment]
appears to break snow stamping sound effect on xenoblade 2

**Comment by v1993** [comment]
I wonder what does that game do to do its snow audio effect. Schedule gaps in audio? Either way, proper fix to underlying issue shouldn't cause such problems.

**Comment by FernandoS27** [comment]
> I wonder what does that game do to do its snow audio effect. Schedule gaps in audio? Either way, proper fix to underlying issue shouldn't cause such problems.

I agree, this is just a correction for a wrong calculation of late time.

**Comment by gidoly** [comment]
Mainline 831 merged this pr however seems visual novel
Collar x malice got audio lagging issue with it.
Ik it is valid fix but just to track issues  uncovered

**Comment by MetalSpork** [comment]
> Mainline 831 merged this pr however seems visual novel Collar x malice got audio lagging issue with it according to user on discord Ik it is valid fix but just to track issues uncovered

That would be me. I compiled it on my end with this PR reverted, and the audio crackling I was experiencing went away. I'm on Windows 10.

**Comment by MetalSpork** [comment]
> We are avoiding mainline-merge since it causes issues. Let me see this PR well though.

@FernandoS27 It seems mainline 831 actually did merge this, which I'm guessing was in error?

> Mainline 831 merged this pr however seems visual novel Collar x malice got audio lagging issue with it according to user on 

That would be me. I compiled it on my end with this PR reverted, and the audio crackling I was experiencing went away. I'm on Windows 10.

**Comment by v1993** [comment]
> It seems mainline 831 actually did merge this, which I'm guessing was in error?

No, it is not an error. `do-not-merge` means not merging into master (since this is a hack at its core). `mainline-merge` merges it into every mainline build, which is intended.

**Comment by MetalSpork** [comment]
> > It seems mainline 831 actually did merge this, which I'm guessing was in error?
> 
> No, it is not an error. `do-not-merge` means not merging into master (since this is a hack at its core). `mainline-merge` merges it into every mainline build, which is intended.

I see. Question, does Linux experience the audio crackling that results from this PR? I don't know a lot about Linux, but I do know that the audio systems that govern Windows and Linux couldn't be more different.

Could what this PR does be made into an option that can be toggled, or is that just not feasible?

As an aside, as a Windows user, the sdl2 audio backend has never worked for me. I'm not sure if that's the case for all Windows users or not, though. Makes me wonder if the side effects of this PR would still be an issue if I could use the sdl2 backend.

**Comment by v1993** [comment]
I'd expect this crackling to be present in Linux as well. This isn't really related to audio systems OSes use.

As for making this into an option - this, as I said, is a temporary hack. Once the proper fix will be available (hopefully soon), this PR will be dropped entirely.

**Comment by ImportTaste** [comment]
I wasn't going to harp on this, but it's been a bit. Why is this seen as an improvement? It seems like the problem's cure is worse than the problem itself.

**Comment by behunin** [comment]
It's just a work around while a real solution is being worked on.

**Comment by ImportTaste** [comment]
Would it be at all possible to make this an option that can be toggled? It doesn't seem like there's a real solution in sight, and I still think that the problem this PR causes is worse than the problem it fixes.

I've been compiling manually with this PR excluded in the meantime, but it's been three months now.

**Comment by v1993** [comment]
Yes, it is entirely possible to make it into a toggle, but I personally don't have time for this now. If other devs are willing to make it into a toggle - that wouldn't have any objections from me.

The truth is - I've never intended for this to stay in this state for so long, expecting this to get fixed in a month or maybe two with leads to underlying issue being somewhat figured out.

**Comment by Timmy5942** [comment]
I think we need an audio boost?, Even I find it hard to hear it at tv 50% sound

maybe 200% booster?

**Comment by ImportTaste** [comment]
> Yes, it is entirely possible to make it into a toggle, but I personally don't have time for this now. If other devs are willing to make it into a toggle - that wouldn't have any objections from me.
> 
> The truth is - I've never intended for this to stay in this state for so long, expecting this to get fixed in a month or maybe two with leads to underlying issue being somewhat figured out.

It's been more than a couple months now – how many of the other devs are even aware of the drawbacks of this PR? Maybe that's why it's not being touched upon.

**Comment by german77** [comment]
This PR just hides a problem. The issue is not easy to fix at all. It basically needs a scheduler that it's more accurate.

**Comment by ImportTaste** [comment]
> This PR just hides a problem. The issue is not easy to fix at all. It basically needs a scheduler that it's more accurate.

I'm more concerned that it causes a problem. Seriously, the audio crackling it causes is so annoying. Considering it's supposed to fix audio pops and clicks in the first place, it seems like taking one step forward and two steps back.

**Comment by v1993** [comment]
I've disabled this PR's effect on Windows for now based on feedback.

**Comment by liamwhite** [comment]
Closing as audio was completely replaced

**Pull request closed without merging**
