### PR TITLE
 general: properly support multiple memory instances 

### PR DESCRIPTION
**Pull request by liamwhite**
This changeset aims to allow multiple memory instances to exist and interact with server sessions. Needs extensive testing because it touches the resource limits and modifies how objects are acquired from the handle table, which might cause issues.

### CODE REVIEW

**Review by kkxiegouquan — COMMENTED** [review]
I hope Ann can do this

**Review by FernandoS27 — APPROVED** [review]

**Comment by brujo5** [comment]
@liamwhite 
In build v170 I am experiencing that my phone heats up quickly compared to v166 or v168 just to give an example.  Previously the battery temperature did not exceed 40c but in v170 it reached 44c playing the same games.  I'm going to stay on v168 for the moment since the increase in heat is annoying

**Comment by liamwhite** [comment]
this commit was first seen on android 169 so I doubt it

**Comment by brujo5** [comment]
I also tried this pr that's why I commented here

**Pull request merged**
