### PR TITLE
video_core: Use contains when possible

### PR DESCRIPTION
**Pull request by ogniK5377**

### CODE REVIEW

**Comment by lioncash** [comment]
clang/libc++ currently don't implement this yet (see the compiler [support](https://en.cppreference.com/w/cpp/compiler_support) page)

**Comment by ogniK5377** [comment]
Will keep it open until support is added

**Comment by v1993** [comment]
Looks like it's supported now.

**Comment by ameerj** [comment]
These files no longer exist as of the shader decompiler rewrite. Do you want to keep this open @ogniK5377 ?

**Comment by ameerj** [comment]
Closing since the files being changed no longer exist in the project.

**Pull request closed without merging**
