### PR TITLE
CMakeLists.txt

### PR DESCRIPTION
**Pull request by KDZ12**

### CODE REVIEW

**Comment by KDZ12** [comment]
esboco 1

**Comment by KDZ12** [comment]
esboco 2

**Comment by KDZ12** [comment]
esboco 3

**Comment by KDZ12** [comment]
esboco 4

**Comment by KDZ12** [comment]
https://ci.appveyor.com/project/joaozin23/yuzu/build/1.0.3/job/5k34bnci8yo1gf34

**Comment by Subv** [comment]
This setting should only be enabled for MSVC on Windows, not for anything else

**Comment by MerryMage** [comment]
Closeable.

**Pull request closed without merging**
