### PR TITLE
settings_ui: Disable async shaders by a simple comment addition

### PR DESCRIPTION
**Pull request by Moonlacer**
Disables async shaders in both global and custom configuration by making anything regarding them a comment, so as not to break anything being worked on (I hope)

### CODE REVIEW

**Comment by Moonlacer** [comment]
Clang is annoying, but I won't be able to try to fix it much until I get back from my trip

**Comment by yzct12345** [comment]
What's wrong with async shaders?

**Comment by Moonlacer** [comment]
> What's wrong with async shaders?

It breaks many games in yuzu, atm

**Comment by yzct12345** [comment]
> many

That means some games don't get broken. For those games you will be taking away the freedom of the user to use this feature. If async shaders are breaking all of your games you can simply uncheck the checkbox on your computer instead of on everyone's computers.

**Comment by Moonlacer** [comment]
> > many
> 
> That means some games don't get broken. For those games you will be taking away the freedom of the user to use this feature. If async shaders are breaking all of your games you can simply uncheck the checkbox on your computer instead of on everyone's computers.

For the games it doesn't break, there is no benefit to them being enabled

**Comment by v1993** [comment]
I'm curious if this is indeed true. Any word from devs?

**Comment by Moonlacer** [comment]
> I'm curious if this is indeed true. Any word from devs?

Maybe @goldenx86 could give you a clearer answer on this, this is just what I have tested and seen from being in the Discord server

**Comment by Moonlacer** [comment]
> I'm curious if this is indeed true. Any word from devs?

Also @v1993, if you are in the Discord, you should be able to look at this for a bit more info: https://discord.com/channels/398318088170242053/668532415257509958/863215731172048927

**Comment by v1993** [comment]
That discord message was related to bug in Hades before its merge. It was ultimately fixed before getting into master.

**Comment by Moonlacer** [comment]
I think I may just open a different PR adding onto #6817 that shows that async may break things

**Pull request closed without merging**
