### PR TITLE
gl_shader_decompiler: Fix clang build issues

### PR DESCRIPTION
**Pull request by ReinUsesLisp**
This commit tries to address #2863

### CODE REVIEW

**Comment by jbeich** [comment]
Still fails with Clang:
```c++
src/video_core/renderer_opengl/gl_shader_decompiler.cpp:754:22: error: reference to local binding 'image' declared in enclosing function 'OpenGL::GLShader::(anonymous namespace)::GLSLDecompiler::DeclareImages'
                if (!image.IsSizeKnown()) {
                     ^
src/video_core/renderer_opengl/gl_shader_decompiler.cpp:752:35: note: 'image' declared here
        for (const auto& [offset, image] : images) {
                                  ^
src/video_core/renderer_opengl/gl_shader_decompiler.cpp:757:25: error: reference to local binding 'image' declared in enclosing function 'OpenGL::GLShader::(anonymous namespace)::GLSLDecompiler::DeclareImages'
                switch (image.GetSize()) {
                        ^
src/video_core/renderer_opengl/gl_shader_decompiler.cpp:752:35: note: 'image' declared here
        for (const auto& [offset, image] : images) {
                                  ^
src/video_core/renderer_opengl/gl_shader_decompiler.cpp:764:56: error: reference to local binding 'image' declared in enclosing function 'OpenGL::GLShader::(anonymous namespace)::GLSLDecompiler::DeclareImages'
                                      static_cast<u32>(image.GetSize()));
                                                       ^
src/video_core/renderer_opengl/gl_shader_decompiler.cpp:752:35: note: 'image' declared here
        for (const auto& [offset, image] : images) {
                                  ^
3 errors generated.
```

**Comment by ReinUsesLisp** [comment]
Thanks for re-testing. I'll fix the invalid code validating clang.

**Comment by jbeich** [comment]
FWIW, downstream I've used [copy hack](https://svnweb.freebsd.org/ports/head/emulators/yuzu/files/patch-clang?revision=512453&view=markup&pathrev=512453) to get it to build.

**Comment by ReinUsesLisp** [comment]
If that was the only thing missing, it should be fixed now. I moved it to a function.

**Comment by jbeich** [comment]
Thanks. `master` builds fine with this PR on top.

**Pull request merged**
