### PR TITLE
system_archive: Fix Korean and Chinese fonts

### PR DESCRIPTION
**Pull request by FearlessTobi**
Fixes Korean fonts when using Open-source system archives.

Fixes https://github.com/yuzu-emu/yuzu/issues/3101.

### CODE REVIEW

**Comment by DarkLordZach** [comment]
Please state the impact on binary size resulting from this PR.

**Comment by FearlessTobi** [comment]
Impact on the binary size on my system is 10.1MB (~2MB Korean, ~8MB Chinese).

**Comment by bunnei** [comment]
@FearlessTobi ping again here -- I believe you were going to use clang format ignore tags to fix the CI errors?

**Comment by FearlessTobi** [comment]
Updated.

**Pull request merged**
