### PR TITLE
host_shaders: ASTC compute shader optimizations

### PR DESCRIPTION
**Pull request by ameerj**
### Changes
This change introduces some optimizations for the ASTC decoder. Broadly summarizing there are 3 main changes:
- Pack `EncodingData` into a single uint, rather than 4 separate uints
- Reuse of local memory, rather than having many large LMEM arrays
- Backing out of decode phases early where possible (see `ResultEmplaceBack`)

I also experimented with:
- Specializing the shader for the specific block dimensions (4x4, 8x6, etc.)
- Specializing for the dual plane mode
- Using indirect dispatches for non error or void extent blocks.

Early testing did not seem to produce any noticeable improvement in performance. These may be worth revisiting with the latest changes.

### Testing
Here are some of the torture tests used for benchmarking the decoder:
[astc_unit_tests.zip](https://github.com/yuzu-emu/yuzu/files/12156554/astc_unit_tests.zip)
This invokes the decoder once per frame, unlock the framerate to stress the ASTC decode path.
Pressing A/B changes the ASTC block size.

For Vulkan, the bottleneck seems to be the presentation synchronization. 
`Asynchronous presentation` should be enabled to alleviate much of this bottleneck.

Performance numbers on my RTX 3070, averaged since there is fluctuation.

1k | Before | After
-- | -- | --
Vulkan | 1500 - 1900 | 2200 - 2380
OpenGL | 165 - 350 |  2000 - 2520

2k | Before | After
-- | -- | --
Vulkan | 620 - 1100  | 1200 - 1400
OpenGL | 48 - 100 |  770 - 980

(fun fact: the work here is what uncovered the Nvidia OGL driver Local Memory bug addressed in #10916 )

### CODE REVIEW

**Comment by gidoly** [comment]
Nice! X10 is huge.

@GPUCode  you might able to use this homebrew for bc7 compression benchmark?.

**Comment by gidoly** [comment]
here is test result on 4090.

1k homebrew

ea: 95fps
yuzu_su1QNESNoc

pr: 945fps
astc_opt_hdze5KCNww

2k homebrew

ea: 27fps
yuzu_3hfdtvFbPk

pr:  400fps

astc_opt_amk7v0j4UW

**Comment by goldenx86** [comment]
RDNA2 Windows is negatively affected:
image

**Comment by Morph1984** [comment]
Negatively affects my 980 ti, but further testing will be done tomorrow:
EA
image
PR
image

**Comment by Moonlacer** [comment]
Vega 56: Regressed visually, but shows massive performance improvement
EA: 
image
PR:
image

**Comment by goldenx86** [comment]
Remember the new UI defaults to CPU decoding.

**Comment by Moonlacer** [comment]
RX 480 4GB:
EA:
image
PR:
image

**Comment by Moonlacer** [comment]
ARC A770 LE:
EA: 
A770 EA
PR: 
A770 ASTC PERF

**Comment by Moonlacer** [comment]
5700 XT:
EA: 
5700 XT EA
PR: 
5700 XT ASTC PERF

**Comment by mr-sihc** [comment]
Artix-dinit(Arch) Linux MESA RADV RX VEGA 64

Vulkan about 10fps improvement (580-600) -> (590-605) (still very variable fps)
and opengl has on both modes 10/11fps

and a little purple square

grafik

OPENGL NORMAL

**Comment by Moonlacer** [comment]
7900 XTX:
EA: 
image
PR: 
image

**Comment by AliciaBurrito** [comment]
Testing on my 5950X, 3090 system using GPU:

EA: 
image

PR:
image

**Comment by ameerj** [comment]
@Moonlacer @goldenx86 please retest AMD with the latest commit

**Comment by german77** [comment]
No graphic issues on a vega 11 with latest commit. 
This pr performance. 34fps OpenGL, 44fps Vulkan.
Mainline 1507. 84fps OpenGL, 78fps Vulkan.

**Comment by gidoly** [comment]
vulkan retest
1k homebrew / 2k homebrew
4x4
pr: 1055fps / 506fps
ea:  933fps / 512fps
5x4
pr: 1125 fps / 589 fps
ea: 958fps / 592fps
5x5
pr: 1162 fps /648 fps
ea: 975fps / 649 fps
6x5
pr: 1184 fps /704 fps
ea: 1000 fps / 707 fps
6x6
pr: 1206 fps / 764 fps
ea: 1020fps / 764 fps
8x5
pr: 1208 fps / 800fps
ea: 1010fps / 800fps
8x6
pr: 1209 fps / 873fps
ea: 1024 fps / 873fps
8x8
pr: 1210fps / 971 fps
ea: 1011fps / 974fps
10x5
pr: 1216 fps / 890 fps
ea: 1032 fps / 890fps
10x6
pr: 1208 fps / 949 fps
ea: 1023 fps / 952 fps
10x8
pr: 1207 fps / 1023fps
ea: 1027 fps / 1027fps
10x10
pr: 1201 fps / 1053fps
ea: 1026 fps / 1051fps
12x10
pr: 1185 fps / 1070fps
ea: 1045 fps / 1070fps
10x6
pr: 1170 fps / 1072 fps
ea: 1038fps / 1075 fps

this is visual studio profile result

devenv_L1VtNHJncA

**Comment by Moonlacer** [comment]
5700 XT (Commit 2):
EA: 
5700 XT EA 2
PR: 
5700 XT ASTC PERF 2

**Comment by Moonlacer** [comment]
7900 XTX (Commit 2):
EA: 
image
PR:
image

**Comment by gidoly** [comment]
heads up Red dot seems correct behavior. verified on console.

**Comment by Adamillo** [comment]
This change does not impact Intel iGPU's that natively support ASTC right?

**Comment by gidoly** [comment]
yes

**Comment by goldenx86** [comment]
The rendering fix seems to murder performance for RDNA2, what use to be 200 FPS at 4x4 is now just 90.
Rendering is solved though, but this is close to the performance of BC3 recompression now for AMD.

**Comment by goldenx86** [comment]
Forgot to mention, force max clocks was always enabled, for both NVIDIA and AMD testing.

**Comment by german77** [comment]
I didn't had force max clocks enabled. I will redo the test in a few hours. Along with gtx1060 testing

**Comment by Moonlacer** [comment]
@ameerj 
>It seems that Vega and RDNA1 are the only GPUs to have performance regressions?

I believe RDNA1, RDNA2, and Vega regressed, but further testing is probably needed
>Just to be sure, was the Vulkan boost mode enabled for testing?

Yes, force max clocks was enabled on all cards
>And is it possible to lock the GPU clocks to a specific frequency when comparing the two builds for consistency?

I believe the closest we can get to consistent/locked clocks would be the force maximum clocks option

**Comment by Morph1984** [comment]
All tests done with static 1304 MHz gpu clocks, astc 1K homebrew, driver 536.67, GTX 980 Ti

master https://github.com/yuzu-emu/yuzu/commit/a1c355051e030d48b24044023c3fb35d2640386b
GL
4x4 77
5x4 85
5x5 99
6x5 107
6x6 118
8x5 120
8x6 131
8x8 152
10x5 132
10x6 145
10x8 165
10x10 178
12x10 187
12x12 190
VK
4x4 86
5x4 92
5x5 103
6x5 110
6x6 120
8x5 120
8x6 132
8x8 152
10x5 133
10x6 144
10x8 165
10x10 177
12x10 184
12x12 188

PR rebased to https://github.com/yuzu-emu/yuzu/commit/a1c355051e030d48b24044023c3fb35d2640386b
GL
4x4 608
5x4 666
5x5 710
6x5 703
6x6 701
8x5 715
8x6 794
8x8 814
10x5 787
10x6 812
10x8 782
10x10 744
12x10 728
12x12 666

VK
4x4 76
5x4 82
5x5 92
6x5 100
6x6 109
8x5 111
8x6 121
8x8 140
10x5 122
10x6 133
10x8 151
10x10 160
12x10 172
12x12 180

**Comment by Morph1984** [comment]
Here were the builds used, for anyone interested
[Release.zip](https://github.com/yuzu-emu/yuzu/files/12178794/Release.zip)

**Comment by Morph1984** [comment]
master GLSL 4x4 GPU usage:
image
master VK 4x4 GPU usage:
image

pr GLSL 4x4 GPU usage:
image
pr VK 4x4 GPU usage:
image

**Comment by goldenx86** [comment]
Running it again shows to be on par with the old build. No idea what caused the regression, but a second run was fine.

**Comment by goldenx86** [comment]
@ameerj kidnaped me and demands I say sorry.
Send help, I'm in...

**Comment by mr-sihc** [comment]
so resting with maximum clocks
vulkan has a little better with about 10 fps higher high from (550-570) to (550-580) fps (vulkan was so wonky it might not be too accurate, but this build had higher highs most of the time)
opengl is still 10-12fps and the only one to have the accurate square

man is opengl slow here

**Comment by Moonlacer** [comment]
RX 480 4GB (Commit 2) (23.7.2):
EA:
image
PR:
image

**Comment by Moonlacer** [comment]
Vega 56 (Commit 2) (23.7.2)
EA: 
image
PR:
image

**Comment by Moonlacer** [comment]
5700 XT (Commit 2) (23.7.2):
VULKAN
EA:
image
PR:
image
OPENGL
EA:
image
PR:
image

**Comment by Moonlacer** [comment]
6750 XT (Commit 2) (23.7.2)
VULKAN
EA:
image
PR:
image
OPENGL
EA:
image
PR:
image

**Comment by Moonlacer** [comment]
A770 LE (Commit 2) (101.4146):
VULKAN
EA:
image
PR:
image
OPENGL
EA: TBD (Couldn't disable VSync on ARC, so yuzu was locked to 144FPS)
PR: TBD (Couldn't disable VSync on ARC, so yuzu was locked to 144FPS)

**Comment by Moonlacer** [comment]
GTX 1050ti (Commit 2) (536.67):
VULKAN
EA: 
image
PR:
image
OPENGL
EA:
image
PR:
image

**Comment by ameerj** [comment]
Ready for another round of testing.
Rebased, and broke up the commits for easier regression tracking

**Comment by Moonlacer** [comment]
RX 7900 XTX (Commit 3) (23.7.2):
VULKAN
EA:
Screenshot 2023-08-02 220319
PR:
Screenshot 2023-08-02 220349
OPENGL
EA:
Screenshot 2023-08-02 220418
PR:
Screenshot 2023-08-02 220434

**Comment by Moonlacer** [comment]
RX 480 4GB (Commit 3) (23.7.2):
VULKAN
EA:
image
PR:
image
OPENGL
EA:
image
PR:
image

**Comment by gidoly** [comment]
vulkan reretest
1k homebrew / 2k homebrew
4x4
pr: 1201fps / 623 fps
ea: 933 fps / 533 fps
5x4
pr: 1286 fps / 694 fps 
ea: 974 fps / 574 fps
5x5
pr: 1317 fps / 743 fps
ea: 983 fps / 620 fps
6x5
pr:  1337 fps / 808 fps
ea:  991 fps / 671 fps
6x6
pr: 1380 fps / 878 fps
ea: 1007 fps / 720 fps
8x5
pr: 1380 fps / 885 fps
ea: 1021 fps / 729 fps
8x6
pr: 1385 fps / 946 fps
ea: 1024 fps / 764 fps
8x8
pr: 1448 fps / 1043 fps
ea: 1039 fps / 827 fps
10x5
pr: 1438 fps / 957 fps
ea: 1035 fps / 772fps
10x6
pr: 1424 fps / 1014 fps
ea: 1030 fps / 803 fps
10x8
pr: 1475 fps / 1095 fps
ea: 1048 fps / 855 fps
10x10
pr: 1473 fps / 1120 fps
ea: 1035 fps / 868 fps
12x10
pr: 1488 fps / 1135 fps
ea: 1046 fps / 885 fps
12x12
pr: 1468 fps / 1153 fps
ea: 1038 fps / 881 fps

performance are drastically improved.

**Comment by Moonlacer** [comment]
RX Vega 56 (Commit 3) (23.7.2):
EA:
image
PR:
image
OPENGL
EA:
image
PR:
image

**Comment by goldenx86** [comment]
image
Good gains compared to earlier results, net win overall.
Strange dip in performance the lower the quality of the texture on NVIDIA, but still, 0.98x is basically nothing.

**Comment by Moonlacer** [comment]
RX 5700 XT (Commit 3) (23.7.2)
VULKAN
EA:
image
PR:
image
OPENGL
EA:
image
PR:
image

**Comment by Moonlacer** [comment]
RX 6750 XT (Commit 3) (23.7.2):
VULKAN
EA:
image
PR:
image
OPENGL
EA:
image
PR:
image

**Comment by ameerj** [comment]
@goldenx86 @gidoly I'd like to see OGL comparison of old build and new build, and OGL vs Vulkan on Nvidia.

**Comment by goldenx86** [comment]
On it.

**Comment by goldenx86** [comment]
image
Here you go. NVIDIA only, no sane person would use OGL with AMD drivers.

**Comment by ameerj** [comment]
My 3070 says otherwise...

1k | vk | ogl
-- | -- | --
4x4 | 1020 | 1365
5x4 | 1130 | 1337
5x5 | 1160 | 1426
6x5 | 1230 | 1555
6x6 | 1280 | 1572
8x5 | 1333 | 1760
8x6 | 1353 | 1768
8x8 | 1469 | 1798
10x5 | 1408 | 1750
10x6 | 1410 | 1759
10x8 | 1433 | 1764
10x10 | 1463 | 1625
12x10 | 1426 | 1562
12x12 | 1425 | 1470

**Comment by gidoly** [comment]
i got similar result with golden vulkan is slightly faster than opengl

**Comment by Moonlacer** [comment]
@ameerj Here are my results with a 1050ti, testing information is at the bottom of the picture
image

**Comment by gurrgur** [comment]
@mr-sihc @ameerj Apparently mesa supports compute shader decoding of ASTC since Version 23.1 (see this [PR](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/19886)).

As suggested I tested with and without forcing IsASTCSupported() in gl_device.cpp to return false.

Heres my specs:

- mesa 23.1.4
- RX6600XT

The results:

## 1. astc_1k (4x4)

### OpenGL (RadeonSI)

| branch | IsASTCSupported() | fps |
| --- | --- | --- |
| master | true (mesa does decoding) | 37  |
| master | false (yuzu does decoding) | 1950 |
| astc-perf-prod | false (yuzu does decoding) | 1743 |

There seems to be a ~20% performance hit using this PR when forcing IsASTCSupported() to return false.

### Vulkan (RADV)

| branch | fps |
| --- | --- |
| master | 956 |
| astc-perf-prod | 1033 |

This PR does not seem to have too much of an effect for Vulkan results. The difference is pretty likely just measurement error.

## 2. astc_2k (4x4)

###  OpenGL (RadeonSI)

| branch | IsASTCSupported() | fps |
| --- | --- | --- |
| master | true (mesa does decoding) | 10  |
| master | false (yuzu does decoding) | 728 |
| astc-perf-prod | false (yuzu does decoding) | 577 |

### Vulkan (RADV)

| branch | fps |
| --- | --- |
| master | 402 |
| astc-perf-prod | 373 |

Here are screenshots for each test run:

[yuzu-test-astc-optim.zip](https://github.com/yuzu-emu/yuzu/files/12260773/yuzu-test-astc-optim.zip)

**Comment by ameerj** [comment]
@gurrgur thanks for testing! Are you able to git-bisect the commits in this PR to identify which commit causes the perf regression?

@liamwhite @lat9nq sounds like Mesa's ASTC "support" needs to be blacklisted.

**Comment by gurrgur** [comment]
@ameerj Sure thing, here are the results for astc_1k:

Starting with

- `git bisect good 096644c01cb8cd30589d5f168fdabaac5aad174a`
- `git bisect bad 8b2db2228186e69ae7e3d908ff963f0645f5d090`

(note: I accidentaly chose the last good a bit older than needed)

| bisect step | commit | fps |
| :---: | --- | :---: |
| 1   | \[3e7cfa403a957f85a77f347879b776b01ba3f6ba\] amd opts | 1795 |
| 2   | \[6fcbcdc152cfa6b33697cc8c2e95b1f37c95ea16\] EncodingData pack | 2350 |
| 3   | \[685a91e4fa0ff495a84941580a5e1829487dfd9e\] minor redundancy cleanup | 2275 |
| 4   | \[0efa4760dae75a68c70c87aa18bf44a55ff969f7\] gl | 1799 |
| **5** | **\[4dcda34648a6392076136992edc3e0fc373846b5\] const, pack result_vector and replicate tables, \[...\]** | **1796** |

git diff result:

```
4dcda34648a6392076136992edc3e0fc373846b5 is the first bad commit
commit 4dcda34648a6392076136992edc3e0fc373846b5
Author: Ameer J <52414509+ameerj@users.noreply.github.com>
Date:   Tue Aug 1 17:22:03 2023 -0400

    const, pack result_vector and replicate tables,
    
    undo amd opts

 src/video_core/host_shaders/astc_decoder.comp | 487 ++++++++++++++------------
 1 file changed, 260 insertions(+), 227 deletions(-)
```

**Comment by gurrgur** [comment]
Testing master against last good does not show a significant difference in perf. Also glsl / spirv seem about equal.

|     | glsl | spirv |
| --- | :---: | :---: |
| **master** | 2360 fps | 2360 fps |
| **685a91e4fa0ff495a84941580a5e1829487dfd9e (last good)** | 2387 fps | 2398fps |

**Comment by lat9nq** [comment]
https://github.com/yuzu-emu/yuzu/pull/11149#issuecomment-1665581666

Yeah I can work on that. In the meantime I ran performance numbers on my ARC A380 using the Mesa drivers. I found that the existing implementation is consistently performing better than the proposed one in this PR on this graphics card/driver.

Screenshot from 2023-08-04 14-02-03

**Comment by ameerj** [comment]
Thanks gurrgur, I'll have to break up that commit some more to narrow down the regression

@lat9nq is the commit that regresses the A380 the same commit gurrgur identified?

**Comment by gidoly** [comment]
@ameerj since you are specialist for compute shader.
Can we get quad texture compute shader optimize for vulkan too?. Lot of switch game utilize quad texture and some games can be slower than open gl due to not having native support. Would be nice if we can optimize out

**Comment by lat9nq** [comment]
https://github.com/yuzu-emu/yuzu/pull/11149#issuecomment-1666264402

Seems like `4dcda34648a6392076136992edc3e0fc373846b5 const, pack result_vector and replicate tables` is causing the regression for me. `minor redundancy cleanup` is roughly 710 fps at 12x12 GL.

**Comment by abiliodasilva** [comment]
AMD RX6400 (Vulkan, Radeon GPU Analyzer)
EA: ~300 FPS
image
image

PR (last commit): ~400 FPS
image
image

**Comment by abiliodasilva** [comment]
Using `uint[]` for the replicate tables and declaring `color_endpoint_data` in `DecompressBlock` instead of globally (also refactoring all the functions where it is used) reduces the usage of VGPRs, scratch memory and instruction cache:
image

Minimal gain around +5~6 FPS on average compared to the last commit of this PR in my RX6400, may be caused by the reduction of VGPRs:
image

File with the changes: [astc_decoder](https://github.com/yuzu-emu/yuzu/files/12269936/astc_decoder.txt)

**Comment by ameerj** [comment]
> Using uint[] for the replicate tables 

Nvidia (at least their OGL driver) uses a full vector register to store an individual uint, so this results in a 4x LMEM usage increase.

But these tables seemed to be a pain point for Mesa as well. I eliminated a branch in the original `Replicate()` function and performance on the drivers I tested seems to be unchanged in the worst case, or see a slight perf bump.

Can Mesa be retested with the latest commits? @lat9nq @gurrgur

**Comment by abiliodasilva** [comment]
> But these tables seemed to be a pain point for Mesa as well. I eliminated a branch in the original `Replicate()` function and use it to compute the replicate value instead of using a LUT, and performance on the drivers I tested seems to be unchanged in the worst case, or see a slight perf bump.

Tested with the replicate function, same performance as before (around 400 FPS in RX6400). Uses way less VGPR and scratch memory according to Radeon GPU Analyzer:
image

Something that I noticed is that for the rest of the tests done, changing block size seemed to get higher FPS, but for my GPU the result is the opposite:

|   1k (Vulkan)  | EA / FPS | PR / FPS | EA VS PR | PR MAX FPS VS PR BLOCK SIZE FPS |
|:-----:|:--------:|:--------:|:--------:|:-------------------------------:|
|  4x4  |    308   |    404   |   131%   |               100%              |
|  5x4  |    312   |    399   |   128%   |               99%               |
|  5x5  |    315   |    398   |   126%   |               99%               |
|  6x5  |    319   |    390   |   122%   |               97%               |
|  6x6  |    327   |    397   |   121%   |               98%               |
|  8x5  |    325   |    386   |   119%   |               96%               |
|  8x6  |    332   |    381   |   115%   |               94%               |
|  8x8  |    337   |    376   |   112%   |               93%               |
|  10x5 |    331   |    377   |   114%   |               93%               |
|  10x6 |    338   |    384   |   114%   |               95%               |
|  10x8 |    345   |    351   |   102%   |               87%               |
| 10x10 |    341   |    345   |   101%   |               85%               |
| 12x10 |    347   |    358   |   103%   |               89%               |
| 12x12 |    348   |    353   |   101%   |               87%               |

**Comment by gurrgur** [comment]
@ameerj I get about 2250fps using your latest changes. This seems barely lower than master which runs at about 2350fps.

**Comment by lat9nq** [comment]
https://github.com/yuzu-emu/yuzu/pull/11149#issuecomment-1666945179

> Can Mesa be retested with the latest commits?

A little bit of retesting of the previous branch head, retested master and this version.


Appears that Vulkan performance didn't improve. OpenGL performance improved, but remains slower than master.

**Comment by ameerj** [comment]
Everyone please retest Vulkan with async presentation enabled!

**Comment by gidoly** [comment]
bruh perf difference with async presentation on and off is absurd

EXCEL_GYYlTF7yKy

literal bruh moment

**Comment by gurrgur** [comment]
System Info

- GPU: RX6600XT
- Driver: mesa-git
- CPU: Ryzen 3600

| astc_1k \| Vulkan \| RADV | async presentation on (PR) | async presentation on (master) | async presentation off (PR) |
| ------------------------- | -------------------------- | ------------------------------ | --------------------------- |
| 4x4                       | 1430                       | 1081                           | 1306                        |
| 5x4                       | 1440                       | 1049                           | 1313                        |
| 5x5                       | 1480                       | 1077                           | 1410                        |
| 6x5                       | 1540                       | 1086                           | 1491                        |
| 6x6                       | 1550                       | 1082                           | 1463                        |
| 8x5                       | 1596                       | 1028                           | 1415                        |
| 8x6                       | 1581                       | 1056                           | 1421                        |
| 8x8                       | 1690                       | 1228                           | 1490                        |
| 10x5                      | 1615                       | 1025                           | 1424                        |
| 10x6                      | 1724                       | 1187                           | 1488                        |
| 10x8                      | 1697                       | 1273                           | 1556                        |
| 10x10                     | 1764                       | 1336                           | 1708                        |
| 12x10                     | 1696                       | 1338                           | 1681                        |
| 12x12                     | 1694                       | 1379                           | 1662                        |

| astc_1k \| OpenGL \| RadeonSI | PR   | master |
| ----------------------------- | ---- | ------ |
| 4x4                           | 2407 | 2338   |
| 5x4                           | 2580 | 2398   |
| 5x5                           | 2568 | 2346   |
| 6x5                           | 2524 | 2087   |
| 6x6                           | 2539 | 2168   |
| 8x5                           | 2494 | 2027   |
| 8x6                           | 2522 | 2149   |
| 8x8                           | 2707 | 2241   |
| 10x5                          | 2477 | 2045   |
| 10x6                          | 2371 | 2560   |
| 10x8                          | 2466 | 2746   |
| 10x10                         | 2407 | 2860   |
| 12x10                         | 2341 | 2928   |
| 12x12                         | 2303 | 2836   |

OpenGL results seem much less consistent as fps drops over time, making it harder to compare.

**Comment by ameerj** [comment]
@gurrgur are you able to test Mesa GL and VK and note any perf diffs after reverting the 3 latest commits?

**Comment by gurrgur** [comment]
Didnt have time to run all chunk sizes but decided to also retest master and astc-perf-prod without any reverted commits. On the rerun I couldnt believe the numbers for ogl/astc-perf-prod[5c25712af9530dfd27960036141989a6c2f0c3bc] (which includes the three commits you asked me to revert) so I did multiple runs to verify them. Seems like on my system your PR is superior compared to master in all aspects 👍

I believe the discrepancy with previous results comes from the fact that yuzu/astc_1k wasnt restarted before changing chunk size. The constant load on the gpu lead to dropping clock speed resulting in lower numbers. So this time I let the benchmark run just a few seconds for each block size, avoiding lower clock speeds. Also I tried keeping the procedure (how long the benchmark executable was run) as similar as possible between all runs.


astc_1k | [master] vk async | [astc-perf-prod 70f8ffb787a8bf394dfdc33420da3e6632472e5f] vk async | [astc-perf-prod 5c25712af9530dfd27960036141989a6c2f0c3bc] vs async | [master] ogl | [astc-perf-prod 70f8ffb787a8bf394dfdc33420da3e6632472e5f] ogl | [astc-perf-prod 5c25712af9530dfd27960036141989a6c2f0c3bc] ogl
-- | -- | -- | -- | -- | -- | --
4x4 | 1058 | 1245 | 1416 | 2270 | 2305/2315 | 2376/2356
8x8 | 1210 | 1394 | 1654 | 2585 | 2483/2474 | 3200/3204
10x10 | 1318 | 1432 | 1717 | 2825 | 2730/2714 | 3811/3749
12x12 | 1354 | 1431 | 1676 | 2803 | 2748/2737 | 3827/3816

**Comment by ameerj** [comment]
@lat9nq when you get the chance can you retest your ARC gpu?

**Comment by lat9nq** [comment]
Sorry for the delay.


Latest branch head appears to perform faster than master now.

**Review by liamwhite — APPROVED** [review]

**Pull request merged**
