### PR TITLE
configuration: Add settings to enable/disable specific CPU optimizations

### PR DESCRIPTION
**Pull request by MerryMage**
Expose fine-grained CPU optimization flags for debugging purposes only.

image
image
image

### CODE REVIEW

**Comment by MerryMage** [comment]
Added tooltips and changed layouts as per internal discussion.

**Comment by FearlessTobi** [comment]
Should we maybe add a Debug category and move the CPU and the Debug page there?
I'm just a bit worried that having this CPU category so prominently in the settings could lead some users to mess around with it.

**Comment by raven02** [comment]
Should "Multicore CPU emulation" under CPU tab ?

**Comment by MerryMage** [comment]
@FearlessTobi Added a Debug tab. Hope this is a sufficient deterent for you.

**Pull request merged**
