### PR TITLE
android: Improve Gradle build configuration

### PR DESCRIPTION
**Pull request by AbandonedCart**
org.gradle.jvmargs=
-Xms512m  <- Set the IDE to start with 512m allocated. 
-XX:MaxMetaspaceSize=512m <- Convert the MaxPermSize to new option 
-XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 (previous options)

android.useAndroidX=true

kotlin.code.style=official

kotlin.parallel.tasks.in.project=true <- parallel compilation tasks in the same project

android.defaults.buildfeatures.buildconfig=true

### CODE REVIEW

**Comment by AbandonedCart** [comment]
Combines with https://github.com/yuzu-emu/yuzu/pull/10641 to allow verification to pass.

**Comment by t895** [comment]
I'd prefer that you don't enable jetifier since we don't have any incompatible libraries and it will only add extra time to builds this way.

**Comment by t895** [comment]
Also is there a difference in build times by changing the max to 3GBs now? It's a pretty small app with most of the compilation time happening for native code. If this doesn't help much, it just takes longer to build on low-memory systems right?

**Comment by AbandonedCart** [comment]
Is it safe to assume you're building locally on a Chromebook equivalent?

**Comment by AbandonedCart** [comment]
You're limiting it to 2. At that point, you're better off not setting a value at all. However, if you need that limitation, then I can redirect the adjustments to the ci. They can also be set there.

**Comment by AbandonedCart** [comment]
For now, I removed the property entirely. It will start with 512 and the IDE / JVM will set the limit. This can be done for an instance of Android Studio by going to Help -> Edit Custom VM Options and setting an -Xmx value (without the declaration)

**Review by t895 — APPROVED** [review]

**Pull request merged**
