### PR TITLE
shader_recompiler: fix emulation of 3D textureGrad

### LINKED ISSUE #11422: Bayonetta 3 on early access/mainline 1543 builds crashing (EA 3840-3851/MAINLINE 1543/Vulkan/RDNA3)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3840 (and newer)
Mainline 1543

### Description of Issue

Bayonetta 3 is crashing following early access version 3840 and onwards.
RoT, Prologue playable up until second playable verse (following CMW cutscene).

All other chapters crash.

Relaunching Bayonetta 3 with disk shader cache enabled following initial crash/disk shader cache building leads to game crashing on launch. Deleting disk shader cache files allows game to launch up until situation described in first paragraph.

### Expected Behavior

The game does not crash.

### Reproduction Steps

Play Bayonetta 3 on EA 3840+ with Vulkan/RDNA3 card.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12488737/yuzu_log.txt)

### System Configuration

CPU: Intel Core i7-12700k
GPU/Driver: RX 7900 XTX / Radeon 23.8.1
RAM: 64GB 2x32 DDR5-5600
OS: Windows 11 Pro 22621.2134

### PR DESCRIPTION
**Pull request by liamwhite**
Fixes #11422

### CODE REVIEW

**Comment by gidoly** [comment]
also improve fog rendering. no more grainy artifact it is now par with switch rendering

**Comment by KreuzerNL** [comment]
Was the "Derivates" variable supposed to've been "Derivatives"?

**Comment by Squall-Leonhart** [comment]
> Derivates in the code

typo, this isn't even a word.

**Review by FernandoS27 — APPROVED** [review]

**Comment by liamwhite** [comment]
@KreuzerNL You are correct that it should read derivatives and not derivates (the arguments are the partial derivatives dP/dx and dP/dy for sampler point P and window coordinates x/y). However, the shader recompiler was mostly written by someone whose first language is not English. Fixing the terminology to all be consistent would be out of scope for this pull request, so I kept it consistent here.

**Comment by FernandoS27** [comment]
> Was the "Derivates" variable supposed to've been "Derivatives"? (edit) guess not, it reads both Derivatives and Derivates in the code.

Congrats you found yuzu's secret official language: spanglish. Almost all the GPU code is spanglish.

**Comment by boludoz** [comment]
> Was the "Derivates" variable supposed to've been "Derivatives"? (edit) guess not, it reads both Derivatives and Derivates in the code.

How annoying you are giving reactions to all the comments and criticizing, instead of criticizing, start doing something useful.

**Pull request merged**
