### PR TITLE
Add 'Configure Keys Directory' to File Menu

### PR DESCRIPTION
**Pull request by Jungorend**
Addressing Issue #1226, this should allow configuring the Keys directory to a different location if desired.

### CODE REVIEW

**Comment by FearlessTobi** [comment]
Sorry but I personally kinda fail to see the point of this. Instead of looking into addressing the original issue, this just adds yet another option to the user interface that's already a bit cluttered.

**Comment by Jungorend** [comment]
The impression I got is it would help to move to a location to avoid non-latin usernames causing issues.

Do you feel it would be better to move all the Configure Directory into a single dedicated Window in the File Menu to avoid clutter, or look into keeping Keys in one place but reading non-latin characters without issue?

**Comment by lioncash** [comment]
It would likely be better to fix the handling for non-Latin file directory paths, since that's an issue by itself.

**Comment by Jungorend** [comment]
Alright.

**Pull request closed without merging**
