### PR TITLE
yuzu-cmd: Fullscreen Improvements

### PR DESCRIPTION
**Pull request by sankasan**
Building on top of changes by @lat9nq as found in #6652

These patches add the following:
- Fullscreen support when the Vulkan renderer is used.
- Use desktop resolution when switching to fullscreen (all platforms) by default.

### CODE REVIEW

**Comment by german77** [comment]
Just as a side note. You dont need to close a PR. Just push the changes to the branch and git will update the PR automatically

**Comment by sankasan** [comment]
> Just as a side note. You dont need to close a PR. Just push the changes to the branch and git will update the PR automatically

I renamed the branch which somehow automatically closed the PR. It might be an error on my end though. My experience with git(hub) is fairly limited and rusty ;)

**Comment by Morph1984** [comment]
@sankasan Please rebase with git rebase instead of merging master into your branch

**Comment by sankasan** [comment]
> @sankasan Please rebase with git rebase instead of merging master into your branch

No problem... All should be in sync with master again.

**Review by bunnei — APPROVED** [review]

**Pull request merged**
