### PR TITLE
GPU: Implemented the DXN1 (BC4) texture format.

### PR DESCRIPTION
**Pull request by Subv**

### CODE REVIEW

**Comment by greggameplayer** [comment]
@Subv can you implement DXN2 which is the TextureFormat value 0x28 ?

**Comment by greggameplayer** [comment]
@Subv bit width of DXN2 also known as BC5 are about 128, according to : 
https://msdn.microsoft.com/en-us/library/windows/desktop/bb694531(v=vs.85).aspx

**Comment by greggameplayer** [comment]
and there is some informations about some other textures formats to implement like R32, R32_G32

**Comment by Subv** [comment]
`@Subv can you implement also with this PR DXN2 which is the TextureFormat value 0x28 ?`
No.
It'll be implemented when we find a game that uses it, and in a separate PR.

**Comment by greggameplayer** [comment]
@Subv ok no problem, but we should add all the textures formats even if we don't know a game that use them.

**Pull request merged**
