### PR TITLE
Map more missing opengl states

### PR DESCRIPTION
**Pull request by Tinob**
Add support for anisotropic filtering, lod settings, some fixes to stencil test and some tweaks to reduce state handling redundancy.

### CODE REVIEW

**Comment by ReinUsesLisp** [comment]
You should check for anisotropic's `_EXT` extension in SDL2 and Qt. Also, it'd be nice if you can use `ARB_texture_filter_anisotropic` (4.6) when available, that way yuzu doesn't depend on non-core extensions.

**Comment by Tinob** [comment]
@ReinUsesLisp Done

**Comment by Tinob** [comment]
that part is only  for extensions that are requiered for the emulator to work, and none of the extensions added by me are mandatory, if they are present they will be used if not, you will get glitches but it will still work.

**Comment by bunnei** [comment]
@Tinob can you rebase?

**Comment by Tinob** [comment]
rebased

**Pull request merged**
