### PR TITLE
image_info: adjust rescale thresholds and refactor constant use

### PR DESCRIPTION
**Pull request by liamwhite**
Helps resolution mods to work correctly in Tears of the Kingdom when using the scaler. Needs testing to ensure it hasn't caused any issues in other games.

### CODE REVIEW

**Review by Kelebek1 — APPROVED** [review]

**Comment by solarmystic** [comment]
A bit late, but this broke Xenoblade 3 when using the upscaling mod. 

There are white flickering outlines around distant objects when upscaling now, especially obvious when moving around. 

Video example (look at the distant palm trees and the large flying bird raptor)

https://github.com/yuzu-emu/yuzu/assets/4345150/238748ca-93bc-4546-8b7c-f7937e8fe965

**Comment by liamwhite** [comment]
Can you provide more information about your configuration? I passed it to an internal tester who couldn't reproduce this issue.

**Comment by solarmystic** [comment]
> Can you provide more information about your configuration? I passed it to an internal tester who couldn't reproduce this issue.

I'm on a i7 12700KF, NVIDIA RTX 2080TI machine, using the emu scaler enabler mod on update 2.0.0 of the game with 2x scaling used on the emulator.

The issue is not always apparent at certain times of the day and weather conditions. 

Another way the bug manifests is in the darkened, stripped areas of distant ground. I've highlighted it in the screenshot below with a red rectangle.

Issue

What it ought to look like, also highlighted with a red rectangle (image from Mainline 1467, which is unaffected):-

non Issue

My save for easy reproduction, pick save 2 to go straight to the demonstration area:- 

[010074F013262000.zip](https://github.com/yuzu-emu/yuzu/files/11913234/010074F013262000.zip)

**Comment by gidoly** [comment]
i couldn't reproduce on my 5800x3d 4090 system
yuzu_vFzHkfZoNP

here is setting i used
yuzu_ywhKVAxfiJ
yuzu_7EAIEhjdqG
yuzu_irdd4atWGP
i would try disable some mods first to see if it caused it

**Comment by gidoly** [comment]
seems issue happens for me on x2 but not on x3

**Comment by goldenx86** [comment]
Remember Turing is the only NVIDIA arch that can use FP16, confirm with console, as you may be hitting a hardware difference with Ada.

**Comment by liamwhite** [comment]
Console does not render at scaled resolution, what does that even mean

**Pull request merged**
