### PR TITLE
Putting guest thread to sleep inside handler

### PR DESCRIPTION
**Pull request by VishalRocks**

### CODE REVIEW

**Comment by VishalRocks** [comment]
https://github.com/yuzu-emu/yuzu/issues/40
For 3101 change from mentioned in the issue.

**Comment by greggameplayer** [comment]
There is 375 errors in core/hle/kernel/hle_ipc.h

**Comment by VishalRocks** [comment]
Yeah looking at it

**Comment by N00byKing** [comment]
@VishalRocks i recommend setting up an Appveyor and Travis Account and adding your Fork to it for testing, instead of doing work on it while the PR is open

**Comment by chris062689** [comment]
**Appveyor and Travis are not meant for testing code.**  Please do not recommend it be use that way, as it's an abuse of the service and is causing lots of issues with those companies because it bogs down the system for everyone. Those tools are designed as release agents, not testing if your code builds.

**Comment by bunnei** [comment]
Can you fix CI errors?

**Comment by Subv** [comment]
The citra PR has been merged with updated changes, please include them in this PR.

Please add a more detailed PR message and description.

Please keep the commit structure from the original citra PR.

**Comment by bunnei** [comment]
Ping to please wrap this up. Thanks!

**Comment by VishalRocks** [comment]
Will push by next week..sorry for the delay

**Comment by VishalRocks** [comment]
Please review and suggest any changes so that I can push them too asap and get this branch merged. Sorry for some bad commits, its my first commit for an open source.

**Comment by mailwl** [comment]
looks good...

**Comment by bunnei** [comment]
Sorry for the delay on this - after reviewing the code more closely, this is not something that can just be 1:1 ported from Citra. While we need this as well, the problem is that there are some implementation details here that are specific to the 3DS IPC. You can try to address this if you'd like, but if you're not sure how it works I'll probably supersede this PR with a fix.

**Comment by bunnei** [comment]
Closing as these changes were part of #250 - Thank you anyways!

**Pull request closed without merging**
