### PR TITLE
dynarmic: Abort watchpoints ASAP

### PR DESCRIPTION
**Pull request by merryhime**
Abort watchpoints as soon as possible.

Ref: https://github.com/merryhime/dynarmic/commit/f7b42b924ebaa5acd225d6629c2dab6f16a9cd39

### CODE REVIEW

**Review by liamwhite — APPROVED** [review]

**Comment by liamwhite** [comment]
Confirming that this fixes the reported issue.

Since halt is checked explicitly, is it no longer required to have memory instructions be the end of basic blocks with this?

**Comment by liamwhite** [comment]
Also, assuming the halt checks on memory accesses are removed, does this only check the condition if the access did not hit fastmem/page table? If so, it'll be a significant performance improvement over the previous implementation.

**Comment by merryhime** [comment]
> Also, assuming the halt checks on memory accesses are removed, does this only check the condition if the access did not hit fastmem/page table?

Made that change.

**Comment by liamwhite** [comment]
I am no longer able to boot the reproduction example in #8563 with the latest round of changes.

**Comment by merryhime** [comment]
Really sorry, made a [really trivial error](https://github.com/merryhime/dynarmic/commit/ea8e22f60c087bb8e6545c83f236b04461eb297d). Hopefully fixed.

**Comment by liamwhite** [comment]
Yes, it's working again now. Thank you! :+1:

**Comment by merryhime** [comment]
Hate to say 'works on my machine' but with my normal selection of games it works. Do you have a specific title that fails to boot?

**Pull request merged**
