### PR TITLE
externals: update cubeb (again)

### LINKED ISSUE #10390: Submodule path 'externals/cubeb' Compile fails
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

0

### Description of Issue

fatal: git upload-pack: not our ref 2d817de7c58b33a7c045edf873f3f9c98e4a2082
fatal: remote error: upload-pack: not our ref 2d817de7c58b33a7c045edf873f3f9c98e4a2082
fatal: Fetched in submodule path 'externals/cubeb', but it did not contain 2d817de7c58b33a7c045edf873f3f9c98e4a2082. Direct fetching of that commit failed.

### Expected Behavior

...

### Reproduction Steps

...

### Log File

...

### System Configuration

CPU:
GPU/Driver:
RAM:
OS:

### PR DESCRIPTION
**Pull request by danilaml**
When I made a PR I didn't notice that submodule didn't switch to a proper sha for some reason (from master, not PR branch).
This uses correct SHA. Probably fixes #10390 if it's related.

### CODE REVIEW

**Review by liamwhite — APPROVED** [review]

**Comment by killown** [comment]
Submodule path 'externals/SDL': checked out 'f17058b562c8a1090c0c996b42982721ace90903'
Submodule path 'externals/Vulkan-Headers': checked out '63af1cf1ee906ba4dcd5a324bdd0201d4f4bfd12'
Submodule path 'externals/cpp-httplib': checked out '6d963fbe8d415399d65e94db7910bbd22fe3741c'
Submodule path 'externals/cpp-jwt': checked out 'e12ef06218596b52d9b5d6e1639484866a8e7067'
fatal: git upload-pack: not our ref 48689ae7a73caeb747953f9ed664dc71d2f918d8
fatal: remote error: upload-pack: not our ref 48689ae7a73caeb747953f9ed664dc71d2f918d8
fatal: Fetched in submodule path 'externals/cubeb', but it did not contain 48689ae7a73caeb747953f9ed664dc71d2f918d8. Direct fetching of that commit failed.

**Comment by danilaml** [comment]
@killown I think your cubeb submodule might be broken in some way, since this commit is clearly present on cubeb master branch: https://github.com/mozilla/cubeb/commit/48689ae7a73caeb747953f9ed664dc71d2f918d8
Try removing `externals/cubeb` and initing it again.

**Comment by killown** [comment]
➜  trizen rm -rf yuzu-mainline-git              
➜  trizen aur aur/yuzu-mainline-git 
:: Cloning AUR package: yuzu-mainline-git

--------------------------------------------------------------------------------
:: Content of /files/trizen/yuzu-mainline-git/PKGBUILD
--------------------------------------------------------------------------------

# Maintainer: Brendan Szymanski <hello@bscubed.dev>
# Co-Maintainer: HurricanePootis <hurricanepootis@protonmail.com>

_pkgname=yuzu
pkgname=$_pkgname-mainline-git
pkgver=r23626.2506594c5
pkgrel=1
pkgdesc='An experimental open-source emulator for the Nintendo Switch (newest features)'
arch=('i686' 'x86_64')
url='https://github.com/yuzu-emu/yuzu-mainline'
license=('GPL2')
provides=('yuzu' 'yuzu-cmd')
conflicts=('yuzu-git' 'yuzu-canary-git' 'yuzu')
# Set "!strip" to keep the debugging symbols within the package for debugging
options=("lto" "strip") #Set LTO (Flatpak builds with Full GCC LTO)
depends=('fmt'
         'cubeb'
         'mbedtls'
         'libinih'
         'qt5-multimedia'
         'qt5-webengine'
         'sdl2'
         'enet'
         'boost-libs')
makedepends=('boost'
             'llvm'
             'catch2'
             'gcc'
             'cmake'
             'ffmpeg'
             'git'
             'ninja'
             'nlohmann-json'
             'qt5-tools'
             'robin-map'
             'rapidjson')
optdepends=("qt5-wayland: Wayland support")
source=("$_pkgname::git+https://github.com/yuzu-emu/yuzu-mainline"
        'git+https://github.com/lsalzman/enet.git'
        'git+https://github.com/benhoyt/inih.git'
        'git+https://github.com/kinetiknz/cubeb.git'
        'git+https://github.com/MerryMage/dynarmic.git'
        'libressl::git+https://github.com/citra-emu/ext-libressl-portable.git'
        'git+https://github.com/libusb/libusb.git'
        'git+https://github.com/yuzu-emu/discord-rpc.git'
        'git+https://github.com/KhronosGroup/Vulkan-Headers.git'
        'git+https://github.com/yuzu-emu/sirit'
        'git+https://github.com/yuzu-emu/mbedtls'
        'git+https://github.com/herumi/xbyak.git'
        'git+https://github.com/xiph/opus.git'
        'git+https://git.ffmpeg.org/ffmpeg.git'
        'git+https://github.com/libsdl-org/SDL.git'
        'git+https://github.com/yhirose/cpp-httplib.git'
        'git+https://github.com/Microsoft/vcpkg.git'
        'git+https://github.com/arun11299/cpp-jwt.git'
        # cubeb dependencies
        'git+https://github.com/arsenm/sanitizers-cmake.git'
        'git+https://github.com/google/googletest'
        # sirit dependencies
        'git+https://github.com/KhronosGroup/SPIRV-Headers.git')
md5sums=('SKIP'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP')

pkgver() {
    cd "$srcdir/$_pkgname"
    echo "r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)"
}

prepare() {
    cd "$srcdir/$_pkgname"

    for submodule in {inih,cubeb,dynarmic,libressl,libusb,discord-rpc,Vulkan-Headers,sirit,mbedtls,xbyak,opus,ffmpeg,SDL,cpp-httplib,vcpkg,cpp-jwt,enet}; 
    do
        git config --file=.gitmodules submodule.$submodule.url "$srcdir/${submodule}"
    done

    git -c protocol.file.allow=always submodule update --init

    cd "$srcdir/$_pkgname"/externals/cubeb

    git config --file=.gitmodules submodule.cmake/sanitizers-cmake.url "$srcdir/sanitizers-cmake"
    git config --file=.gitmodules submodule.googletest.url "$srcdir/googletest"
    git -c protocol.file.allow=always submodule update --init
    
    cd "$srcdir/$_pkgname"/externals/sirit
    
    git config --file=.gitmodules submodule.externals/SPIRV-Headers.url "$srcdir/SPIRV-Headers"
    git -c protocol.file.allow=always submodule update --init
}

build() {
    cd "$srcdir"
    
    [[ -d build ]] && rm -rf build

    cmake -S $_pkgname -B build \
      -GNinja \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_C_COMPILER=gcc \
      -DCMAKE_CXX_COMPILER=g++ \
      -DCMAKE_C_FLAGS="$CFLAGS -flto=auto" \
      -DCMAKE_CXX_FLAGS="$CXXFLAGS -flto=auto" \
      -DCMAKE_BUILD_TYPE=RelWithDebInfo \
      -DYUZU_USE_QT_WEB_ENGINE=ON \
      -DYUZU_USE_QT_MULTIMEDIA=ON \
      -DYUZU_ENABLE_LTO=ON \
      -DYUZU_USE_EXTERNAL_SDL2=OFF \
      -DYUZU_USE_BUNDLED_FFMPEG=OFF \
      -DYUZU_USE_BUNDLED_QT=OFF \
      -DYUZU_TESTS=OFF \
      -DENABLE_QT6=OFF \
      -DUSE_DISCORD_PRESENCE=ON \
      -DENABLE_QT_TRANSLATION=ON \
      -DBUILD_REPOSITORY=yuzu-emu/yuzu-mainline \
      -DBUILD_TAG=${pkgver} \
      -DTITLE_BAR_FORMAT_IDLE="yuzu | ${pkgver} {}" \
      -DTITLE_BAR_FORMAT_RUNNING="yuzu | ${pkgver} | {}" \
      -Wno-dev
    cmake --build build
}

package() {
    cd "$srcdir"
    DESTDIR="$pkgdir" cmake --install build
}

=>> Edit yuzu-mainline-git/PKGBUILD? [y/N]:  n

Repository      : AUR
Name            : yuzu-mainline-git
Version         : r23626.2506594c5-1
Maintainer      : bscubed
URL             : https://github.com/yuzu-emu/yuzu-mainline
AUR URL         : https://aur.archlinux.org/packages/yuzu-mainline-git
License         : GPL2
Votes           : 24
Popularity      : 1%
Installed       : Yes
Out Of Date     : No
Depends On      : fmt
                  cubeb
                  mbedtls
                  libinih
                  qt5-multimedia
                  qt5-webengine
                  sdl2
                  enet
                  boost-libs
Make Deps       : boost
                  llvm
                  catch2
                  gcc
                  cmake
                  ffmpeg
                  git
                  ninja
                  nlohmann-json
                  qt5-tools
                  robin-map
                  rapidjson
Check Deps      : None
Optional Deps   : qt5-wayland: Wayland support
Provides        : yuzu
                  yuzu-cmd
Conflicts With  : yuzu-git
                  yuzu-canary-git
                  yuzu
Replaces        : None
Package Base    : yuzu-mainline-git
Last Update     : Thu May  4 18:58:57 2023
Description     : An experimental open-source emulator for the Nintendo Switch (newest features)

==> Criando o pacote: yuzu-mainline-git r23626.2506594c5-1 (dom 21 mai 2023 16:13:52)
==> Verificando as dependências de tempo de execução...
==> Verificando as dependências de tempo de compilação...
==> Obtendo fontes...
  -> Clonando repositório yuzu do tipo git...
Cloning into bare repository '/files/trizen/yuzu-mainline-git/yuzu'...
remote: Enumerating objects: 206129, done.
remote: Counting objects: 100% (1885/1885), done.
remote: Compressing objects: 100% (599/599), done.
remote: Total 206129 (delta 1299), reused 1803 (delta 1281), pack-reused 204244
Receiving objects: 100% (206129/206129), 85.13 MiB | 10.34 MiB/s, done.
Resolving deltas: 100% (165162/165162), done.
  -> Clonando repositório enet do tipo git...
Cloning into bare repository '/files/trizen/yuzu-mainline-git/enet'...
remote: Enumerating objects: 2205, done.
remote: Counting objects: 100% (297/297), done.
remote: Compressing objects: 100% (183/183), done.
remote: Total 2205 (delta 181), reused 173 (delta 91), pack-reused 1908
Receiving objects: 100% (2205/2205), 733.24 KiB | 8.63 MiB/s, done.
Resolving deltas: 100% (1407/1407), done.
  -> Clonando repositório inih do tipo git...
Cloning into bare repository '/files/trizen/yuzu-mainline-git/inih'...
remote: Enumerating objects: 1157, done.
remote: Counting objects: 100% (164/164), done.
remote: Compressing objects: 100% (85/85), done.
remote: Total 1157 (delta 73), reused 127 (delta 68), pack-reused 993
Receiving objects: 100% (1157/1157), 252.42 KiB | 10.10 MiB/s, done.
Resolving deltas: 100% (659/659), done.
  -> Clonando repositório cubeb do tipo git...
Cloning into bare repository '/files/trizen/yuzu-mainline-git/cubeb'...
remote: Enumerating objects: 7253, done.
remote: Counting objects: 100% (681/681), done.
remote: Compressing objects: 100% (262/262), done.
remote: Total 7253 (delta 457), reused 533 (delta 399), pack-reused 6572
Receiving objects: 100% (7253/7253), 3.28 MiB | 7.56 MiB/s, done.
Resolving deltas: 100% (5081/5081), done.
  -> Clonando repositório dynarmic do tipo git...
Cloning into bare repository '/files/trizen/yuzu-mainline-git/dynarmic'...
remote: Enumerating objects: 50975, done.
remote: Counting objects: 100% (1761/1761), done.
remote: Compressing objects: 100% (919/919), done.
remote: Total 50975 (delta 823), reused 1602 (delta 741), pack-reused 49214
Receiving objects: 100% (50975/50975), 34.92 MiB | 10.20 MiB/s, done.
Resolving deltas: 100% (34890/34890), done.
  -> Clonando repositório libressl do tipo git...
Cloning into bare repository '/files/trizen/yuzu-mainline-git/libressl'...
remote: Enumerating objects: 2386, done.
remote: Counting objects: 100% (697/697), done.
remote: Compressing objects: 100% (551/551), done.
remote: Total 2386 (delta 252), reused 245 (delta 136), pack-reused 1689
Receiving objects: 100% (2386/2386), 4.82 MiB | 9.68 MiB/s, done.
Resolving deltas: 100% (1201/1201), done.
  -> Clonando repositório libusb do tipo git...
Cloning into bare repository '/files/trizen/yuzu-mainline-git/libusb'...
remote: Enumerating objects: 21199, done.
remote: Counting objects: 100% (891/891), done.
remote: Compressing objects: 100% (426/426), done.
remote: Total 21199 (delta 601), reused 600 (delta 416), pack-reused 20308
Receiving objects: 100% (21199/21199), 6.90 MiB | 6.56 MiB/s, done.
Resolving deltas: 100% (15299/15299), done.
  -> Clonando repositório discord-rpc do tipo git...
Cloning into bare repository '/files/trizen/yuzu-mainline-git/discord-rpc'...
remote: Enumerating objects: 1896, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 1896 (delta 1), reused 11 (delta 0), pack-reused 1871
Receiving objects: 100% (1896/1896), 2.74 MiB | 10.25 MiB/s, done.
Resolving deltas: 100% (1078/1078), done.
  -> Clonando repositório Vulkan-Headers do tipo git...
Cloning into bare repository '/files/trizen/yuzu-mainline-git/Vulkan-Headers'...
remote: Enumerating objects: 4302, done.
remote: Counting objects: 100% (79/79), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 4302 (delta 43), reused 74 (delta 42), pack-reused 4223
Receiving objects: 100% (4302/4302), 39.89 MiB | 10.35 MiB/s, done.
Resolving deltas: 100% (2831/2831), done.
  -> Clonando repositório sirit do tipo git...
Cloning into bare repository '/files/trizen/yuzu-mainline-git/sirit'...
remote: Enumerating objects: 1604, done.
remote: Counting objects: 100% (1604/1604), done.
remote: Compressing objects: 100% (313/313), done.
remote: Total 1604 (delta 1053), reused 1591 (delta 1044), pack-reused 0
Receiving objects: 100% (1604/1604), 204.22 KiB | 1.63 MiB/s, done.
Resolving deltas: 100% (1053/1053), done.
  -> Clonando repositório mbedtls do tipo git...
Cloning into bare repository '/files/trizen/yuzu-mainline-git/mbedtls'...
remote: Enumerating objects: 143488, done.
remote: Total 143488 (delta 0), reused 0 (delta 0), pack-reused 143488
Receiving objects: 100% (143488/143488), 65.31 MiB | 10.27 MiB/s, done.
Resolving deltas: 100% (110730/110730), done.
  -> Clonando repositório xbyak do tipo git...
Cloning into bare repository '/files/trizen/yuzu-mainline-git/xbyak'...
remote: Enumerating objects: 7089, done.
remote: Counting objects: 100% (830/830), done.
remote: Compressing objects: 100% (252/252), done.
remote: Total 7089 (delta 615), reused 652 (delta 577), pack-reused 6259
Receiving objects: 100% (7089/7089), 2.41 MiB | 5.93 MiB/s, done.
Resolving deltas: 100% (4919/4919), done.
  -> Clonando repositório opus do tipo git...
Cloning into bare repository '/files/trizen/yuzu-mainline-git/opus'...
remote: Enumerating objects: 32343, done.
remote: Counting objects: 100% (425/425), done.
remote: Compressing objects: 100% (148/148), done.
remote: Total 32343 (delta 289), reused 407 (delta 277), pack-reused 31918
Receiving objects: 100% (32343/32343), 10.25 MiB | 10.33 MiB/s, done.
Resolving deltas: 100% (25412/25412), done.
  -> Clonando repositório ffmpeg do tipo git...
Cloning into bare repository '/files/trizen/yuzu-mainline-git/ffmpeg'...
remote: Enumerating objects: 3076, done.
remote: Counting objects: 100% (3076/3076), done.
remote: Compressing objects: 100% (2426/2426), done.
remote: Total 691140 (delta 2043), reused 811 (delta 647)
Receiving objects: 100% (691140/691140), 166.32 MiB | 3.84 MiB/s, done.
Resolving deltas: 100% (559234/559234), done.
  -> Clonando repositório SDL do tipo git...
Cloning into bare repository '/files/trizen/yuzu-mainline-git/SDL'...
remote: Enumerating objects: 149142, done.
remote: Counting objects: 100% (46488/46488), done.
remote: Compressing objects: 100% (5187/5187), done.
remote: Total 149142 (delta 41914), reused 41672 (delta 41275), pack-reused 102654
Receiving objects: 100% (149142/149142), 110.60 MiB | 10.26 MiB/s, done.
Resolving deltas: 100% (115154/115154), done.
  -> Clonando repositório cpp-httplib do tipo git...
Cloning into bare repository '/files/trizen/yuzu-mainline-git/cpp-httplib'...
remote: Enumerating objects: 7010, done.
remote: Counting objects: 100% (62/62), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 7010 (delta 33), reused 39 (delta 21), pack-reused 6948
Receiving objects: 100% (7010/7010), 4.35 MiB | 7.91 MiB/s, done.
Resolving deltas: 100% (4599/4599), done.
  -> Clonando repositório vcpkg do tipo git...
Cloning into bare repository '/files/trizen/yuzu-mainline-git/vcpkg'...
remote: Enumerating objects: 568940, done.
remote: Counting objects: 100% (44847/44847), done.
remote: Compressing objects: 100% (1927/1927), done.
remote: Total 568940 (delta 43603), reused 43874 (delta 42919), pack-reused 524093
Receiving objects: 100% (568940/568940), 287.32 MiB | 10.36 MiB/s, done.
Resolving deltas: 100% (395631/395631), done.
  -> Clonando repositório cpp-jwt do tipo git...
Cloning into bare repository '/files/trizen/yuzu-mainline-git/cpp-jwt'...
remote: Enumerating objects: 1402, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (62/62), done.
remote: Total 1402 (delta 34), reused 47 (delta 14), pack-reused 1309
Receiving objects: 100% (1402/1402), 5.84 MiB | 10.30 MiB/s, done.
Resolving deltas: 100% (804/804), done.
  -> Clonando repositório sanitizers-cmake do tipo git...
Cloning into bare repository '/files/trizen/yuzu-mainline-git/sanitizers-cmake'...
remote: Enumerating objects: 305, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 305 (delta 36), reused 29 (delta 15), pack-reused 242
Receiving objects: 100% (305/305), 73.24 KiB | 8.14 MiB/s, done.
Resolving deltas: 100% (194/194), done.
  -> Clonando repositório googletest do tipo git...
Cloning into bare repository '/files/trizen/yuzu-mainline-git/googletest'...
remote: Enumerating objects: 52812, done.
remote: Counting objects: 100% (621/621), done.
remote: Compressing objects: 100% (351/351), done.
remote: Total 52812 (delta 387), reused 388 (delta 242), pack-reused 52191
Receiving objects: 100% (52812/52812), 30.20 MiB | 10.43 MiB/s, done.
Resolving deltas: 100% (36577/36577), done.
  -> Clonando repositório SPIRV-Headers do tipo git...
Cloning into bare repository '/files/trizen/yuzu-mainline-git/SPIRV-Headers'...
remote: Enumerating objects: 4509, done.
remote: Counting objects: 100% (446/446), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 4509 (delta 380), reused 379 (delta 344), pack-reused 4063
Receiving objects: 100% (4509/4509), 2.32 MiB | 10.16 MiB/s, done.
Resolving deltas: 100% (3033/3033), done.
==> Validando source arquivos com md5sums...
    yuzu ... Ignorada
    enet ... Ignorada
    inih ... Ignorada
    cubeb ... Ignorada
    dynarmic ... Ignorada
    libressl ... Ignorada
    libusb ... Ignorada
    discord-rpc ... Ignorada
    Vulkan-Headers ... Ignorada
    sirit ... Ignorada
    mbedtls ... Ignorada
    xbyak ... Ignorada
    opus ... Ignorada
    ffmpeg ... Ignorada
    SDL ... Ignorada
    cpp-httplib ... Ignorada
    vcpkg ... Ignorada
    cpp-jwt ... Ignorada
    sanitizers-cmake ... Ignorada
    googletest ... Ignorada
    SPIRV-Headers ... Ignorada
==> Extraindo fontes...
  -> Criando cópia de trabalho do repositório yuzu do tipo git...
Cloning into 'yuzu'...
done.
  -> Criando cópia de trabalho do repositório enet do tipo git...
Cloning into 'enet'...
done.
  -> Criando cópia de trabalho do repositório inih do tipo git...
Cloning into 'inih'...
done.
  -> Criando cópia de trabalho do repositório cubeb do tipo git...
Cloning into 'cubeb'...
done.
  -> Criando cópia de trabalho do repositório dynarmic do tipo git...
Cloning into 'dynarmic'...
done.
  -> Criando cópia de trabalho do repositório libressl do tipo git...
Cloning into 'libressl'...
done.
  -> Criando cópia de trabalho do repositório libusb do tipo git...
Cloning into 'libusb'...
done.
  -> Criando cópia de trabalho do repositório discord-rpc do tipo git...
Cloning into 'discord-rpc'...
done.
  -> Criando cópia de trabalho do repositório Vulkan-Headers do tipo git...
Cloning into 'Vulkan-Headers'...
done.
  -> Criando cópia de trabalho do repositório sirit do tipo git...
Cloning into 'sirit'...
done.
  -> Criando cópia de trabalho do repositório mbedtls do tipo git...
Cloning into 'mbedtls'...
done.
  -> Criando cópia de trabalho do repositório xbyak do tipo git...
Cloning into 'xbyak'...
done.
  -> Criando cópia de trabalho do repositório opus do tipo git...
Cloning into 'opus'...
done.
  -> Criando cópia de trabalho do repositório ffmpeg do tipo git...
Cloning into 'ffmpeg'...
done.
  -> Criando cópia de trabalho do repositório SDL do tipo git...
Cloning into 'SDL'...
done.
  -> Criando cópia de trabalho do repositório cpp-httplib do tipo git...
Cloning into 'cpp-httplib'...
done.
  -> Criando cópia de trabalho do repositório vcpkg do tipo git...
Cloning into 'vcpkg'...
done.
  -> Criando cópia de trabalho do repositório cpp-jwt do tipo git...
Cloning into 'cpp-jwt'...
done.
  -> Criando cópia de trabalho do repositório sanitizers-cmake do tipo git...
Cloning into 'sanitizers-cmake'...
done.
  -> Criando cópia de trabalho do repositório googletest do tipo git...
Cloning into 'googletest'...
done.
  -> Criando cópia de trabalho do repositório SPIRV-Headers do tipo git...
Cloning into 'SPIRV-Headers'...
done.
==> Iniciando prepare()...
Submodule 'SDL' (/files/trizen/yuzu-mainline-git/src/SDL) registered for path 'externals/SDL'
Submodule 'Vulkan-Headers' (/files/trizen/yuzu-mainline-git/src/Vulkan-Headers) registered for path 'externals/Vulkan-Headers'
Submodule 'cpp-httplib' (/files/trizen/yuzu-mainline-git/src/cpp-httplib) registered for path 'externals/cpp-httplib'
Submodule 'cpp-jwt' (/files/trizen/yuzu-mainline-git/src/cpp-jwt) registered for path 'externals/cpp-jwt'
Submodule 'cubeb' (/files/trizen/yuzu-mainline-git/src/cubeb) registered for path 'externals/cubeb'
Submodule 'discord-rpc' (/files/trizen/yuzu-mainline-git/src/discord-rpc) registered for path 'externals/discord-rpc'
Submodule 'dynarmic' (/files/trizen/yuzu-mainline-git/src/dynarmic) registered for path 'externals/dynarmic'
Submodule 'enet' (/files/trizen/yuzu-mainline-git/src/enet) registered for path 'externals/enet'
Submodule 'ffmpeg' (/files/trizen/yuzu-mainline-git/src/ffmpeg) registered for path 'externals/ffmpeg/ffmpeg'
Submodule 'inih' (/files/trizen/yuzu-mainline-git/src/inih) registered for path 'externals/inih/inih'
Submodule 'libusb' (/files/trizen/yuzu-mainline-git/src/libusb) registered for path 'externals/libusb/libusb'
Submodule 'mbedtls' (/files/trizen/yuzu-mainline-git/src/mbedtls) registered for path 'externals/mbedtls'
Submodule 'opus' (/files/trizen/yuzu-mainline-git/src/opus) registered for path 'externals/opus/opus'
Submodule 'sirit' (/files/trizen/yuzu-mainline-git/src/sirit) registered for path 'externals/sirit'
Submodule 'vcpkg' (/files/trizen/yuzu-mainline-git/src/vcpkg) registered for path 'externals/vcpkg'
Submodule 'xbyak' (/files/trizen/yuzu-mainline-git/src/xbyak) registered for path 'externals/xbyak'
Cloning into '/files/trizen/yuzu-mainline-git/src/yuzu/externals/SDL'...
done.
Cloning into '/files/trizen/yuzu-mainline-git/src/yuzu/externals/Vulkan-Headers'...
done.
Cloning into '/files/trizen/yuzu-mainline-git/src/yuzu/externals/cpp-httplib'...
done.
Cloning into '/files/trizen/yuzu-mainline-git/src/yuzu/externals/cpp-jwt'...
done.
Cloning into '/files/trizen/yuzu-mainline-git/src/yuzu/externals/cubeb'...
done.
Cloning into '/files/trizen/yuzu-mainline-git/src/yuzu/externals/discord-rpc'...
done.
Cloning into '/files/trizen/yuzu-mainline-git/src/yuzu/externals/dynarmic'...
done.
Cloning into '/files/trizen/yuzu-mainline-git/src/yuzu/externals/enet'...
done.
Cloning into '/files/trizen/yuzu-mainline-git/src/yuzu/externals/ffmpeg/ffmpeg'...
done.
Cloning into '/files/trizen/yuzu-mainline-git/src/yuzu/externals/inih/inih'...
done.
Cloning into '/files/trizen/yuzu-mainline-git/src/yuzu/externals/libusb/libusb'...
done.
Cloning into '/files/trizen/yuzu-mainline-git/src/yuzu/externals/mbedtls'...
done.
Cloning into '/files/trizen/yuzu-mainline-git/src/yuzu/externals/opus/opus'...
done.
Cloning into '/files/trizen/yuzu-mainline-git/src/yuzu/externals/sirit'...
done.
Cloning into '/files/trizen/yuzu-mainline-git/src/yuzu/externals/vcpkg'...
done.
Cloning into '/files/trizen/yuzu-mainline-git/src/yuzu/externals/xbyak'...
done.
Submodule path 'externals/SDL': checked out 'f17058b562c8a1090c0c996b42982721ace90903'
Submodule path 'externals/Vulkan-Headers': checked out '63af1cf1ee906ba4dcd5a324bdd0201d4f4bfd12'
Submodule path 'externals/cpp-httplib': checked out '6d963fbe8d415399d65e94db7910bbd22fe3741c'
Submodule path 'externals/cpp-jwt': checked out 'e12ef06218596b52d9b5d6e1639484866a8e7067'
fatal: git upload-pack: not our ref 48689ae7a73caeb747953f9ed664dc71d2f918d8
fatal: remote error: upload-pack: not our ref 48689ae7a73caeb747953f9ed664dc71d2f918d8
fatal: Fetched in submodule path 'externals/cubeb', but it did not contain 48689ae7a73caeb747953f9ed664dc71d2f918d8. Direct fetching of that commit failed.
==> ERRO: Uma falha ocorreu em prepare().
    Abortando...
:: Unable to build yuzu-mainline-git - makepkg exited with code: 4
=>> Try again? [y/N]:  n
=>> Exit now? [Y/n]:  y

**Comment by danilaml** [comment]
@killown please, format the comment somehow that it's readable, but:

>'git+https://github.com/kinetiknz/cubeb.git'

I don't know why AUR uses some fork of  https://github.com/mozilla/cubeb.git as src for cubeb, but that's probably the reason. You should figure it out with AUR maintainer. This is not a yuzu issue.

**Comment by FearlessTobi** [comment]
Will you also port this fix to Citra? @danilaml

**Comment by danilaml** [comment]
@FearlessTobi citra has the correct sha, so no need to fix 😌 .

**Pull request merged**
