### PR TITLE
Increase boost requirement to 1.78.0

### PR DESCRIPTION
**Pull request by goldenx86**
Liu's finding, this allows to build yuzu on VS 2022.
Ignore at will.

### CODE REVIEW

**Comment by german77** [comment]
Did Conan added support to 1.78.0?

**Comment by neico** [comment]
If you use the new https://center.conan.io as remote, then yes.

**Comment by FearlessTobi** [comment]
Will this cause any problems when other compilers are using different boost versions? 
It seems like we're using 1.73, 1.75 and 1.78 at the same time now.

**Comment by german77** [comment]
I noticed that as well. We don't use any new feature. But 1.78 is required to compile in VS2022. Maybe update requirements to only above 1.73 with default at 1.78

**Comment by liushuyu** [comment]
> Will this cause any problems when other compilers are using different boost versions? It seems like we're using 1.73, 1.75 and 1.78 at the same time now.

You can find a compiler compatibility list at the bottom of this page:
https://www.boost.org/users/history/version_1_78_0.html

**Comment by bunnei** [comment]
`##[warning]cl(0,0): Warning D9025: overriding '/Ob2' with '/Ob3'`

Looks like the warning settings are bleeding into our build?

`##[error]src\shader_recompiler\backend\spirv\emit_spirv.cpp(35,0): Error C2220: the following warning is treated as an error`

... Untagging again.

**Comment by goldenx86** [comment]
Conflicts somehow with Early Access, clossing.

**Comment by goldenx86** [comment]
Boss says to reopen, we reopen.

**Review by bunnei — APPROVED** [review]

**Pull request merged**
