### PR TITLE
Revert "Partial revert of #10433 (Texture Cache Util: Fix block depth adjustment on slices)"

### LINKED ISSUE #11738: TOTK crash on start up after update to ML 1582
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1582

### Description of Issue

After updating to 1582, TOTK crashes after the launching screen. However all other games (MK8, M:O, Katamari) run fine.

I've tried disabling all my mods and deleting the shader cache but it still crashes.

### Expected Behavior

That the game launches fine like it did earlier today before the yuzu update.

### Reproduction Steps

1. Launch game
2. Get error that application has crashed

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12859862/yuzu_log.txt)
[inxi.txt](https://github.com/yuzu-emu/yuzu/files/12859871/inxi.txt)

### System Configuration

CPU: Intel Core i7-8750H
GPU/Driver: GeForce RTX 2070 Mobile 535.113.01
RAM: 32GB
OS: Fedora 38 Workstation
Kernel: 6.5.6-200.fc38.x86_64

### PR DESCRIPTION
**Pull request by liamwhite**
Reverts yuzu-emu/yuzu#11534
Fixes #11738

Found to cause out of bounds reads/writes in Tears of the Kingdom, but was not caught due to Flathub releases being outdated for several days. Explicit crashes can be triggered with:

```diff
--- a/src/video_core/textures/decoders.cpp
+++ b/src/video_core/textures/decoders.cpp
@@ -79,6 +79,14 @@ void SwizzleImpl(std::span<u8> output, std::span<const u8> input, u32 width, u32
                 const u32 unswizzled_offset =
                     slice * pitch * height + line * pitch + column * BYTES_PER_PIXEL;
 
+                if constexpr (TO_LINEAR) {
+                    if (swizzled_offset >= output.size()) Crash();
+                    if (unswizzled_offset >= input.size()) Crash();
+                } else {
+                    if (unswizzled_offset >= output.size()) Crash();
+                    if (swizzled_offset >= input.size()) Crash();
+                }
+
                 u8* const dst = &output[TO_LINEAR ? swizzled_offset : unswizzled_offset];
                 const u8* const src = &input[TO_LINEAR ? unswizzled_offset : swizzled_offset];
 
```

### CODE REVIEW

**Comment by FernandoS27** [comment]
Wtf?

**Comment by Kelebek1** [comment]
Everything related to block size calculation needs to be nuked and re-done, lol. This code has been changed and reverted at least 5 times now.

**Comment by Squall-Leonhart** [comment]
> Everything related to block size calculation needs to be nuked and re-done, lol. This code has been changed and reverted at least 5 times now.

Yeah, i'm not even sure whats wrong with these flatpak builds, the code works fine everywhere else.

**Comment by v1993** [comment]
@Squall-Leonhart Flatpak builds include extra checks compared to others, hence code that more-or-less works elsewhere but has a hidden bug has a chance of hitting an assert there.

**Comment by Squall-Leonhart** [comment]
Ah i see, well it was my mistake anyway.  I had some AI help to go over the usages of info.block and level_info.block after noticing i had changed those in the swizzle handling in util.cpp and realised i hadn't made those same changes anywhere else, so now i know that level_info.block is the block information for adjusted mips, while info.block is the original info.  I should always make sure to pass level_info.block rather than info.block any time i'm interacting with adjustedmipsize

**Pull request closed without merging**
