### PR TITLE
core: Add support for loading NSPs with personalized tickets.

### PR DESCRIPTION
**Pull request by Steveice10**
Adds support for loading personalized (encrypted title key) tickets from NSP files. Previously the relevant code would assume a common key and load in the first 16 bytes of the key area. Now, the code properly reads the ticket and loads it in as personalized or common depending on the type.

This also adds support for eticket_rsa_keypair key material, which was added to the Lockpick_RCM output sometime late last year and can be used instead of needing to derive the key material from other system files. The key pair is also now derived ahead of time and stored in KeyManager instead of re-deriving it every time it is needed.

### CODE REVIEW

**Comment by FearlessTobi** [comment]
Maybe a bit out of scope, but can we do the same for XCI identification as well?

**Comment by Steveice10** [comment]
> Changes look good, however, the reason why the NSP is parsed that way is to prevent updates from showing in the games list. With your change, updates and/or dlc will erroneously show up as launchable games.

Thanks for the info, I'll probably just drop that part of it for now then and do an investigation into speeding up loading later. Maybe try to lazy load more of the data that the game list doesn't use or something.

**Comment by Stiffy360** [comment]
I'm getting crashes loading any of my games when using this artifact. All of my Cartridge games are dumped in the .NSP file format with "Change NPDM RSA key/sig in Program NCA set to "Yes" in NXDumpTool

I have not been able to test with e-shop titles as I do not possess them.

**Comment by Steveice10** [comment]
> I'm getting crashes loading any of my games when using this artifact. All of my Cartridge games are dumped in the .NSP file format with "Change NPDM RSA key/sig in Program NCA set to "Yes" in NXDumpTool
> 
> I have not been able to test with e-shop titles as I do not possess them.

Please provide a log and/or crash trace as I do not have any cartridges to test with.

**Comment by Stiffy360** [comment]
The logs don't seem to provide any useful information

https://www.mediafire.com/file/ucwlgjk4cqm7v6z/log.zip/file

**Comment by Steveice10** [comment]
These logs look to be crashes after the game has already loaded up and launched, not sure how that would relate to this PR as it only modifies logic during initial load.

**Comment by Stiffy360** [comment]
The games crash on launch, I've tested with other PRs and did not have a crash until I used this pull request specifically.

Here's a video demonstrating the crash

https://www.mediafire.com/file/y59aujh90qmsbgm/crash.mp4/file

**Comment by Steveice10** [comment]
I've added some additional logging for ticket parsing failure cases, please try again and post another log so I can see if that's the issue here.

**Comment by Stiffy360** [comment]
Tried again with the new artifact pr10048-20230417-445c517cf

I got the crashes still. Looks like the program exits before it has time to finish writing the logs.

Just to double-check I built the latest yuzu version and I do not have crashes there.

https://www.mediafire.com/file/8pljdpyk63i1mry/log_new.zip/file

**Comment by Stiffy360** [comment]
Adding onto this, Took me a bit to figure out how to build it, but I built it and ran it in Visual Studio and got these following stack trace exceptions:

`[  47.365458] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateGraphicsPipeline:571: 0xb731da5e6831593f
[  47.366220] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateGraphicsPipeline:571: 0xeac4e6ee3575cb23
[  47.366340] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateGraphicsPipeline:571: 0xa4e1fe8eb84823c0
[  47.366443] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateGraphicsPipeline:571: 0x9436ecc9c5f06219
[  47.402595] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:SerializeVulkanPipelineCache:749: Vulkan driver pipelines cached at: C:\Users\Jewell\AppData\Roaming\yuzu\shader\01007ef00011e000\vulkan_pipelines.bin
Exception thrown at 0x00007FFB24EECD29 in yuzu.exe: Microsoft C++ exception: std::bad_variant_access at memory location 0x000002DED4A1EC40.
Unhandled exception at 0x00007FFB24EECD29 in yuzu.exe: Microsoft C++ exception: std::bad_variant_access at memory location 0x000002DED4A1EC40.`

Keymanager.cpp Line 195

**Comment by Morph1984** [comment]
Untagging as it causes weird detection issues

**Comment by Steveice10** [comment]
> Untagging as it causes weird detection issues

Can you elaborate on what these issues are? (unless you're referring to the above issue still existing)

**Comment by german77** [comment]
Some users have reported having some of their games gone from the game list when they previously worked.

**Comment by Steveice10** [comment]
> Some users have reported having some of their games gone from the game list when they previously worked.

Any log samples that you've received for this? There should be logs when e.g. the ticket fails to be read from the NSP.

**Comment by Steveice10** [comment]
Finally gave some time to this again, went and sanitized all the places we read and use the Ticket structure to hopefully eliminate any instability. The working theory I have is that by loading in the eticket_rsa_keypair from the prod.keys, more ticket-related code paths are being triggered that were not without that key in place.

**Comment by Steveice10** [comment]
Last commit should make sure if someone has a NSP with a bad ticket but a good title key in their keys files, the title key won't get overwritten by the ticket and break the NSP.

**Comment by Steveice10** [comment]
Rebased and fixed the slow loading speed issues I was having with the game list, it was re-parsing the ticket title key every time instead of relying on the already loaded values.

**Comment by Steveice10** [comment]
Could this get another look taken at it? It's been updated for a while now.

**Comment by Steveice10** [comment]
Rebased

**Comment by RUANRUI1995** [comment]
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/12417089/yuzu_log.txt.old.txt)
Could not load Super Robot Wars 30 [0100ECB0129BE000][v0][Base].nsp

**Comment by Steveice10** [comment]
> [yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/12417089/yuzu_log.txt.old.txt) Could not load Super Robot Wars 30 [0100ECB0129BE000][v0][Base].nsp.Mainline 1534 is ok.

Latest commit should hopefully fix this, thanks.

**Comment by liamwhite** [comment]
Every time I boot an application I now get these messages printed in the log:
```
[  83.965319] Common.Filesystem <Error> common/fs/file.cpp:Open:281: Failed to open the file at path=.local/share/yuzu/nand/system/save/80000000000000e1, ec_message=No such file or directory
[  83.965333] Common.Filesystem <Error> common/fs/file.cpp:Open:281: Failed to open the file at path=.local/share/yuzu/nand/system/save/80000000000000e2, ec_message=No such file or directory
```
Can these be silenced?

**Comment by Steveice10** [comment]
> Every time I boot an application I now get these messages printed in the log:
> 
> ```
> [  83.965319] Common.Filesystem <Error> common/fs/file.cpp:Open:281: Failed to open the file at path=.local/share/yuzu/nand/system/save/80000000000000e1, ec_message=No such file or directory
> [  83.965333] Common.Filesystem <Error> common/fs/file.cpp:Open:281: Failed to open the file at path=.local/share/yuzu/nand/system/save/80000000000000e2, ec_message=No such file or directory
> ```
> 
> Can these be silenced?

Should be taken care of

**Review by liamwhite — APPROVED** [review]

**Pull request merged**
