### PR TITLE
decoder/image: Fix incorrect G24R8 component sizes in GetComponentSize()

### PR DESCRIPTION
**Pull request by lioncash**
The components' sizes were mismatched. This corrects that.

### CODE REVIEW

**Comment by FernandoS27** [comment]
Component 0 is Red and component 1 is Green. I believe they were correct.

**Comment by lioncash** [comment]
Would this not make its use in [GetComponentType()](https://github.com/yuzu-emu/yuzu/blob/24620bc4ea9ca59a757b7f07ca912f6645c5b8ef/src/video_core/shader/decode/image.cpp#L111) incorrect? Its case label is returning `g_type` for component 0 rather than r_type.

**Comment by ReinUsesLisp** [comment]
Never mind, I should test this in hardware.

**Comment by bunnei** [comment]
Added the `do-not-merge` tag, since it sounds like @ReinUsesLisp plans to verify this on HW first

**Pull request merged**
