### PR TITLE
ci: Port Citra flatpak build to yuzu

### PR DESCRIPTION
**Pull request by meiro**
Port Citra's travis based flatpak build to yuzu's Azure build system.

Depends on [the Docker image](https://github.com/yuzu-emu/build-environments/pull/7) being published to yuzuemu/build-environments:linux-flatpak.

~Build will fail due to #3754~

Based on:
- #3259 by abderrahim
- Citra flatpak build for travis ([here](https://github.com/citra-emu/citra/tree/master/.travis/linux-flatpak))

keys.tar.enc is an empty placeholder

### CODE REVIEW

**Comment by H27CK** [comment]
I am working on solving https://github.com/yuzu-emu/yuzu/issues/3754, which will allow this to build.

**Comment by bunnei** [comment]
@liushuyu can you comment on this one?

(also @DarkLordZach as FYI, up to you if you have any input here)

**Comment by meiro** [comment]
The dockerfile this needs has been merged as [PR 7](https://github.com/yuzu-emu/build-environments/pull/7). The image has not yet been pushed to [yuzuemu/](https://hub.docker.com/r/yuzuemu/build-environments/tags). Until this happens I have a separate master-testing branch in my fork, which uses the image pushed to [meirod/](https://hub.docker.com/repository/docker/meirod/build-environments/tags).

**Comment by meiro** [comment]
Pipelines have been set up [here](https://dev.azure.com/romanmeier/yuzu-test/_build) for testing purposes. "meiro.yuzu (testing)" is based on the master-testing branch.

Note that "successful" builds are expected to fail at step "Post-job: Cache Build System".
@DarkLordZach has a fix for this, I think.

**Comment by meiro** [comment]
#3757 and its associated PR in yuzu-emu/build-environments#10 made it so that all docker images now run as the non-root user "yuzu".

Because the flatpak docker.sh script is a little more involved than its counterparts it broke in multiple places.

I'm currently working on resolving these issues.

**Comment by soredake** [comment]
Any progress on this?

**Comment by soredake** [comment]
https://github.com/flathub/org.citra_emu.citra

**Comment by liushuyu** [comment]
> https://github.com/flathub/org.citra_emu.citra

I was waiting for someone to bring this up, however, here it is: https://github.com/flathub/flathub/pull/2139.

**Comment by soredake** [comment]
https://flathub.org/apps/details/org.yuzu_emu.yuzu

**Comment by Morph1984** [comment]
Closing as we now have an officially maintained flatpak repository above

**Pull request closed without merging**
