### PR TITLE
video_core: Make use of defaulted three-way comparison where applicable

### PR DESCRIPTION
**Pull request by lioncash**
Allows the compiler to generate the comparison operators in a much more succinct manner.

### CODE REVIEW

**Comment by lioncash** [comment]
Seems like the Windows buildbot doesn't support this yet :|

**Comment by bunnei** [comment]
@lioncash Should this be closed then?

**Comment by ameerj** [comment]
Many of these files no longer exist given the various rewrites and changes over the last year. Is this something you want to keep opened @lioncash ?

**Comment by ameerj** [comment]
Closing due to the above.

**Pull request closed without merging**
