### PR TITLE
fix a version number in the window title bar for updated applications.

### PR DESCRIPTION
**Pull request by CrazyMax**
fix to get version number from updated applications.

master
p2_m1

PR
p2_p1

master
p3_m1

PR
p3_p1

### CODE REVIEW

**Comment by Gustav0ar** [comment]
Isn't that already implemented? Here is latest master for me:
image

**Comment by ToxaGaming** [comment]
It was implemented, but for a while now I've noticed that the game version only appears on custom compiled builds and not in the officially released builds. Hopefully that is what this PR fixes

**Comment by Morph1984** [comment]
I'm not sure what this solves. The implementation of showing the game version only 1) works on custom builds and 2) also works for updated games.

**Comment by CrazyMax** [comment]
i compiled the latest version of mainline and does't show the version of the game

p1

**Comment by Morph1984** [comment]
Thats odd because it shows up for me 
image

**Comment by Morph1984** [comment]
Try merging #3385 and #4249, delete all the contents in your registered cache, and try seeing if the update shows up

**Comment by Morph1984** [comment]
I see that there are 2 other PRs that were closely related to the issue, it looks like it isn't able to parse the control nca from the base title on your end?

**Comment by CrazyMax** [comment]
i tested with merged to mainline PRs #3385, #4249 and #3385 + #4249 - not any changes, the version in title bar is empty (and gets null PatchManager)

only when i install the game to NAND i can see the version of the game in title bar

p2

**Comment by Morph1984** [comment]
@CrazyMax Ah I have traced this issue to loading the game from a file. When you load a game from a file it does not seem to initialize the patch manager.

**Comment by CrazyMax** [comment]
no, i all time loading from the game list

**Comment by jojodunet** [comment]
Hi guys, please check this related PR

https://github.com/yuzu-emu/yuzu/issues/4063

**Pull request closed without merging**
