### PR TITLE
gl_device: Intel: do not apply Windows fixes in Linux

### PR DESCRIPTION
**Pull request by A-w-x**
Fixes regressions introduced [here](https://github.com/yuzu-emu/yuzu/commit/7d904fef2e6ac9ce8a3df71e758a36d39b8f69e5)

Known regression: Mario Tennis home menu is a black screen
Tested on mesa 20.3.4 Iris plus gen 11

Are amd igpus affected too?

### CODE REVIEW

**Comment by v1993** [comment]
Please accept CLA. Yuzu can not accept contributions without that.

**Comment by A-w-x** [comment]
i see no regressions

@ReinUsesLisp
what games are fixed by this?
so that i can see if i can test affected games and we close this pr

**Comment by ReinUsesLisp** [comment]
What do you mean? That was added because texture views are broken on Intel and AMD, but mesa is not affected. An easy way to test if texture views work is to boot Pokémon Sword without a save, the first screen should be broken.

I don't see anything wrong with excluding mesa Intel from the blacklist, as long as it's an updated driver (because texture views on blits were also broken).

**Comment by v1993** [comment]
Please note that it's preferred to rebase on top of fresh master than opening another PR for future contributions.

**Pull request closed without merging**
