### PR TITLE
Port citra-emu/citra#4244 and citra-emu/citra#4599: Changes to BitField

### PR DESCRIPTION
**Pull request by FearlessTobi**
See citra-emu/citra#4244 and citra-emu/citra#4599 for details.

Even if the enum swap template from 4244 is not used yet, it's good to have it around just in case and also in order to keep parity between Citra and yuzu.

### CODE REVIEW

**Comment by bunnei** [comment]
@FearlessTobi msvc failure (tests) look real

**Comment by bunnei** [comment]
@FearlessTobi ping again here.

**Comment by FearlessTobi** [comment]
Travis Github status is borked for some reason. Anyway, all CI checks passed now.

**Comment by FearlessTobi** [comment]
What's the status of this?

**Comment by bunnei** [comment]
Sorry for the delay - too many PRs lately (I guess that's not a bad thing)

**Pull request merged**
