### PR TITLE
remove an error from end of Visual Studio build process

### PR DESCRIPTION
**Pull request by Docteh**
I built yuzu with MSVC today (Visual Studio 2022 hype?), and at the very bottom there was a message stating

27>'/NJH' is not recognized as an internal or external command,
27>operable program or batch file.

The cause of this is a newline at the end of the requirements.txt in the precompiled ffmpeg dlls

Flags intended to be sent to robocopy are instead attempted to be executed as a command.

As this is normal, I believe the build scripts need to adjust to fit what is provided.

externals/cmake-modules/WindowsCopyFiles.cmake has the actual invocation of robocopy

The precompiled dlls are from here, and will be in build/externals
https://github.com/yuzu-emu/ext-windows-bin/tree/master/ffmpeg

Extra bonus note not in the commit message: I checked the docs for CMake, and even 3.0 supports the REGEX REPLACE command. Also robocop branch for robocopy problems.

### CODE REVIEW

**Comment by german77** [comment]
Why not updating the externals instead of patching the file?

**Comment by Docteh** [comment]
@german77 I looked under both [yuzu-emu](https://github.com/orgs/yuzu-emu/repositories) and [citra-emu](https://github.com/orgs/citra-emu/repositories?type=all) repository lists and I'm not seeing a repository that would create a zip



```
$ hexdump requirements.txt -c
0000000   a   v   c   o   d   e   c   -   5   8   .   d   l   l   ;   a
0000010   v   u   t   i   l   -   5   6   .   d   l   l   ;   l   i   b
0000020   w   i   n   p   t   h   r   e   a   d   -   1   .   d   l   l
0000030   ;   s   w   s   c   a   l   e   -   5   .   d   l   l  \n
000003f
```

Is ending files with `\n` a habit just seen on Linux? notepad.exe and notepad++ are both willing to remove the trailing newline, but I tried the nano that comes with MSYS2's environment, and also vim and they like trailing newlines

`echo -n "avcodec-58.dll;avutil-56.dll;libwinpthread-1.dll;swscale-5.dll" > requirements.txt`

**Comment by Docteh** [comment]
🤦‍♂️ anyways I submitted a PR over there. I'll keep an eye on it.

**Comment by german77** [comment]
Superseded by  https://github.com/yuzu-emu/ext-windows-bin/pull/30

**Pull request closed without merging**
