### PR TITLE
Implement TAS Tools Please

### PR DESCRIPTION
**Pull request by FilipeTales**
It Would be amazing if you Implement TAS Tools in yuzu emulator!

### CODE REVIEW

**Comment by BSoDGamingYT** [comment]
This is not what GitHub pull requests are for, please stop wasting developer time

**Comment by FearlessTobi** [comment]
Please don't use Github if you have no clue how it works.

**Comment by Yvar192** [comment]
i love this

**Comment by illusion98** [comment]
Meme.

**Comment by Margen67** [comment]
If you can't use GitHub I doubt you can use TAS Tools..

**Pull request closed without merging**
