### PR TITLE
Implement SurfaceTarget Texture2DArray

### PR DESCRIPTION
**Pull request by greggameplayer**
( needed by Mario+Rabbids Kingdom Battle )

### CODE REVIEW

**Comment by ogniK5377** [comment]
Rebase please

**Comment by greggameplayer** [comment]
@ogniK5377 Done

**Comment by bunnei** [comment]
Conflicts with #1616. We will merge that one first, then this will need a rebase.

**Comment by bunnei** [comment]
Done - please rebase.

**Comment by greggameplayer** [comment]
@bunnei done

**Pull request merged**
