### PR TITLE
gl_texture_cache: Unify BGR copy passes using PBOs

### LINKED ISSUE #6492: OpenGL BGR fixes do not work on Kepler
atm affects: 
A Hat in Time [GLSL yuzu_log.txt.tar.gz](https://github.com/yuzu-emu/yuzu/files/6680124/yuzu_log.txt.tar.gz)
Octopath Traveler Prologue Demo
Yoshi's Crafted World Demo
Braverly Default II Final Demo

^ above log is from running on the hades testing branch. This issue is being transferred over here as an issue on master, thus the problems in the logs should be the same.

### LINKED ISSUE #6625: Dragon Ball FighterZ - [OpenGL] - Do Not Render (even with Shader Rewrite)
While on yuzu Early Access 1869, when trying to play Dragon Ball FighterZ on OpenGL the game do not render, most area are black. I've tried with all possibilities with OpenGL (all new variants). Mainline do not work as well. Video at the begining also do not render.

Vulkan also have problems (https://github.com/yuzu-emu/yuzu/issues/6604)

Game: 0100A250097F0000 | DRAGON BALL FighterZ (64-bit) | 01.27

Host CPU: AMD Ryzen 5 3600 6-Core Processor | AVX2 | FMA
Host OS: Windows 10 (10.0)
Host RAM: 15.93 GB
Host Swap: 19.53 GB
Driver: NVIDIA 466.77.0.0
Device: NVIDIA GeForce GTX 670
Vulkan: 1.2.168

Dock or Undock mode, same results as show below:

OpenGL GLSL High:
ball_ogl_high_glsl

OpenGL GLSL Normal:
ball_ogl_normal_glsl

OpenGL GLASM High:
ball_ogl_high_glasm

OpenGL GLASM Normal:
ball_ogl_normal_glasm

### PR DESCRIPTION
**Pull request by ameerj**
We were previously using PBOs to streamline the BGR565 texture copies, and compute shaders to swizzle each individual pixel for the BGRA8 formats. This change unifies all BGR related copies to use a PBO, which was shown to benefit performance especially on lower powered devices.

This change is also made in anticipation of resolution scaling, where the number of pixels in upscaled textures can easily grow to saturate the number of compute threads on a device for a simple BGR swizzle copy. PBO operations instead are asynchronous DMA operations which are expected be much cheaper for these cases.

Closes #6492 and closes #6625

### CODE REVIEW

**Comment by codbugpatrol** [comment]
fixes https://github.com/yuzu-emu/yuzu/issues/6625

**Comment by codbugpatrol** [comment]
image
image
@ameerj , just a question. This PR fixes the #6625. But while in game, the only problem that I notice is that the background of the character selection screen and battle load, don't render the background. Is this releated to this issue or maybe it is something else ? Works on Vulkan.

**Comment by ameerj** [comment]
@codbugpatrol can you test this game on [mainline 557](https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-557)? This was the last mainline version before the initial BGR fixes were merged. It will tell us if the background bug you see is related to these changes.

**Comment by codbugpatrol** [comment]
@ameerj, background works, but chars are blue,lol. But the backgroud works. So, it this PR fixes most of the issues, but not all, right ? Maybe some little tweak in it would make this perfect. 

image
image
image

but also, with this 557, the game is blue sometimes:

image
image

**Comment by codbugpatrol** [comment]
I dont know much of BGR, but in mainline 558, you have add a blacklist to BGRA8 copies ? Maybe this is the problem ?
At least we know this is related to BGR.

**Comment by codbugpatrol** [comment]
@ameerj do you think that this issue(background), might get fixed in this PR still ?

**Comment by ameerj** [comment]
> 
> 
> @ameerj do you think that this issue(background), might get fixed in this PR still ?

@codbugpatrol I am not able to reproduce the bug at the moment. Please open an issue with logs and your configuration so we can better track this specific bug.

**Comment by codbugpatrol** [comment]
@ameerj , ok, that sad to hear. But here some more updates regarding this issue:

Tested the game with undocked mode, and the flickering started. 
The error seems to be that it is holding the frame that happens before entering the char selection screen.

image
image
image

AND UPDATING the behavior on docked mode, it flickers from this red to the correct backgroud, but it is fast, hard to get the picture.
image
image

No errros on the log.

**Review by bunnei — APPROVED** [review]

**Pull request merged**
