### PR TITLE
Query Cache: Fix memory leak.

### PR DESCRIPTION
**Pull request by FernandoS27**
Fixes the memory leaks caused by the new query cache

### CODE REVIEW

**Comment by FernandoS27** [comment]
Fixes https://github.com/yuzu-emu/yuzu/issues/11640 https://github.com/yuzu-emu/yuzu/issues/11617

**Comment by Squall-Leonhart** [comment]
Love the branch name lol, does this need checking on nvidia?

**Review by liamwhite — APPROVED** [review]

**Comment by goldenx86** [comment]
There are reports of crashes in Pokémon games even with this fix.

**Comment by liamwhite** [comment]
Then get someone with the issue to file a separate report.

**Pull request merged**
