### PR TITLE
vk_rasterizer: flip scissor y on lower left origin mode

### PR DESCRIPTION
**Pull request by liamwhite**
Fixes cut off rendering in handheld mode on Tomb Raider I-III Remastered. Oversight of #12235

### CODE REVIEW

**Comment by liamwhite** [comment]
Identified to break Gargoyles Remastered

**Comment by FireBurn** [comment]
This doesn't fix playing at "2x" resolution

**Comment by liamwhite** [comment]
2x in what game?  I tested scaling on this branch and it works...

**Comment by FireBurn** [comment]
> 2x in what game? I tested scaling on this branch and it works...

Sorry Tomb Raider Remastered

**Comment by liamwhite** [comment]
I don't know what to tell you other than "works for me"
Screenshot from 2024-02-26 20-44-16

**Comment by FireBurn** [comment]
I'll play around with it more tomorrow, now I'm just seeing the sky box when I play TR1's house level - RADV on Linux here

**Comment by liamwhite** [comment]
Yes it's broken on radv because they don't support D24 and this breaks the scaler a little bit

**Review by FearlessTobi — APPROVED** [review]

**Pull request merged**
