### PR TITLE
gl_shader_decompiler: Implement gl_ViewportIndex and gl_Layer in vertex shaders

### PR DESCRIPTION
**Pull request by ReinUsesLisp**
This commit implements gl_ViewportIndex and gl_Layer in vertex and geometry shaders. In the case it's used in a vertex shader, it requires ARB_shader_viewport_layer_array. This extension is available on AMD and Nvidia devices (mesa and proprietary drivers), but not available on Intel on any platform. At the moment of writing this description I don't know if this is a hardware limitation or a driver limitation.

In the case that ARB_shader_viewport_layer_array is not available, writes to these registers on a vertex shader are ignored, with the appropriate logging.

### CODE REVIEW

**Comment by FernandoS27** [comment]
It seems to cause a regression in AMD cap kingdom. It should be checked.

**Comment by Hexagon12** [comment]
Causes a regression with Smash Ultimate - no 3D rendering with a GTX 750 Ti

**Comment by fluffapparition** [comment]
Considering that this causes regression on AMD and NVidia devices it might be smart to either add an option for the user to select a method appropriate for their device or to automatically use one of the two methods based on the graphics device being used. Otherwise, we could do that and allow the user to switch to another if the one selected isnt working, just incase. 

Unless we find a fix for this on all devices, this is what I think would be reasonable

**Comment by ReinUsesLisp** [comment]
> 
> 
> Considering that this causes regression on AMD and NVidia devices it might be smart to either add an option for the user to select a method appropriate for their device or to automatically use one of the two methods based on the graphics device being used. Otherwise, we could do that and allow the user to switch to another if the one selected isnt working, just incase.
> 
> Unless we find a fix for this on all devices, this is what I think would be reasonable

There's no need to do that, a device that's not able to write gl_ViewportIndex and gl_Layer from a vertex shader currently doesn't use it.

I'm currently investigating what causes the regression, but it's likely that it's a bug somewhere else in the code that just got revealed by using different viewports.

**Comment by ReinUsesLisp** [comment]
It should be fixed now, it wasn't that in the end.

We'll still need to enable multiple viewports when geometry shaders are disabled to render properly on games that use `gl_ViewportIndex` (like SSBU).

**Pull request merged**
