### PR TITLE
Change Discord badge color.

### PR DESCRIPTION
**Pull request by MichaelHinrichs**
Use the official Discord logo's color value of 5662F6.

### CODE REVIEW

**Comment by FearlessTobi** [comment]
Can you link a resource where this color is coming from?

**Comment by MichaelHinrichs** [comment]
I used msPaint's eyedrop color-picker tool on the Discord app icon.
DiscordLogoMSPaint

**Comment by BreadFish64** [comment]
> I used msPaint's eyedrop color-picker tool on the Discord app icon.

There might be a color space conversion or rendering difference in the version of the logo you're using.
https://discord.com/branding
According to Discord, "Blurple" is officially `#5865F2`, and that's what I'm getting from the logo.
image

**Comment by MichaelHinrichs** [comment]
Crap.

**Pull request closed without merging**
