### PR TITLE
config: Make debug and input pages scrollable

### PR DESCRIPTION
**Pull request by yzct12345**
The debug and input pages are squeezed on my laptop screen. Others agrees, such as in number 1 of #6710. This PR makes the config easier to use for those who don't have a larger monitor.

### CODE REVIEW

**Comment by Morph1984** [comment]
Could you screenshot what the contrroller input dialog now looks like? Making it a scroll area may not make it look as nice.

**Comment by yzct12345** [comment]
Here are the screenshots:

yuzu1
yuzu2
yuzu3
yuzu4

**Comment by Morph1984** [comment]
I see, on linux the element sizes are different

**Comment by v1993** [comment]
Not that it's specifically on Linux, those are just different Qt themes.

**Comment by bunnei** [comment]
@yzct12345 Can you rebase this? Thank you!

**Pull request closed without merging**
