### PR TITLE
Vulkan: Fix regression caused by limiting render area to width/height of render targets.

### PR DESCRIPTION
**Pull request by FernandoS27**
Fixes bayonetta 3's white screen on Vulkan.

### CODE REVIEW

**Comment by Bjorn29512** [comment]
Should close #9144  on merge

**Comment by bunnei** [comment]
Fixes #9144

**Review by bunnei — APPROVED** [review]

**Comment by Kotastros** [comment]
How to apply this fix?

**Comment by v1993** [comment]
It's already in mainline yuzu. Please make sure you're using the latest yuzu version and refer to yuzu discord for further support.

**Pull request merged**
