### PR TITLE
[WIP] Some SSBU fixes

### PR DESCRIPTION
**Pull request by BaronKiko**
DO NOT MERGE
This PR doesn't make smash boot, it does give some progress.
This PR isn't meant to be merged, it's meant to be a collection of changes required for smash however they may not be optimal changes. It is also a child of https://github.com/yuzu-emu/yuzu/pull/1698 which is being re-implemented.
At it's current state it should get into an infinite loop, still unknown why.

### CODE REVIEW

**Comment by BaronKiko** [comment]
I have no idea if the sleep change is hardware accurate as I honestly don't have any idea how you would test that nor do I have my switch setup for dev. I simply noticed it got stuck there waiting for int32 max nanoseconds.
I don't think the loop is caused by the parent pr, I think it's a different loop later on. I left it for over 10 mins yesterday and it never progressed. 
I only included the other pr because it's required to test this pr and is consequently the source of my branch. The other mii pr isn't included for a similar reason. I never really intended it to be merged at this point, Once it's showing more progress I will split it up into all the required parts. Till then, as it says, do not merge.

**Comment by BaronKiko** [comment]
> Just going to point out that MapPhysicalMem is implemented wrong

I'm aware but it's the best I have until it has been re-implemented. It's working for what I need here so I'm not exactly sure how it's broken, not that's it's really relevant to me or this pr.

**Comment by Hexagon12** [comment]
@BaronKiko Will you still continue on getting this PR in a mergeable state? If yes, please rebase it.

**Comment by BaronKiko** [comment]
I got distracted. I believe the time less than 0 change was already implemented on the mii pr(?) and the other change is just a stub so I will just close it.

**Pull request closed without merging**
