### PR TITLE
Rename Normal GPU accuracy to Low

### PR DESCRIPTION
**Pull request by goldenx86**
Seems way more appropriate, especially considering the accuracy cost "low" has.

### CODE REVIEW

**Comment by goldenx86** [comment]
Thanks @v1993

**Comment by FernandoS27** [comment]
I'll be changing the system soon. So this may end up being useless.

**Comment by FearlessTobi** [comment]
From what I've seen, there's a lot confusion with users regarding this setting either way.
Especially in the lower bar where it is just named "GPU Normal" or "GPU High" it is not clear that this setting is related to accuracy in any way.

**Comment by bunnei** [comment]
Probably worth just waiting for @FernandoS27, but I would love to see Normal/High go away (to just an accurate default), with anything normally unnecessary behind an advanced setting

**Comment by user18081972** [comment]
I will only approve of this change if instead of Low we name it Scuffed

**Comment by liamwhite** [comment]
Normal got a huge buff in #10084 so I don't think this is relevant anymore.

**Pull request closed without merging**
