### PR TITLE
settings: Add anisotropic filtering level to the yuzu configuration log

### PR DESCRIPTION
**Pull request by Morph1984**
```
Default = 0,
2x = 1,
4x = 2,
8x = 3,
16x = 4,
```

### CODE REVIEW

**Comment by lioncash** [comment]
Commit title should be amended to be more specific

**Comment by goldenx86** [comment]
This would help a lot when giving support.

**Comment by callmenemo491** [comment]
@Morph1984 , i think something similar could be done to include in the yuzu.log the amount of RAM the person has...

**Comment by Fneufneu** [comment]
Why keep this obscur ?
can you make some #define that convert 0 1 2 3 4 to a human reading setting: Default , 2x ....

**Comment by ogniK5377** [comment]
> @Morph1984 , i think something similar could be done to include in the yuzu.log the amount of RAM the person has...

Unrelated to this pull request

**Pull request merged**
