### PR TITLE
nce: implement instruction emulation for misaligned memory accesses

### PR DESCRIPTION
**Pull request by liamwhite**
This allows Paper Mario: The Origami King to go in game with NCE. This is the most outsized effort I think I have ever made to fix a single game, with an almost 4000 line delta. The game doesn't even render correctly anyway, so it almost feels not worth the effort.

image

Marked as draft due to conflicts with #12236, which should be merged first.

### CODE REVIEW

**Comment by v1993** [comment]
> This would be the method to follow for other games like Dragon Ball Z Kakarot or Dragon Quest Infinity Strash that crash at the beginning? Basically what happens to them is that they start up but then the fps goes to 0...Is there no way to make this bug fixed...it's a common bug to many games..... Thank you.

What you're describing is a symptom of various different issues that happen to manifest in the same way, i.e. game-side crash. There's no *single* fix to all of them.

**Comment by liamwhite** [comment]
@Raistlin43 there are no existing github issues matching the problems with the games you described. How can we fix a problem that we do not have any information about?

**Comment by Raistlin43** [comment]
> @Raistlin43 there are no existing github issues matching the problems with the games you described. How can we fix a problem that we do not have any information about?

You are right I thought you were aware of that bug. The problem is that when activating NCE many games start but then after starting the fps go to 0. Here is an example of Dbz Kakarot and the txt file of the error, thanks.

[Yuzu_log1.txt](https://github.com/yuzu-emu/yuzu/files/13518136/Yuzu_log1.txt)


https://youtu.be/vm7d50l1IV8?si=mz4wVMB6hnqJnrrL

**Comment by Raistlin43** [comment]
> @Raistlin43 there are no existing github issues matching the problems with the games you described. How can we fix a problem that we do not have any information about?

Here's another very similar problem in Dragon Quest Infinity Strash... The game starts in NCE and then the fps goes to 0... It happens in many games... I leave the video and the txt error ... Thanks. 

[Yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13518152/Yuzu_log.txt)

https://youtu.be/n6piL45Bx2o?si=hI_yxSGWrFEMUD7S

**Comment by liamwhite** [comment]
Attached log shows a game crash due to running out of mappings ("fastmem issue"). If you have a rooted device you can work around this by increasing the allowable map count like this:
```
sunfish:/ # echo 524288 > /proc/sys/vm/max_map_count                                                                                                                                                                                         
```

**Comment by Raistlin43** [comment]
> > Attached log shows a game crash due to running out of mappings ("fastmem issue"). If you have a rooted device you can work around this by increasing the allowable map count like this:
> > ```
> > sunfish:/ # echo 524288 > /proc/sys/vm/max_map_count
> > ```
> 
> Screenshot_20231130-234914_yuzu Screenshot_20231130-235420
> 
> Now I can play DBZ Kakarot AND demon slayer a full speed. Thanks

Hopefully they can fix it with an emulator update.... Without the need to rotate the terminal... It would solve a lot of crashes in games with NCE... Thanks for your contribution

**Comment by brujo5** [comment]
> > > Attached log shows a game crash due to running out of mappings ("fastmem issue"). If you have a rooted device you can work around this by increasing the allowable map count like this:
> > > ```
> > > sunfish:/ # echo 524288 > /proc/sys/vm/max_map_count
> > > ```
> > 
> > 
> > Screenshot_20231130-234914_yuzu Screenshot_20231130-235420
> > Now I can play DBZ Kakarot AND demon slayer a full speed. Thanks
> 
> Hopefully they can fix it with an emulator update.... Without the need to rotate the terminal... It would solve a lot of crashes in games with NCE... Thanks for your contribution

Screenshot_20231201-004323_lybKernelManager

**Review by Kelebek1 — APPROVED** [review]

**Pull request merged**
