### PR TITLE
FSR Sharpening Slider

### PR DESCRIPTION
**Pull request by goldenx86**
Simply a sharpening slider for FSR.
Lacks support for per-game settings, Qt is scary.

### CODE REVIEW

**Comment by goldenx86** [comment]
01007ef00011e000_2022-11-19_21-29-38-027
01007ef00011e000_2022-11-19_21-29-49-916

**Comment by goldenx86** [comment]
Added a percentage label for ease of use.
Still fighting Qt.

**Comment by goldenx86** [comment]
Thank you @lat9nq for implementing per-game settings.

**Review by bunnei — APPROVED** [review]

**Comment by notimp** [comment]
@goldenx86 did you change the default value for sharpening yuzu had active  before your slider implementation? if so from what to what value. If not please confirm. Thank you. 

OCD, and something I need not know. :)

**Pull request merged**
