### PR TITLE
externals: update libzip to pick up zlib fix

### PR DESCRIPTION
**Pull request by jbeich**
Fixes https://github.com/yuzu-emu/yuzu/issues/2544
Fixes https://github.com/yuzu-emu/yuzu/issues/2946
Depends on https://github.com/DarkLordZach/libzip/pull/1

### CODE REVIEW

**Comment by ReaperOfSouls1909** [comment]
image
fix is needed mingw is broken

**Comment by jbeich** [comment]
@ReaperOfSouls1909, can you try again? If it still fails I don't know how to fix it. ;(

**Comment by ReaperOfSouls1909** [comment]
i was just backing you up about the fix but yes it does work

**Comment by jbeich** [comment]
Obsolete after #3045

**Pull request closed without merging**
