### PR TITLE
renderer_vulkan: Implement MSAA image copies

### PR DESCRIPTION
**Pull request by GPUCode**
Implementation of https://github.com/yuzu-emu/yuzu/pull/9746 for vulkan for the image copy part. I didn't implement uploads because I couldn't find much information about the layout of MSAA images and games I tested do not upload anything meaningful anyway. Fixes graphics in Sonic Forces as mentioned in the PR and also in Mortal Kombat 1

yuzu (master) | yuzu (PR)
-|-
master | pr

### CODE REVIEW

**Comment by Kelebek1** [comment]
Can this not be done with vkCmdResolveImage instead of a whole compute shader?

**Comment by GPUCode** [comment]
From my understanding MSAA copies are about preserving all the original samples. So a 672x378 MSAA 4x image will copy to 1344x756 normal image while it resolves to a 672x378 normal image

**Comment by pacoa-kdbg** [comment]
Mali still not able to boot MK1 with the artifact of this PR.
Probably related to something completely different, but leaving this here in case anyone wants to take a look 


[MK_1.log](https://github.com/yuzu-emu/yuzu/files/12690075/MK_1.log)

**Comment by Squall-Leonhart** [comment]
Partially fixes Pinball FX3

image

**Comment by GPUCode** [comment]
Also fixes Fate Extella menu. Screenshot by @gidoly
yuzu-msvc-verify-pr11556-20230921-9c1840023_WaFMRVijZM

**Comment by GPUCode** [comment]
@Squall-Leonhart How did the game look without this PR

**Comment by Squall-Leonhart** [comment]
> @Squall-Leonhart How did the game look without this PR

The Table itself didn't render, but the LCD on some of the tables would animate, the woman and her speech bubbles would appear with nothing behind her

The Main menu would be black, now it draws but a bit glitchy

image

**Comment by GPUCode** [comment]
Hm does it work on OpenGL? I think that has msaa uploads.

**Comment by Squall-Leonhart** [comment]
oh, good call, the same lines are there in opengl so guess its not what i thought it was.

**Comment by GPUCode** [comment]
Latest commit should fix Pinball glitches @Squall-Leonhart

**Comment by Squall-Leonhart** [comment]
Perfect!

image
image

**Review by liamwhite — APPROVED** [review]

**Review by FernandoS27 — APPROVED** [review]

**Comment by benderscruffy** [comment]
@Squall-Leonhart 
can you get Medievel Madness to load up 
it is stuck on the loading screen for myself

**Comment by Squall-Leonhart** [comment]
That table requires a more thorough implementation of IFriendService

**Comment by benderscruffy** [comment]
It used to work so wondering what has changed with it

**Comment by Squall-Leonhart** [comment]
It has always had the same crash that Ryujinx has

```
   0x000000000972c4a8	sdk:0x444a8	nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, nn::Result const*, nn::os::UserExceptionInfo const*, char const*, ...)
   0x000000000972c560	sdk:0x44560	nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, char const*, ...)
   0x000000000972c5f0	sdk:0x445f0	nn::diag::detail::OnAssertionFailure(nn::diag::AssertionType, char const*, char const*, char const*, int, char const*, ...)
```

```
[3861.956301] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 00000071000B15D8    00000000817995D8    00000000000B15D8    
[3861.956310] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 00000071000456DC    000000008172D6DC    00000000000456DC    nn::diag::detail::Abort()
[3861.956312] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 00000071000444A8    000000008172C4A8    00000000000444A8    nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, nn::Result const*, nn::os::UserExceptionInfo const*, char const*, ...)
[3861.956315] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 0000007100044560    000000008172C560    0000000000044560    nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, char const*, ...)
[3861.956317] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:144: sdk                 00000071000445F0    000000008172C5F0    00000000000445F0    nn::diag::detail::OnAssertionFailure(nn::diag::AssertionType, char const*, char const*, char const*, int, char const*, ...)
```

**Pull request merged**
