### PR TITLE
vk_device: Block VK_EXT_extended_dynamic_state for RDNA devices

### PR DESCRIPTION
**Pull request by goldenx86**
RDNA devices seem to crash when using VK_EXT_extended_dynamic_state in
the latest 20.9.2 proprietary Windows drivers. As a workaround, for now
we block device names corresponding to current RDNA released products.

### CODE REVIEW

**Comment by goldenx86** [comment]
This was all done by ReinUsesLisp.

**Comment by Wunkolo** [comment]
I think it might be better to use the `deviceID` property of [VkPhysicalDeviceProperties](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPhysicalDeviceProperties.html) than the current string-comparison method.

Sites like [this](https://pci-ids.ucw.cz/read/PC/1002) can help identify these devices as well. Next time there's a special-case set of cards or architectures that has to be handled differently(`"blah-blah is broken on blah-blah, so we disable it"`), the `deviceID` might be a more stable metric of detecting certain cards and architectures across platforms and operating systems rather than however a driver decides to name the device in Vulkan(Linux AMD drivers will name their devices `AMD RADV RAVEN (LLVM 10.0.1)` for instance).

deviceID| GPU
-- | --
7310 | Navi 10 [Radeon Pro W5700X]
7312 | Navi 10 [Radeon Pro W5700]
731f | Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
7340 | Navi 14 [Radeon RX 5500/5500M / Pro 5500M]
7341 | Navi 14 [Radeon Pro W5500]
7347 | Navi 14 [Radeon Pro W5500M]
734f | Navi 14 [Radeon Pro W5300M]
7360 | Navi 12 [Radeon Pro 5600M]

**Comment by goldenx86** [comment]
We considered it, but the list becomes too extensive, and we are already limiting the scope of this to only the Windows driver.
Besides, this will most likely just be temporal, the 20.9.2 driver fixed this extension for all AMD archs besides Navi, one would expect that the next release or so will finally fix it for RDNA1.

**Review by Morph1984 — APPROVED** [review]

**Review by bunnei — APPROVED** [review]

**Comment by hurricane-dorian** [comment]
Yuzu no longer crashes with VK_EXT_extended_dynamic_state  enabled in driver version 20.11.1
Tested on a RX5600
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5541900/yuzu_log.txt)

**Pull request merged**
