### PR TITLE
Format .gitmodules, Replace Inih, and Apply XCode Update + Clang Format Fixes

### PR DESCRIPTION
**Pull request by CDAGaming**
**Direct Port of the PR on Citra-Emu**

(Ready to Merge)

### CODE REVIEW

**Comment by j-selby** [comment]
Why are these updates necessary? What do they achieve? I'm not sure what you are trying to do here....

**Comment by CDAGaming** [comment]
The inih is to migrate to a more active repo which is better supported (And has already been applied to Citra). The XCode Update is to fix a few warnings that would/could come up in travis Builds.

**Comment by indrajithbandara** [comment]
ok

**Comment by CDAGaming** [comment]
Updated PR to Include Clang Format Fixes. Don't Merge however until later today, as I'll be Updating Catch to v2 like it is on Citra.

**Comment by Hexagon12** [comment]
Please fix the conflicts.

**Comment by CDAGaming** [comment]
Will Rebase and Apply Ubuntu Update hopefully by tonight :)

**Comment by Hexagon12** [comment]
What's the status of this PR?

**Comment by CDAGaming** [comment]
Been taking a break from this. I can rebase this tonight.

**Comment by LogPod** [comment]
When will that night come? 😂

**Comment by CDAGaming** [comment]
Probably this weekend now, as some personal issues have come up a bit lately.

**Comment by mailwl** [comment]
his is fix https://github.com/yuzu-emu/yuzu/issues/172 ?

**Comment by CDAGaming** [comment]
I would have to test to see if that Issue is fixed this weekend.

**Comment by mailwl** [comment]
Happy "День защитника Отечества 2018"

**Comment by bunnei** [comment]
Closing since there has been no update here for a while.

**Comment by CDAGaming** [comment]
When I have some time available, I'll recreate this. (I have exams this week but afterwords, I shouldn't have any reason not to be able to do this) :D

**Pull request closed without merging**
