### PR TITLE
Update httplib to 0.5.5

### PR DESCRIPTION
**Pull request by brianclinkenbeard**
Some linux users (#3048) report segfaults using the mainline builds that seem to trace back to older versions of httplib being [incompatible with OpenSSL 1.1](https://github.com/yhirose/cpp-httplib/pull/243). For me, this only occurred on the provided binaries and not on built images, so without a DevOps build, I can't confirm that this fixes the issue.

It's worth noting the latest version of cpp-httplib is 0.5.5, however v0.5 introduces breaking changes that prevented yuzu from building. Anyone more familiar is obviously welcome to rectify the code that uses httplib to work with they latest version if they want.

### CODE REVIEW

**Comment by brianclinkenbeard** [comment]
Testing the artifacts, it looks like this doesn't solve the issue so I will do some more digging.

**Comment by bunnei** [comment]
@brianclinkenbeard does the update to 0.5.5 resolve this issue?

**Comment by brianclinkenbeard** [comment]
@bunnei Sadly no. The issue is probably with glibc. You can close this or merge it if you want, the latest version should offer greater compatibility and might fix some bugs.

**Comment by bunnei** [comment]
Hitting CI errors with this: https://gist.github.com/bunnei/9c09b2853e8a3b5c7c66777d496192ca

Do you mind taking a look? Thanks!

**Comment by brianclinkenbeard** [comment]
Does this work?

**Comment by bunnei** [comment]
Looks good -- thanks!

**Pull request merged**
