### PR TITLE
nce: fix read size in simd immediate emulation

### LINKED ISSUE #12347: Paper Mario The Origami King - some issues
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android v159

### Description of Issue

The game looks perfect in the menu but then some textures turn black and after the cinematic the FPS drops to 0 and it doesn't go from there.
Yuzu
Screenshot_20231212-214100_yuzu
Screenshot_20231212-214214

For reference, the game works perfectly on another emulator with Qualcomm and Turnip driver.
Screenshot_20231212-215245_Egg_NS_Emulador
Screenshot_20231212-215157

### Expected Behavior

that shouldn't happen

### Reproduction Steps

Justo play normally

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13656328/yuzu_log.txt)

### System Configuration

CPU:sd870
GPU/Driver:Adreno 650/turnip/Qualcomm drivers 
RAM:8gb
OS: android 13

### PR DESCRIPTION
**Pull request by liamwhite**
Fixes #12347

### CODE REVIEW

**Comment by ThepuncheXD7** [comment]
Great this should fix no man's sky too

**Review by FernandoS27 — APPROVED** [review]

**Comment by brujo5** [comment]
I don't know why they closed my thread if I haven't confirmed anything

According to this, it solves the problem of getting stuck after the intro with FPS at 0. I tried v167 and it's still the same

Screenshot_20231220-184233
Screenshot_20231220-183834

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/13734189/yuzu_log.txt.old.txt)

**Comment by brujo5** [comment]
It works with dynarmic but it is unplayable since the FPS drops massively when entering the castle.  The strange thing is that the fix says NCE but it doesn't work

Screenshot_20231220-203352

**Comment by Slexer** [comment]
The FPS drop with Turnip drivers but are stable with system default drivers. Just use default drivers. 

The NCE problem still remains. FPS drops to 0 after the first cutscene.

**Pull request merged**
