### PR TITLE
Garbage Collection: enable as default, eliminate option.

### PR DESCRIPTION
**Pull request by FernandoS27**
Thanks to @K0bin the graphic corruption in SMO was fixed. Therefore, it's completely safe to have garbage collection always active.

This PRR eliminates the option and makes GC always be activated.

### CODE REVIEW

**Comment by yzct12345** [comment]
I had some crashes a while ago while working on #6713. Link's Awakening crashed during the intro movie only when garbage collection was on. Are those fixed too?

**Comment by FernandoS27** [comment]
> I had some crashes a while ago while working on #6713. Link's Awakening crashed during the intro movie only when garbage collection was on. Are those fixed too?

uhm that shouldn't happen. I was not aware of that one.

**Comment by jacky400** [comment]
Less option is good . Wonder do we still need the option of use NVDEC emulation unless there are some games that broken wthout this option .

**Comment by v1993** [comment]
> Less option is good .

Hard disagree (by me, anyways). Less options that you never actually need to change is good for sure.

> Wonder do we still need the option of "Use NVDEC emulation" unless there are some games that broken wthout this option .

There are still some games having issues with it enabled: #6525 (see comments).

**Comment by jacky400** [comment]
I see. Just tested Mario Golf again and the in-game movie background playback is broken .

**Comment by FernandoS27** [comment]
I've disabled this in the meantime. I'll investigate current issues

**Comment by v1993** [comment]
This should be closed as option is gone with #6897 anyways.

**Pull request closed without merging**
