### PR TITLE
Texture Cache: Fix untracking on GPU remap

### PR DESCRIPTION
**Pull request by FernandoS27**
This fixes some 0 fps bugs in NCE Unreal games and likely some other engines.

### CODE REVIEW

**Review by liamwhite — APPROVED** [review]

**Comment by Eiklaps** [comment]
Batman Arkham City & Asylum getting 0 fps bug on latest Android 254 GitHub version. The games are working fine I think in the Android 220 to 227 version.

**Comment by liamwhite** [comment]
Find the exact version that regressed it

**Comment by Eiklaps** [comment]
I checked the Batman Arkham City & asylum are working fine in Android 243 GitHub version but in Android 244 GitHub version & up versions are giving 0 fps bug.

**Comment by liamwhite** [comment]
Those versions don't appear to have anything to do with this pull request.

**Comment by liamwhite** [comment]
In fact there is no change between the sources in 243 and 244 except this, which has nothing to do with the game:
```diff
--- a/src/core/memory/cheat_engine.cpp
+++ b/src/core/memory/cheat_engine.cpp
@@ -65,8 +65,7 @@ void StandardVmCallbacks::MemoryWriteUnsafe(VAddr address, const void* data, u64
         return;
     }
 
-    if (system.ApplicationMemory().WriteBlock(address, data, size) &&
-        system.ApplicationProcess()->Is64Bit()) {
+    if (system.ApplicationMemory().WriteBlock(address, data, size)) {
         Core::InvalidateInstructionCacheRange(system.ApplicationProcess(), address, size);
     }
 }
```
The issue cannot be new in 244. It must be older.

**Pull request merged**
