### PR TITLE
Added 'Hide empty rooms' toggle to lobby

### PR DESCRIPTION
**Pull request by unfamiliarplace**
Same as the full rooms toggle, but hides rooms with no other players, in case you want to jump in where people already are. There are a lot of 0/ rooms at some times of day.

### CODE REVIEW

**Comment by german77** [comment]
Fix clang format please. So we can run CI

**Comment by unfamiliarplace** [comment]
Have not run clang-format in VSCode before. I think it's good now.

**Comment by german77** [comment]
Looks good to me. Please squash the commits into a single one then we can merge it.

**Comment by unfamiliarplace** [comment]
Not sure how to do so on my end -- I thought that was done by the merger (from [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits)). Sorry! Will research and do it on my end if needed.

**Comment by german77** [comment]
git rebase -i origin/master
then edit the text file to squash all the commits that arent the first one. After that just force push to this PR.

If it's too difficult I can do it as well

**Comment by unfamiliarplace** [comment]
OK, I think it's done

**Comment by german77** [comment]
I didn't noticed you didn't made a branch so the command didn't work as intended. I squashed the PR. Should be good now.

**Comment by unfamiliarplace** [comment]
Ahh gotcha. I was wondering what I was rebasing to. :) Thanks for the help!

**Review by german77 — APPROVED** [review]

**Comment by german77** [comment]
You used master to make this PR. My bad I didn't noticed that earlier. I squashed your PR it Should be good now.

Next time consider making a branch for every PR. Makes easier maintaining them up to date and doing rebases.

**Review by lioncash — APPROVED** [review]

**Comment by goldenx86** [comment]
Hi, can I mention your work in the next progress report?

**Comment by unfamiliarplace** [comment]
Yes indeed. Ty

**Pull request merged**
