### PR TITLE
Project Andio

### PR DESCRIPTION
**Pull request by Kelebek1**
# Project Andio 
##### (Thanks @lat9nq for the name)

This PR is a complete replacement for the Yuzu's current audio systems. It aims to improve current audio playback through:
* Implementing missing features (such as audio effects).
* Updating the audio system to a newer revision, allowing newer games to be playable. Firmware 13.0.0 is used as the base.
* Aligning the code structure more closely to Nintendo's, to make it easier for others to update from future RE (though in some areas this went full jank).

The documentation leaves a lot to be desired, but felt adding it was better than not.

Audio input is now supported (though not very tested), allowing the Let's Sing games to be playable.

#### Regressions/Persistent issues
* Super Mario Odyssey. 
Same issue exists in master currently, but some users may experience it worse than before, many won't. SDL output can help somewhat if you experience glitchy playback with SMO. It's caused by the Aux command, and is to do with the audio renderer and game not updating exactly in sync, it's very timing-sensitive. If anyone wants to look into improving audio, this is definitely a good place, how the audio renderer signals and sleeps, interaction with the backend stream, and the interaction with Aux.

#### Not-fixed issues
* Skyward Sword HD intro cutscene. 
Looked at this for a while, can't find a way to fix this one. The game submits audio data far too slowly so it continually runs out of data. Another thing to look at if anyone wants to.

Closes:
#8526
#8345
#8278
#7972
#7902
#7893
#7872
#7645
#7585
#7473
#7457
#6737
#6066
#4885
#3751
#1952

Hopefully fixed, needs testing:
#8498
#8187
#8001
#7912
#7584
#7442
#2749

Not compatible with #7346

Thanks to all the dev team and testers for helping me with this.
@FernandoS27 for finding multiple bugs I was stuck on trying to fix, and encouraging me
@gidoly for testing so much he ended up in hospital
@G-Spawn also testing a lot of games and finding me new ~~problems~~ things to fix
@liamwhite for helping answer a lot of questions, and building on linux
@lioncash for reviewing this mess
@sciresm for answering a bunch of questions I had about the switch
@Dragorn421 for helping with the compressor effect
And everyone else I forgot to tag. :)

### CODE REVIEW

**Comment by RinMaru** [comment]
This PR break Subnautica audio

**Comment by lat9nq** [comment]
This PR causes a regression in Splatoon 2. Audio is noticeably delayed. The effect after leaving the splash screen was warbled.

https://user-images.githubusercontent.com/22451773/178022005-1ee3fd32-f651-4e2e-8638-758ceaa3b69d.mp4

In addition, selecting the `sdl` audio backend in the Audio configuration causes the application to crash.
[gdb.txt](https://github.com/yuzu-emu/yuzu/files/9073215/gdb.txt)

**Comment by RinMaru** [comment]
Xenoblade Chronicles 2 has Audio Delay with this PR

**Comment by DelghLay** [comment]
The Legend of Zelda: Skyward Sword HD and Fire Emblem: Three Houses has audio delay as well

**Comment by Kelebek1** [comment]
@RinMaru @lat9nq @DelghLay please re-test with the newest EA.

**Comment by RinMaru** [comment]
> @RinMaru @lat9nq @DelghLay please re-test with the newest EA.

All is working now

**Comment by lat9nq** [comment]
https://github.com/yuzu-emu/yuzu/pull/8545#issuecomment-1179115100
This has been resolved.

**Comment by german77** [comment]
Closes #3751

**Review by liamwhite — APPROVED** [review]

**Pull request merged**
