### PR TITLE
yeah it's not really worth it anymore

### PR DESCRIPTION
**Pull request by typecasto**
just give up at this point lol

### CODE REVIEW

**Comment by typecasto** [comment]
oh yeah let me take care of that cla, 1 sec

**Comment by typecasto** [comment]
there we go, sorry about that

**Comment by Ecks1337** [comment]
lgtm! great feature, do you have a patreon? i'd love to support your work!

**Comment by typecasto** [comment]
@Ecks1337 i actually do! [here](https://www.youtube.com/watch?v=dQw4w9WgXcQ)'s the link, thanks so much!

**Pull request closed without merging**
