### PR TITLE
Implement stub for IApplicationFunctions::QueryApplicationPlayStatisticsByUid

### PR DESCRIPTION
**Pull request by SciresM**
Needed to boot some newer games (SDK >= ~7.x).

### CODE REVIEW

**Comment by FernandoS27** [comment]
hmn, is this stubbed or it's just a boolean service?

**Comment by SciresM** [comment]
@FernandoS27 It's stubbed. The function normally writes entries to an output buffer, and returns an s32 "NumEntriesWritten".

This stub makes it return zero entries.

**Comment by SciresM** [comment]
For even more clarity: This stub is equivalent to the service telling the application that there are no historical play statistics available (i.e., this is the first boot of the application).

**Comment by lioncash** [comment]
The commit message should probably include the tidbit about it being necessary to boot games on SDK >= ~7.x, as well as the clarity comment stating what the stub is doing behaviorally.

**Comment by lioncash** [comment]
Similarly, `QueryApplicationPlayStatistics` can be stubbed along with this for implementation consistency, given it essentially performs the same behavior, with minor differences.

**Pull request merged**
