### PR TITLE
 Implement Pull #3184 from citra: core/arm: Improve timing accuracy before service calls in JIT

### PR DESCRIPTION
**Pull request by N00byKing**
NOTE: ARM_Dynarmic::PagetableChanged does pretty much nothing yet, with the exception of setting the current pagetable, which is the reason that i left "UNIMPLEMENTED()" in there.

I tested this Build on a Windows Machine with spacenx.nso, and it runs as expected (shitty). The NRO does not work at all.

### CODE REVIEW

**Comment by N00byKing** [comment]
Goddamnit every time i forget to run clang format.

Will reopen SoonTM

**Comment by N00byKing** [comment]
Ran clang-format

**Comment by MerryMage** [comment]
core.cpp: line 44: tight_loop = 1; -> tight_loop = false;

**Comment by N00byKing** [comment]
How did i miss this?

Btw, are you sure its not supposed to be tight_loop = true?

**Comment by Hexagon12** [comment]
Please fix the conflicts or close the PR if dropped.

**Comment by N00byKing** [comment]
Will do.
Re-opening once done

**Comment by N00byKing** [comment]
Moved to #193

**Pull request closed without merging**
