### PR TITLE
input_common: fix build when SDL2 is disabled

### PR DESCRIPTION
**Pull request by zhuowei**

### CODE REVIEW

**Comment by ogniK5377** [comment]
@zhuowei Can you please sign the CLA, thanks!

**Comment by callmenemo491** [comment]
@ogniK5377 , perhaps you can take what he has written and put it into a new PR, and merge it, then close this PR?

**Comment by lioncash** [comment]
@callmenemo491 That's pretty rude to do. Not cool.

I've reached out to them on Twitter.

**Comment by zhuowei** [comment]
I'm closing this PR for now. Sorry about this.

**Comment by callmenemo491** [comment]
@lioncash , looking back i agree it was not a 'smart' thing to write, i should have 110% phrased it differently... to something like this:

@zhuowei , if u dont want to sign doc,  would u allow the developers to use the PR code modifications that you came with up?
as currently you have closed the PR... so the code modification will not be in Yuzu....

**Pull request closed without merging**
