### PR TITLE
cmake: Disable PIE for performance

### PR DESCRIPTION
**Pull request by yzct12345**
This makes yuzu faster by disabling PIE. PIE is used for shared libraries and the ASLR security feature. We are an executable not a shared library and we don't need extra security because we are dumping games trusted by Nintendo. This PR also makes the addr2line debugging tool work after-the-fact without gdb.

### CODE REVIEW

**Comment by v1993** [comment]
Making `addr2line` work sounds nice, but:

1. For performance, would you mind providing some basic benchmarking results? Just to see that it does indeed make difference and how significant it is.
2. As for `addr2line`, don't core dumps allows to do the same?

**Comment by v1993** [comment]
Additionally, if you will actually measure some increase in performance, consider using CMake's mechanism for turning PIE off instead of adding flags directly. You'll also want policy CMP0083 to be set to new.

**Comment by yzct12345** [comment]
> performance, would you mind providing some basic benchmarking results

The performance improvement was less than 1 FPS. I might have seen a 33 FPS to 34 FPS average increase in the Kirby intro movie but I think it's so insignificant it's a placebo effect.

Theoretically this should improve performance and I can't see why it would decrease it.

> don't core dumps allows to do the same

This is the whole reason why I want this change. Core dumps are just like gdb as I have to remember to do `ulimit -c unlimited` before I run yuzu. The problem is yuzu only crashes when I'm enjoying something and never when I looking for bugs. The GPU cache garbage collection often crashes in the Link's Awakening intro but never when gdb is attached. Also the last time I tried to open a core dump it none of the symbols loaded probably because of PIE. I only have the line in dmesg to use and this PR removes the PIE randomization so addr2line actually works. It was showing "?:?" before.

> CMake's mechanism for turning PIE off instead of adding flags directly. You'll also want policy CMP0083 to be set to new.

I tried that already and it doesn't work.

**Comment by v1993** [comment]
I surely wouldn't expect this to lower performance, it's just that both PR title and description talk about performance increase as a main factor, so I wondered if it's actually that notable (it is not, it seems), given that no other emulators I've checked force disable/enable PIE. Also, symbol lookup in core dumps works just fine for me in "RelWithDebInfo" build type which is still built with PIE. As for core dump creation, you can avoid need for `ulimit` by editing `/etc/security/limits.conf`.

**Comment by lioncash** [comment]
> given that no other emulators I've checked force disable/enable PIE

Indeed. Given this, I'm mainly leaning toward not particularly wanting to merge this, given the perf gains seem to be negligible and the core dump creation can be mitigated.

**Comment by yzct12345** [comment]
Looks like another one to put into my set of local-only patches.

**Comment by v1993** [comment]
Actually, this does not need to be a patch if you're using it locally. You can pass flags to cmake from command line to do this.

**Pull request closed without merging**
