### PR TITLE
cmake: Take advantage of FMA support

### PR DESCRIPTION
**Pull request by yzct12345**
yuzu's hardware requirements updated to require FMA https://github.com/yuzu-emu/yuzu-emu.github.io/blob/9e5ec00ba327c46d032a8e01b599a3dd17af8a9d/site/content/help/quickstart/index.md?plain=1#L33. If we tell the compiler to use those instructions yuzu will be faster.

The flags I put will support haswell and higher and bdver3 and higher. On the AMD side the wiki requires znver1 but I set it lower because I'm working on optimizing and lowering the requirements.

This PR is inspired by https://github.com/yuzu-emu/yuzu/pull/6790#issuecomment-891210862.

### CODE REVIEW

**Comment by goldenx86** [comment]
Recent changes made FMA-less CPUs perform very well. Note that we recommend FMA support, but we don't enforce it.

**Comment by yzct12345** [comment]
What would you use instead? Supporting older CPUs prevents the compiler from even using AVX. Would sandybridge be a better target?

**Comment by yzct12345** [comment]
> apply them dynamically

I've never heard of any compiler except Intel's do that.

> Core 2 Duo and Phenom

Ok I will close this PR. I'm using march=native myself anyway.

**Comment by goldenx86** [comment]
We could consider enforcing higher requirements after Windows 10 is out of support. But for now, enforcing FMA leaves too many Sandy Bridge users out, it's incredible the amount there are.

**Comment by Moonlacer** [comment]
Sandy Bridge deserves it 👀

**Comment by yzct12345** [comment]
I actually have a very old sandybridge laptop in some box in my basement. I never ever thought yuzu would run on it.

**Comment by goldenx86** [comment]
Some optimizations to Dynarmic and fastmem made them very viable in most games. The exception being the big ones like BotW.

**Pull request closed without merging**
