### PR TITLE
Fix when the program index is greater than 0 invalid

### PR DESCRIPTION
**Pull request by vonchenplus**
This PR aims to fix error will occur when the program index is greater than 0, and I think we also need UI support to load multiple programs.

### CODE REVIEW

**Comment by german77** [comment]
Can you provide the name of a game or homebrew that hit this problem? I would like to do some testing on my side

**Comment by vonchenplus** [comment]
You can test the DQ(1, 2, 3) collection.

 Currently it can only be tested by modifying the following code:

image

**Comment by Morph1984** [comment]
@vonchenplus This is likely not the proper fix for this game. The program index is specific to multi-program titles like Super Mario 3D All-Stars, where the program index is simply an offset from a program ID.

For example:
StardustLauncher has Program ID 010049900F546000
SM64 has Program ID 010049900F546001
Sunshine has Program ID 010049900F546002
Galaxy has Program ID 010049900F546003

**Comment by vonchenplus** [comment]
@Morph1984 Yes, you are right. I checked the previous submission records, it just support for loading indexed programs. I think I need to submit another solution to support collection.

**Pull request closed without merging**
