### PR TITLE
Update dynarmic and add new unsafe CPU option.

### PR DESCRIPTION
**Pull request by FernandoS27**
This PR updates dynarmic and adds an option to loose the rounding mode on ASIMD instructions (32 bits).

### CODE REVIEW

**Comment by v1993** [comment]
I find this PR rather confusing right now. Does 32-bit refer to host architecture (ok, it does not, but end users probably won't know that)? Guest architecture? Size of values instruction operates on?

If it refers to instruction arguments, then `(32 bits only)` is only a pretty technical detail that can be omitted. If it refers to guest architecture - doesn't Yuzu lack support for 32-bit guests as for now?

P.S.: where I can get stuff you use to come up with branch names? It seems pretty good...

**Comment by MerryMage** [comment]
> Yuzu lack support for 32-bit guests as for now?

Yuzu supports 32-bit guests.

**Comment by v1993** [comment]
Ah, thanks for correcting me then. So, does this option affect only 32-bit guests? Also, are 32-bit guests common in Yuzu?

**Comment by MerryMage** [comment]
This option only affects 32-bit guests, because only 32-bit ASIMD instructions have the concept of "default FPCR", which may by different from the current FPCR. Switching rounding modes for this can be expensive.

**Comment by v1993** [comment]
Thanks a lot for explanation! I'm suggesting to go with this description then:
```
Inexact rounding for ASIMD instructions in 32-bit applications
This option improves speed of 32-bit ASIMD floating-point instructions by skipping rounding mode changes.
```

**Review by bunnei — APPROVED** [review]

**Comment by v1993** [comment]
@bunnei Uh, what do you think about my rewording suggestion? Should I send it as follow-up PR or something?

**Pull request merged**
