### PR TITLE
core: remove ResultVal type

### PR DESCRIPTION
**Pull request by liamwhite**
HLE kernel/service code should use out pointers instead.

### CODE REVIEW

**Comment by comex** [comment]
Oh, why?

I'm a big fan of result-like types including `ResultVal` and `Expected`.

My SSL PR (#10912) uses `ResultVal` extensively…

**Comment by liamwhite** [comment]
This style matches the way the kernel design works, and how official service bindings work (which we eventually want to replicate, to allow services to call each other). They don't return a sum type of Result and value--they always return Result, and write to output pointers if they have outputs.

**Comment by liamwhite** [comment]
(and it's fine that you used it; since we intend to merge it first, when I rebase I'll just get those instances here)

**Comment by comex** [comment]
I see, thanks.  I wasn't sure about the merge order.

So it's mainly about the values that should be returned from IPC methods in failure cases?  And whereas a lot of code currently does this at the IPC boundary, plumbing it deeper into the implementation makes it more natural to accurately replicate the original behavior?

Well, I'm still skeptical, but it's not my codebase. 🤷

**Review by bunnei — APPROVED** [review]

**Pull request merged**
