### PR TITLE
Fix UI internationalization translation issue.

### PR DESCRIPTION
**Pull request by Lu-jingfeng**
Fix the issue of UI interface internationalization translation, the original code did not add Q_ OBJET macro, resulting in some strings not being translated.

### CODE REVIEW

**Comment by Hariu7** [comment]
It might wrong

**Comment by Lu-jingfeng** [comment]
There is no problem with the testing, we need to update the "*. ts" translation file.

**Comment by Lu-jingfeng** [comment]
Some strings were not translated correctly before modification.
image


After modifying the code, the string can be translated correctly.
image

**Comment by german77** [comment]
Any reason you closed the PR?

**Pull request closed without merging**
