### PR TITLE
common: Apply the nodiscard attribute where applicable

### PR DESCRIPTION
**Pull request by lioncash**
Given the common library is supposed to be a general set of utilities, we can mark functions with the nodiscard attribute to allow the compiler to create warnings when functions have their return values discarded when they shouldn't be, identifying bugs quicker. This also takes the liberty of applying noexcept to some trivial cases as well (such as the bit arithmetic utilities, etc).

This is only done with the common library, given it's supposed to contain a multitude of functions that don't necessarily change quite frequently (e.g. applying it to other libraries would need to be done on a much more strict case-by-case basis).

I've kept the individual modifications within their own commits to make review slightly nicer, however I can squash these down at the end of review if that's preferable.

### CODE REVIEW

**Comment by bunnei** [comment]
@lioncash clang-format errors are real.

**Comment by bunnei** [comment]
@lioncash reminder to address above comment

**Comment by bunnei** [comment]
@lioncash ping here

**Comment by MysticExile** [comment]
You might want to rebase this.

**Comment by lioncash** [comment]
This'll first need to have our current code style formatting looked at. Currently clang-format suggests extremely wonky formatting suggestions for some usages.

**Comment by bunnei** [comment]
@lioncash any plan to do anything with this? If as a whole, you do not plan to finish this, are there parts that can be merged? Or should this just be closed? Thanks!

**Comment by lioncash** [comment]
I may as well just close this for the time being. I can revisit this some other time

**Pull request closed without merging**
