### PR TITLE
service: hid: Implement SetNpadJoyAssignmentModeSingleWithDestination

### PR DESCRIPTION
**Pull request by german77**
Used by Let's Get Fit. I already had this implemented but I haven't really done any test at the moment. Tomorrow I will confirm if it works as intended.

### CODE REVIEW

**Comment by bunnei** [comment]
@german77 reminder to confirm this works as intended :)

**Comment by german77** [comment]
It does work. However the game has other issues that seem unrelated to this PR. I was focused on trying to find out what was wrong.

**Review by liamwhite — APPROVED** [review]

**Comment by Lexeres** [comment]
still have the problem, yuzu 3606 :(

**Comment by german77** [comment]
We are in 1441. Please open a new issue if your problem persist

**Pull request merged**
