### PR TITLE
Tegra progress 2

### PR DESCRIPTION
**Pull request by bunnei**
There's lots going on in this space, review at your own peril. I don't really expect anyone to review this line by line, but for the most part, it's code taken from Citra.
At a really high level, this PR:
* Adds some of Citra's texture forwarding and framebuffer handling stuff
* Uses it for framebuffer rendering (although it's currently flushed every frame, so there is no net gains yet)
* Implements some stuff that I explicitly removed with #254 
* Misc. video_core cleanup
* Adds some Maxwell format decoding stuff

### CODE REVIEW

**Comment by Hexagon12** [comment]
This PR breaks most, if not all of the homebrew applications.
`[   3.067291] Render.OpenGL <Debug> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:402: API OTHER 131185: Buffer detailed info: Buffer object 3 (bound to GL_ARRAY_BUFFER_ARB, usage hint is GL_DYNAMIC_DRAW) will use SYSTEM HEAP memory as the source for buffer object operations.`

`[   3.068438] Render.OpenGL <Debug> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:402: API OTHER 131185: Buffer detailed info: Buffer object 3 (bound to GL_ARRAY_BUFFER_ARB, usage hint is GL_DYNAMIC_DRAW) has been mapped WRITE_ONLY in SYSTEM HEAP memory (fast).`

`[   3.070046] Render.OpenGL <Debug> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:402: API OTHER 131185: Buffer detailed info: Buffer object 5 (bound to GL_ARRAY_BUFFER_ARB, usage hint is GL_DYNAMIC_DRAW) will use SYSTEM HEAP memory as the source for buffer object operations.`

`[   3.070535] Render.OpenGL <Debug> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:402: API OTHER 131185: Buffer detailed info: Buffer object 5 (bound to GL_ARRAY_BUFFER_ARB, usage hint is GL_DYNAMIC_DRAW) has been mapped WRITE_ONLY in SYSTEM HEAP memory (fast).`

`[   3.070995] Debug <Critical> video_core\renderer_opengl\gl_rasterizer.cpp:RasterizerOpenGL::SyncClipEnabled::<lambda_89349b42b332a43c5844b861c782ee14>::operator ():326: Assertion Failed!
Unimplemented`

**Comment by bunnei** [comment]
@Hexagon12 can you please upload example(s) of homebrew apps that are now broken? Things seem to work fine for me.

**Comment by Hexagon12** [comment]
Sure, [**here you go**](https://drive.google.com/drive/folders/18bnJ88a83wzLV5silcmko3y_emjmhMX9?usp=sharing). Test them both.

**Comment by bunnei** [comment]
Woah - lots of problems and lots of fixes. Thanks for testing, @Hexagon12 ! Issues should be resolved. Please let me know if you see any further issues.

**Comment by Hexagon12** [comment]
I cannot build Yuzu with the latest changes:
`3>C:\Users\Hexagon12\yuzu\src\video_core\renderer_opengl\gl_rasterizer_cache.cpp(1253): error C3083: 'VMManager': the symbol to the left of a '::' must be a type`

`3>C:\Users\Hexagon12\yuzu\src\video_core\renderer_opengl\gl_rasterizer_cache.cpp(1253): error C2039: 'MAX_ADDRESS': is not a member of 'Kernel'`

`3>C:\Users\Hexagon12\yuzu\src\video_core\renderer_opengl\gl_rasterizer_cache.cpp(1253): error C2065: 'MAX_ADDRESS': undeclared identifier`

**Comment by bunnei** [comment]
@Hexagon12 oops missed a line - pushed a fix, please try again. Thanks.

**Comment by bunnei** [comment]
lgtm 👍

**Pull request merged**
